/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentas_cobrar;

import clases.controlformularios;
import clientes.buscarc;
import clientes.clientesprov;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author USUARIO
 */
public class cuentasxcobrar extends javax.swing.JFrame {

    public static String codigo, nombre;
    controlformularios cen = new controlformularios();
    private final clientesprov verif = new clientesprov();

    /**
     * Creates new form cuentasxcobrar
     */
    public cuentasxcobrar() {
        initComponents();
        cargar();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaopciones = new javax.swing.JTabbedPane();
        panel1 = new org.edisoncor.gui.panel.Panel();
        lblclientee = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaestado = new javax.swing.JTable();
        txtclientee = new javax.swing.JTextField();
        btnestadoc = new javax.swing.JButton();
        lblcliente = new javax.swing.JLabel();
        btnmostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lbldesde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblhasta = new javax.swing.JLabel();
        dcinicio = new com.toedter.calendar.JDateChooser();
        dchasta = new com.toedter.calendar.JDateChooser();
        btnayudas1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaopciones.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        panel1.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel1.setColorSecundario(new java.awt.Color(255, 153, 0));

        lblclientee.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblclientee.setText("Cliente");

        lblestado.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblestado.setText("Estado de cuenta");

        tablaestado.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tablaestado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaestado);

        txtclientee.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtclientee.setEnabled(false);

        btnestadoc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnestadoc.setText("Mostar Estado de Cuenta");
        btnestadoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnestadocActionPerformed(evt);
            }
        });

        lblcliente.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcliente.setText("Código Cliente");

        btnmostrar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnmostrar.setText("Mostrar todos");
        btnmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmostrarActionPerformed(evt);
            }
        });

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtcodigo.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodigoKeyPressed(evt);
            }
        });

        txtnombre.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        lbldesde.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldesde.setText("Filtro Desde");

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Cliente");

        lblhasta.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblhasta.setText("Hasta");

        btnayudas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcliente)
                            .addComponent(lbldesde)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(dcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(lblhasta)
                                .addGap(33, 33, 33)
                                .addComponent(dchasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnmostrar)))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnestadoc, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblclientee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtclientee, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(lblestado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnayudas1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmostrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbldesde)
                                .addComponent(lblhasta))
                            .addComponent(dcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dchasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblestado))
                    .addComponent(btnayudas1))
                .addGap(11, 11, 11)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblclientee)
                    .addComponent(txtclientee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnestadoc))
        );

        tablaopciones.addTab("Balance de Clientes ", panel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablaopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void arranque() {
        int año = dcinicio.getCalendar().get(Calendar.YEAR);
        int mes = dcinicio.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcinicio.getCalendar().get(Calendar.DAY_OF_MONTH);
        int año1 = dchasta.getCalendar().get(Calendar.YEAR);
        int mes1 = dchasta.getCalendar().get(Calendar.MONTH) + 1;
        int dia1 = dchasta.getCalendar().get(Calendar.DAY_OF_MONTH);
        if (txtcodigo.getText().length() == 10) {
            conec.conectar();
            final String[] columnas = {"Codigo", "Cédula", "Cliente", "Ult. Mov", "Ult. Monto", "Balance Total"};
            String consulta = "select f.codigo_fact,f.numero_cliente,nombres_cliente,f.fecha_emision,f.total_facturave, f.total_facturave  from clientes c,facturasve f where c.cedula_cliente=f.numero_cliente  and f.numero_cliente='" + txtcodigo.getText() + "' and f.termino_pago!=1 and(f.fecha_emision>'" + año + "-" + mes + "-" + dia + "' and f.fecha_emision<'" + año1 + "-" + mes1 + "-" + dia1 + "') order by f.fecha_emision desc,f.total_facturave desc";
            tabladatos.setModel(conec.consultaget(consulta, columnas));
            conec.desconectar();
        }

    }
    Date fecha = new Date();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    private void cargar() {
        fecha = cen.fechasmas(fecha, -30);
        dcinicio.setDate(fecha);
        fecha = cen.fechasmas(fecha, 60);
        dchasta.setDate(fecha);
    }
    private void txtcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyPressed
        arranque();
    }//GEN-LAST:event_txtcodigoKeyPressed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        int index = tabladatos.getSelectedRow();
        codigo = tabladatos.getValueAt(index, 0).toString();
        nombre = tabladatos.getValueAt(index, 1).toString();
        txtclientee.setText(tabladatos.getValueAt(index, 1).toString());
        conec.conectar();
        final String[] columnas = {"Fecha", "Nro. cuota", "Nro. Factura", "Monto"};
        String consulta = "select fecha_cobrar,numero_cuota,numero_factura,monto_cuota from cuentas_cobrar c,facturasve f where f.codigo_fact=c.numero_factura and f.codigo_fact=" + tabladatos.getValueAt(index, 0).toString() + "";
        tablaestado.setModel(conec.consultaget(consulta, columnas));
        conec.desconectar();
    }//GEN-LAST:event_tabladatosMouseClicked

    private void btnmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmostrarActionPerformed
        clientesprov.verme = 100;
        buscarc nu = new buscarc();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcodigo.setText(buscarc.cedula);
        txtnombre.setText(buscarc.nombres);
        arranque();
    }//GEN-LAST:event_btnmostrarActionPerformed

    private void btnestadocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnestadocActionPerformed
        pagosxcobrar nu = new pagosxcobrar();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btnestadocActionPerformed
    private conexion conec = new conexion();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuentasxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuentasxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuentasxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuentasxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuentasxcobrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayudas1;
    private javax.swing.JButton btnestadoc;
    private javax.swing.JButton btnmostrar;
    private com.toedter.calendar.JDateChooser dchasta;
    private com.toedter.calendar.JDateChooser dcinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblclientee;
    private javax.swing.JLabel lbldesde;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblhasta;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTable tablaestado;
    private javax.swing.JTabbedPane tablaopciones;
    private javax.swing.JTextField txtclientee;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
