/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentas_cobrar;

import clases.controlformularios;
import clientes.buscarc;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author USUARIO
 */
public class pagosxcobrar extends javax.swing.JFrame {

    /**
     * Creates new form pagosxcobrar
     */
    public pagosxcobrar() {
        initComponents();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
        mostrar();
    }

    private void mostrar() {
        conec.conectar();
        final String[] columnas = {"Codigo", "Emisión", "Vencimineto", "Num. cuota", "Num. factura", "Tasa Anual", "Debito", "Condición"};
        String consulta = "select codigo_cobrar,fecha_emision,fecha_cobrar,numero_cuota,numero_factura,interes,monto_cuota,if(now()>fecha_cobrar,'Vencido', if(estado_cuota=1,'Abierto','Cerrado')) from cuentas_cobrar c ,facturasve f where f.codigo_fact=c.numero_factura and f.codigo_fact=" + cuentasxcobrar.codigo + "";
        tabladatos.setModel(conec.consultaget(consulta, columnas));
        conec.desconectar();
        lbldocumento.setText(lbldocumento.getText() + "  " + cuentasxcobrar.codigo);
        lblcliente.setText(lblcliente.getText() + "  " + buscarc.nombres);
        lbldireccion.setText(lbldireccion.getText() + "  " + buscarc.direccion);
        lblinicio.setText(lblinicio.getText() + "  " + tabladatos.getValueAt(0, 1));
        lblfinal.setText(lblfinal.getText() + "  " + tabladatos.getValueAt(tabladatos.getRowCount() - 1, 2));
        conec.conectar();
        final String[] columnas1 = {"Codigo", "Emisión", "Vencimineto", "Num. cuota", "Tasa Anual", "Monto Mensual", " 1-30 dias", " 30-60 dias", "+60 dias", "Condición"};
        consulta = "select codigo_cobrar,fecha_emision,fecha_cobrar,numero_cuota,interes,monto_cuota,if(now()>fecha_cobrar and(DATEDIFF(now(),fecha_cobrar))>1,monto_cuota+interes,0),if(now()>fecha_cobrar and(DATEDIFF(now(),fecha_cobrar))>30,monto_cuota+(interes*2),0),if(now()>fecha_cobrar and(DATEDIFF(now(),fecha_cobrar))>60,monto_cuota+(interes*3),0),if(estado_cuota=1,'Abierto','Cerrado') from cuentas_cobrar c ,facturasve f where f.codigo_fact=c.numero_factura and f.codigo_fact=" + cuentasxcobrar.codigo + "";
        tabladatos1.setModel(conec.consultaget(consulta, columnas1));
        conec.desconectar();
        lbldocumento1.setText(lbldocumento1.getText() + "  " + cuentasxcobrar.codigo);
        lblcliente1.setText(lblcliente1.getText() + "  " + buscarc.nombres);
        lbldireccion1.setText(lbldireccion1.getText() + "  " + buscarc.direccion);
        lblinicio1.setText(lblinicio1.getText() + "  " + tabladatos.getValueAt(0, 1));
        lblfinal1.setText(lblfinal1.getText() + "  " + tabladatos.getValueAt(tabladatos.getRowCount() - 1, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaopciones = new javax.swing.JTabbedPane();
        panel3 = new org.edisoncor.gui.panel.Panel();
        lblfinal = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        btnpago = new javax.swing.JButton();
        lblinicio = new javax.swing.JLabel();
        lbldocumento = new javax.swing.JLabel();
        lblcliente = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        btnayudas1 = new javax.swing.JButton();
        panel4 = new org.edisoncor.gui.panel.Panel();
        btnpago1 = new javax.swing.JButton();
        lblfinal1 = new javax.swing.JLabel();
        lblinicio1 = new javax.swing.JLabel();
        lbldireccion1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos1 = new javax.swing.JTable();
        btncancelar1 = new javax.swing.JButton();
        lbldocumento1 = new javax.swing.JLabel();
        lblcliente1 = new javax.swing.JLabel();
        btnayudas2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaopciones.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        lblfinal.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblfinal.setText("Fecha Final del credito:");

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        btnpago.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnpago.setText("Asigna Pago");
        btnpago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagoActionPerformed(evt);
            }
        });

        lblinicio.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblinicio.setText("Fecha del Credito:");

        lbldocumento.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldocumento.setText("Número de documento: ");

        lblcliente.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcliente.setText("Cliente del Credito");

        lbldireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion.setText("Dirección del proveedor");

        btnayudas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnpago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldireccion)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldocumento)
                                    .addComponent(lblcliente))
                                .addGap(246, 246, 246)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfinal)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(lblinicio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnayudas1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldocumento)
                            .addComponent(lblinicio))
                        .addGap(32, 32, 32))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(btnayudas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcliente)
                    .addComponent(lblfinal))
                .addGap(28, 28, 28)
                .addComponent(lbldireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpago, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tablaopciones.addTab("Documentos en la cuenta", panel3);

        panel4.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel4.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        btnpago1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnpago1.setText("Asigna Pago");
        btnpago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpago1ActionPerformed(evt);
            }
        });

        lblfinal1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblfinal1.setText("Fecha Final del credito:");

        lblinicio1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblinicio1.setText("Fecha del Credito:");

        lbldireccion1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion1.setText("Dirección del proveedor");

        tabladatos1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladatos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabladatos1);

        btncancelar1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar1.setText("Cancelar");
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });

        lbldocumento1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldocumento1.setText("Número de documento: ");

        lblcliente1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcliente1.setText("Cliente del Credito");

        btnayudas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(btnpago1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldireccion1)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldocumento1)
                                    .addComponent(lblcliente1))
                                .addGap(246, 246, 246)
                                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblfinal1)
                                    .addGroup(panel4Layout.createSequentialGroup()
                                        .addComponent(lblinicio1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnayudas2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldocumento1)
                            .addComponent(lblinicio1)))
                    .addComponent(btnayudas2))
                .addGap(32, 32, 32)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcliente1)
                    .addComponent(lblfinal1))
                .addGap(28, 28, 28)
                .addComponent(lbldireccion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpago1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btncancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tablaopciones.addTab("Pendientes por pagar", panel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private conexion conec = new conexion();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void btnpagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagoActionPerformed
        interes = "0";
        balance = tabladatos.getValueAt(index, 6).toString();
        estado = tabladatos.getValueAt(index, 7).toString();
        numeroc = tabladatos.getValueAt(index, 0).toString();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        try {
            fecha1 = formatoFecha.parse(tabladatos.getValueAt(index, 2).toString());
        } catch (ParseException ex) {
            Logger.getLogger(pagosxcobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!"Cerrado".equals(estado) && fecha.before(fecha1)) {
            cierre();
        }
    }//GEN-LAST:event_btnpagoActionPerformed
    private void cierre() {
        int control = 0, otro = 0;
        for (int i = 0; i < tabladatos.getRowCount() - 1; i++) {
            if ("Cerrado".equals(tabladatos.getValueAt(i, 7).toString()) || "Vencido".equals(tabladatos.getValueAt(i, 7).toString())) {
                control = i;
                otro = 1;
            }
        }
        if (control == index) {
            reciboxcobrar nu = new reciboxcobrar();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            mostrar();
        }
        if (control + 1 == index && otro != 0) {
            reciboxcobrar nu = new reciboxcobrar();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            mostrar();
        }

    }

    private void cierre1() {
        int control = 0;
        for (int i = 0; i < tabladatos1.getRowCount() - 1; i++) {
            if ("Cerrado".equals(tabladatos1.getValueAt(i, 9).toString())) {
                control = i;
            }
        }
        if (control + 1 == index) {
            reciboxcobrar nu = new reciboxcobrar();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        }

    }

    //kidjikddhjdd
    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        index = tabladatos.getSelectedRow();

    }//GEN-LAST:event_tabladatosMouseClicked

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelar1ActionPerformed

    private void tabladatos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatos1MouseClicked
        index = tabladatos1.getSelectedRow();
    }//GEN-LAST:event_tabladatos1MouseClicked

    private void btnpago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpago1ActionPerformed
        interes = tabladatos1.getValueAt(index, 4).toString();
        balance();
        estado = tabladatos.getValueAt(index, 7).toString();
        numeroc = tabladatos.getValueAt(index, 0).toString();
        if (!"Cerrado".equals(estado) && !"Abierto".equals(estado)) {
            cierre1();
        }
    }//GEN-LAST:event_btnpago1ActionPerformed
    private Date fecha = new Date();
    private Date fecha1 = new Date();
    private int index;

    private void balance() {

        if (!"0.0".equals(tabladatos1.getValueAt(index, 6).toString()) && "0.0".equals(tabladatos1.getValueAt(index, 7).toString()) && "0.0".equals(tabladatos1.getValueAt(index, 8).toString())) {
            balance = tabladatos1.getValueAt(index, 6).toString();
        } else if (!"0.0".equals(tabladatos.getValueAt(index, 6).toString()) && !"0.0".equals(tabladatos1.getValueAt(index, 7).toString()) && "0.0".equals(tabladatos1.getValueAt(index, 8).toString())) {
            balance = tabladatos1.getValueAt(index, 7).toString();
        } else if (!"0.0".equals(tabladatos1.getValueAt(index, 6).toString()) && !"0.0".equals(tabladatos1.getValueAt(index, 7).toString()) && !"0.0".equals(tabladatos1.getValueAt(index, 8).toString())) {
            balance = tabladatos1.getValueAt(index, 8).toString();
        }
    }
    public static String interes, balance, estado, numeroc;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagosxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagosxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagosxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagosxcobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagosxcobrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayudas1;
    private javax.swing.JButton btnayudas2;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btnpago;
    private javax.swing.JButton btnpago1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JLabel lblcliente1;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lbldireccion1;
    private javax.swing.JLabel lbldocumento;
    private javax.swing.JLabel lbldocumento1;
    private javax.swing.JLabel lblfinal;
    private javax.swing.JLabel lblfinal1;
    private javax.swing.JLabel lblinicio;
    private javax.swing.JLabel lblinicio1;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTable tabladatos1;
    private javax.swing.JTabbedPane tablaopciones;
    // End of variables declaration//GEN-END:variables
}
