/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roles;

import clases.controlformularios;
import clases.oayuda;
import clientes.buscarc;
import clientes.buscare;
import clientes.clientesprov;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author Cristian
 */
public class rolemplado extends javax.swing.JFrame {

    controlformularios cen = new controlformularios();

    /**
     * Creates new form rolemplado
     */
    public rolemplado() {
        initComponents();
        cargar();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        jLabel3 = new javax.swing.JLabel();
        lblcontador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encabezado = new javax.swing.JTable();
        btncancelar = new javax.swing.JButton();
        lblperiodo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnautorizacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        btngrabar = new javax.swing.JButton();
        txtautorizacion = new javax.swing.JTextField();
        btncontador = new javax.swing.JButton();
        lblautorizacion = new javax.swing.JLabel();
        dcfecha = new com.toedter.calendar.JDateChooser();
        txtcontador = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        lblhorase = new javax.swing.JLabel();
        txthextras = new javax.swing.JTextField();
        lblhorass = new javax.swing.JLabel();
        txthsuple = new javax.swing.JTextField();
        lblanticipos = new javax.swing.JLabel();
        txtanticipos = new javax.swing.JTextField();
        lblmultas = new javax.swing.JLabel();
        txtmultas = new javax.swing.JTextField();
        lblcomisiones = new javax.swing.JLabel();
        txtcomisariatos = new javax.swing.JTextField();
        btnsiguiente = new javax.swing.JButton();
        lblnombres = new javax.swing.JLabel();
        btnanterior = new javax.swing.JButton();
        txtnombres = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnayuda = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel3.setEnabled(false);

        labelMetric7.setForeground(new java.awt.Color(51, 51, 255));
        labelMetric7.setText("ROL DE PAGOS");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        lblcontador.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcontador.setText("Contador CI:");

        encabezado.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        encabezado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Detalles", "Ingresos", "Egresos", "Totales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(encabezado);

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        lblperiodo.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblperiodo.setText("Periodo");

        jLabel5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel5.setText("mes del 2014");

        btnautorizacion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnautorizacion.setText("...");
        btnautorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnautorizacionActionPerformed(evt);
            }
        });

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        btngrabar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });

        txtautorizacion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtautorizacion.setEnabled(false);
        txtautorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautorizacionActionPerformed(evt);
            }
        });

        btncontador.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncontador.setText("...");
        btncontador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontadorActionPerformed(evt);
            }
        });

        lblautorizacion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblautorizacion.setText("Autorizacion CI:");

        dcfecha.setEnabled(false);

        txtcontador.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcontador.setEnabled(false);

        lblfecha.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblfecha.setText("Fecha ");

        lblcedula.setText("CI Empleado: ");

        txtcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcedula.setEnabled(false);

        lblhorase.setText("Horas Extras:");

        txthextras.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txthextras.setText("0");
        txthextras.setEnabled(false);

        lblhorass.setText("Horas Suplementarias:");

        txthsuple.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txthsuple.setText("0");
        txthsuple.setEnabled(false);

        lblanticipos.setText("Anticipo Sueldo:");

        txtanticipos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtanticipos.setText("0");
        txtanticipos.setEnabled(false);

        lblmultas.setText("Multas:");

        txtmultas.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtmultas.setText("0");

        lblcomisiones.setText("Comisariato: ");

        txtcomisariatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcomisariatos.setText("0");

        btnsiguiente.setText(">>");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        lblnombres.setText("Nombres y Apellidos");

        btnanterior.setText("<<");
        btnanterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanteriorActionPerformed(evt);
            }
        });

        txtnombres.setEnabled(false);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jButton1.setText("OBTENER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btngrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(262, 262, 262)
                                        .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(lblcontador)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcontador, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btncontador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(lblautorizacion)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addComponent(lblhorase)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txthextras, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                                .addComponent(lblhorass)
                                                .addGap(18, 18, 18)
                                                .addComponent(txthsuple, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblcedula)
                                                    .addComponent(lblfecha))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnanterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnsiguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnbuscar))
                                    .addComponent(lblnombres))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(lblperiodo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                                .addComponent(lblanticipos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                                .addComponent(txtanticipos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addComponent(lblmultas)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtmultas, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                                .addComponent(lblcomisiones)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtcomisariatos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(2, 2, 2)))
                                .addGap(72, 72, 72))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(btnayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblperiodo)
                            .addComponent(jLabel5)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfecha)
                            .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblanticipos)
                            .addComponent(txtanticipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmultas)
                            .addComponent(txtmultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcomisiones)
                            .addComponent(txtcomisariatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcedula)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsiguiente)
                            .addComponent(btnanterior)
                            .addComponent(btnbuscar))
                        .addGap(12, 12, 12)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombres)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhorase)
                            .addComponent(txthextras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhorass)
                            .addComponent(txthsuple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontador)
                    .addComponent(lblautorizacion)
                    .addComponent(txtcontador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncontador)
                    .addComponent(btnautorizacion)
                    .addComponent(btngrabar)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened
    private void cargar() {
        try {
            conec.conectar();
            conec.consultaset("SET @row=0");
            String columnas[] = {"N°", "Empleado", "Cédula", "sueldo", "F.de reserva", "H.Extras", "V. Extras", "H. Supl", "V. Supl", "Bono", "T. Ingresos", "AP.IESS", "Anticipos", "Multas", "Otros", "Imp. Renta", "T. Egresos", "N.Recibir"};
            tabladatos.setModel(conec.consultaget("select (@row:=@row+1) AS row,concat_ws(' ',nombres_empleado,apellidos_empleado) as empleado,cedula_empleado,((sueldo_empleado*(sum(horas_tra)))/160) as sueldo,((((sueldo_empleado*(sum(horas_tra)))/160)*p.fondo_reserva)/100)as reserva,(sum(horas_ext))as he,((sueldo_empleado*(sum(horas_ext)))/160)as hec,(sum(horas_ext)/2)as hs,(((sueldo_empleado*(sum(horas_ext)/2))/160)/2)as hsc,((((sueldo_empleado*(sum(horas_tra)))/160)*p.bonos)/100)as bono,('0')as ingresos,((((sueldo_empleado*(sum(horas_tra)))/160)*p.iess)/100)as iess,('0')as anticipos,('0')as multas,('0')as otras,((((sueldo_empleado*(sum(horas_tra)))/160)*p.impuesto_renta)/100)as renta,('')as egresos,('')as neto from empleados,asistencias,parametros p  where codigo_emple=cedula_empleado  and estado_empleado=1 and fecha_actual>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) group by cedula_empleado", columnas));
            txtcedula.setText("" + tabladatos.getValueAt(0, 2));
            txtnombres.setText("" + tabladatos.getValueAt(0, 1));
            conec.desconectar();
            dcfecha.setDate(fecha);
            asigbus(txtcedula.getText());
        } catch (java.lang.ArrayIndexOutOfBoundsException ja) {

        }
    }
    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        //index = tabladatos.getSelectedRow();

    }//GEN-LAST:event_tabladatosMouseClicked

    private void txtautorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautorizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtautorizacionActionPerformed

    private void btncontadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontadorActionPerformed
        clientesprov.verme = 100;
        buscare nu = new buscare();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcontador.setText(buscare.cedula);
        txtcedula.setText(buscare.nombres);
    }//GEN-LAST:event_btncontadorActionPerformed

    private void btnautorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnautorizacionActionPerformed
        clientesprov.verme = 100;
        buscare nu = new buscare();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtautorizacion.setText(buscare.cedula);
    }//GEN-LAST:event_btnautorizacionActionPerformed

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed
        int año = dcfecha.getCalendar().get(Calendar.YEAR);
        int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        if (txtcontador.getText().length() > 0 && txtautorizacion.getText().length() > 0) {
            int seleccion = JOptionPane.showOptionDialog(this, "¿Confimar Guardado del Rol General", "Guardar Rol de Pago", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");
            if (seleccion == 0) {
                conec.conectar();
                conec.consultaset("INSERT INTO `alexanderflower`.`roles` (`fecha_rol`, `periodo_rol`, `contador_rol`, `autorizacion_rol`,`estado_rol`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + lblperiodo.getText() + "', '" + txtcontador.getText() + "', '" + txtautorizacion.getText() + "','1');");
                for (int i = 0; i < tabladatos.getRowCount(); i++) {
                    conec.consultaset("INSERT INTO `alexanderflower`.`detalle_rol` (`numero_rol`, `empleado_rol`, `codigo_emprol`, `sueldo`, `freserva`, `hextras`, `vextras`, `hsuplementarias`, `vsuplementarias`, `bono`, `tingresos`, `aiess`, `anticipos`, `multas`, `retenciones`, `otros`, `irenta`, `tegresos`, `nrecibir`, `codigo_rol`) VALUES ('" + tabladatos.getValueAt(i, 0).toString() + "', '" + tabladatos.getValueAt(i, 1).toString() + "', '" + tabladatos.getValueAt(i, 2).toString() + "', '" + tabladatos.getValueAt(i, 3).toString() + "', '" + tabladatos.getValueAt(i, 4).toString() + "', '" + tabladatos.getValueAt(i, 5).toString() + "', '" + tabladatos.getValueAt(i, 6).toString() + "', '" + tabladatos.getValueAt(i, 7).toString() + "', '" + tabladatos.getValueAt(i, 8).toString() + "', '" + tabladatos.getValueAt(i, 9).toString() + "', '" + tabladatos.getValueAt(i, 10).toString() + "', '" + tabladatos.getValueAt(i, 11).toString() + "', '" + tabladatos.getValueAt(i, 12).toString() + "', '" + tabladatos.getValueAt(i, 13).toString() + "', '0', '" + tabladatos.getValueAt(i, 14).toString() + "', '" + tabladatos.getValueAt(i, 15).toString() + "', '" + tabladatos.getValueAt(i, 16).toString() + "', '" + tabladatos.getValueAt(i, 17).toString() + "',  '" + conec.consultac2get("select  codigo_rol from roles order by codigo_rol desc limit 1", "codigo_rol") + "');");
                    String codigoa = conec.consultac2get("select t.roles from transacciones t where roles is not null order by roles desc limit 1", "roles");
                    if ("".equals(codigoa)) {
                        codigoa = "0";
                    }
                    int codigom = Integer.parseInt(codigoa);
                    codigom++;
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `debe`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta1 where nombre_subcuenta1='GASTOS SUELDOS'", "cod_subcuenta1") + "', 'GASTO SUELDO', '" + tabladatos.getValueAt(i, 3) + "', '" + codigom + "');");
                    double patronal = (Double.parseDouble(tabladatos.getValueAt(i, 3).toString()) * Double.parseDouble(conec.consultac2get("select * from parametros", "iess"))) / 100;
                    double personal = (Double.parseDouble(tabladatos.getValueAt(i, 3).toString()) * Double.parseDouble(conec.consultac2get("select * from parametros", "iesspersonal"))) / 100;
                    double totales1 = (Double.parseDouble(tabladatos.getValueAt(i, 3).toString()) + patronal) - (patronal + personal + Double.parseDouble(tabladatos.getValueAt(i, 12).toString()));
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `debe`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta1 where nombre_subcuenta1='GASTOS APORTES PATRONALES'", "cod_subcuenta1") + "', 'GASTO APORTE PATRONAL', '" + patronal + "', '" + codigom + "');");
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta1 where nombre_subcuenta1='APORTE PATRONAL POR PAGAR'", "cod_subcuenta1") + "', 'APORTE PATRONAL POR PAGAR', '" + patronal + "', '" + codigom + "');");
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta1 where nombre_subcuenta1='RETENCION APORTE PERSONAL'", "cod_subcuenta1") + "', 'RETENCION APORTE PERSONAL', '" + personal + "', '" + codigom + "');");
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='ANTICIPOS QUINCENA'", "cod_subcuenta2") + "', 'ANTICIPO QUINCENA', '" + tabladatos.getValueAt(i, 12).toString() + "', '" + codigom + "');");
                    conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `roles`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='BANCOS'", "cod_subcuenta2") + "', 'BANCOS', '" + totales1 + "', '" + codigom + "');");
                }

                conec.desconectar();
                this.setVisible(false);
            }
        }

    }//GEN-LAST:event_btngrabarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    int i = 0;
    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed

        txtnombres.setText("" + tabladatos.getValueAt(i, 1));
        txtcedula.setText("" + tabladatos.getValueAt(i, 2));

        if (i == tabladatos.getRowCount() - 1) {
            i = tabladatos.getRowCount() - 1;
            index = i;
        } else {
            i++;
            index = i;
        }
        busasig(txtcedula.getText());
        sumai();
        sumae();
        totales();
        txthextras.setText(tabladatos.getValueAt(i, 5).toString());
        txthsuple.setText(tabladatos.getValueAt(i, 7).toString());
        txtanticipos.setText(tabladatos.getValueAt(i, 12).toString());
        txtmultas.setText(tabladatos.getValueAt(i, 13).toString());
        txtcomisariatos.setText(tabladatos.getValueAt(i, 14).toString());

    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnanteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanteriorActionPerformed

        txtnombres.setText("" + tabladatos.getValueAt(i, 1));
        txtcedula.setText("" + tabladatos.getValueAt(i, 2));

        if (i == (tabladatos.getRowCount() - tabladatos.getRowCount())) {
            i = 0;
            index = i;
        } else {
            i--;
            index = i;
        }
        busasig(txtcedula.getText());

        sumai();
        sumae();
        totales();
        txthextras.setText(tabladatos.getValueAt(i, 5).toString());
        txthsuple.setText(tabladatos.getValueAt(i, 7).toString());
        txtanticipos.setText(tabladatos.getValueAt(i, 12).toString());
        txtmultas.setText(tabladatos.getValueAt(i, 13).toString());
        txtcomisariatos.setText(tabladatos.getValueAt(i, 14).toString());

    }//GEN-LAST:event_btnanteriorActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        clientesprov.verme = 100;
        buscare cliente = new buscare();
        dialogo jd = new dialogo(cliente, true);
        jd.setContentPane(cliente.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcedula.setText(buscare.cedula);
        asigbus(txtcedula.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conec.conectar();
        String anti = (conec.consultac2get("select sum(valor_anticipo) from anticipos where cod_empleado=1004874200 and fecha_anticipo>DATE_SUB(CURDATE(),INTERVAL 30 DAY)", "sum(valor_anticipo)"));
        conec.desconectar();
        if ("null".equals(anti)) {
            anti = "0";
            JOptionPane.showMessageDialog(this, "No existen anticipos");
        }

        txtanticipos.setText(anti);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed
    private void busasig(String cedula) {
        for (int j = 0; j < tabladatos.getRowCount(); j++) {
            if (cedula.equals(tabladatos.getValueAt(j, 2).toString())) {
                tabladatos.setValueAt(txthextras.getText(), j, 5);
                tabladatos.setValueAt(txthsuple.getText(), j, 7);
                tabladatos.setValueAt(txtanticipos.getText(), j, 12);
                tabladatos.setValueAt(txtmultas.getText(), j, 13);
                tabladatos.setValueAt(txtcomisariatos.getText(), j, 14);
            }
        }
    }

    private void asigbus(String cedula) {
        for (int j = 0; j < tabladatos.getRowCount(); j++) {
            if (cedula.equals(tabladatos.getValueAt(j, 2).toString())) {
                txthextras.setText(tabladatos.getValueAt(i, 5).toString());
                txthsuple.setText(tabladatos.getValueAt(i, 7).toString());
                txtanticipos.setText(tabladatos.getValueAt(i, 12).toString());
                txtmultas.setText(tabladatos.getValueAt(i, 13).toString());
                txtcomisariatos.setText(tabladatos.getValueAt(i, 14).toString());
            }
        }
    }
    private conexion conec = new conexion();

    private int index;
    private Date fecha = new Date();

    private void sumai() {
        double sueldo = Double.parseDouble(tabladatos.getValueAt(index, 3).toString());
        double uno = Double.parseDouble(tabladatos.getValueAt(index, 4).toString());
        double dos = Double.parseDouble(tabladatos.getValueAt(index, 6).toString());
        double tres = Double.parseDouble(tabladatos.getValueAt(index, 8).toString());
        double cuatro = Double.parseDouble(tabladatos.getValueAt(index, 9).toString());
        double suma = sueldo + uno + dos + tres + cuatro;
        tabladatos.setValueAt(conec.redondear(suma), index, 10);
    }

    private void sumae() {
        double uno = Double.parseDouble(tabladatos.getValueAt(index, 11).toString());
        double dos = Double.parseDouble(tabladatos.getValueAt(index, 12).toString());
        double tres = Double.parseDouble(tabladatos.getValueAt(index, 13).toString());
        double cinco = Double.parseDouble(tabladatos.getValueAt(index, 14).toString());
        double seis = Double.parseDouble(tabladatos.getValueAt(index, 15).toString());
        double suma = uno + dos + tres + cinco + seis;
        tabladatos.setValueAt(conec.redondear(suma), index, 16);
    }

    private void totales() {
        double uno = Double.parseDouble(tabladatos.getValueAt(index, 10).toString());
        double dos = Double.parseDouble(tabladatos.getValueAt(index, 16).toString());
        double suma = uno - dos;
        tabladatos.setValueAt(conec.redondear(suma), index, 17);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rolemplado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rolemplado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rolemplado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rolemplado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rolemplado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanterior;
    private javax.swing.JButton btnautorizacion;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnayuda1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncontador;
    private javax.swing.JButton btngrabar;
    private javax.swing.JButton btnsiguiente;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JTable encabezado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private javax.swing.JLabel lblanticipos;
    private javax.swing.JLabel lblautorizacion;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcomisiones;
    private javax.swing.JLabel lblcontador;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhorase;
    private javax.swing.JLabel lblhorass;
    private javax.swing.JLabel lblmultas;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblperiodo;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtanticipos;
    private javax.swing.JTextField txtautorizacion;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcomisariatos;
    private javax.swing.JTextField txtcontador;
    private javax.swing.JTextField txthextras;
    private javax.swing.JTextField txthsuple;
    private javax.swing.JTextField txtmultas;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
