/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import clases.controlformularios;
import clientes.buscarp;
import javax.swing.JDialog;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.imagenes;
import proyecto_integrador.panel;
import proyecto_integrador.validaciones;

/**
 *
 * @author usuario
 */
public class modielipro extends javax.swing.JFrame {

    private validaciones validar = new validaciones();
    public static int ca;
    conexion conec = new conexion();

    /**
     * Creates new form modielipro
     */
    public modielipro() {
        initComponents();
        cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        lbltitulo = new org.edisoncor.gui.label.LabelMetric();
        jLabel1 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblbodega = new javax.swing.JLabel();
        txtbodega = new javax.swing.JTextField();
        btnbodega = new javax.swing.JButton();
        lblprecio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtproducto = new javax.swing.JTextField();
        lblproducto = new javax.swing.JLabel();
        lblcantidadi = new javax.swing.JLabel();
        lblcompra = new javax.swing.JLabel();
        txtcantidadi = new javax.swing.JTextField();
        lblproveedor = new javax.swing.JLabel();
        txtproveedor = new javax.swing.JTextField();
        btnproveedor = new javax.swing.JButton();
        txtunidadc = new javax.swing.JTextField();
        btnunidadc = new javax.swing.JButton();
        txtsubcategoria = new javax.swing.JTextField();
        btnsubcategoria = new javax.swing.JButton();
        txtcategoria = new javax.swing.JTextField();
        lblcategoria = new javax.swing.JLabel();
        lblsubcategoria = new javax.swing.JLabel();
        txtcantidadmi = new javax.swing.JTextField();
        txtcantidadma = new javax.swing.JTextField();
        lblventa = new javax.swing.JLabel();
        lblcantidadmi = new javax.swing.JLabel();
        lblcantidadma = new javax.swing.JLabel();
        lblcontiene = new javax.swing.JLabel();
        txtcontiene = new javax.swing.JTextField();
        btnunidadv = new javax.swing.JButton();
        txtunidadv = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        lbltitulo.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo.setText("...........................................................");
        lbltitulo.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lbltitulo.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lblbodega.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbodega.setText("Producto a Guardar en la  bodega");

        txtbodega.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtbodega.setToolTipText("Ingresa la Informacion Aqui ");

        btnbodega.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbodega.setText("...");
        btnbodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbodegaActionPerformed(evt);
            }
        });

        lblprecio.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblprecio.setText("Precio del Producto");

        txtprecio.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtprecio.setToolTipText("Ingresa la Informacion Aqui ");
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        txtproducto.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtproducto.setToolTipText("Ingresa la Informacion Aqui ");
        txtproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproductoKeyTyped(evt);
            }
        });

        lblproducto.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblproducto.setText("Nombre Producto");

        lblcantidadi.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcantidadi.setText("Cantidad Inicial");

        lblcompra.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcompra.setText("Producto por compra ");

        txtcantidadi.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcantidadi.setToolTipText("Ingresa la Informacion Aqui ");
        txtcantidadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadiKeyTyped(evt);
            }
        });

        lblproveedor.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblproveedor.setText("Proveedor Principal");

        txtproveedor.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtproveedor.setToolTipText("Ingresa la Informacion Aqui ");

        btnproveedor.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnproveedor.setText("...");
        btnproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedorActionPerformed(evt);
            }
        });

        txtunidadc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtunidadc.setToolTipText("Ingresa la Informacion Aqui ");

        btnunidadc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnunidadc.setText("...");
        btnunidadc.setToolTipText("");
        btnunidadc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunidadcActionPerformed(evt);
            }
        });

        txtsubcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtsubcategoria.setToolTipText("Ingresa la Informacion Aqui ");
        txtsubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubcategoriaActionPerformed(evt);
            }
        });

        btnsubcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnsubcategoria.setText("...");
        btnsubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubcategoriaActionPerformed(evt);
            }
        });

        txtcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcategoria.setToolTipText("Ingresa la Informacion Aqui ");

        lblcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcategoria.setText("Categoria Producto");

        lblsubcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblsubcategoria.setText("Subcategoria");

        txtcantidadmi.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcantidadmi.setToolTipText("Ingresa la Informacion Aqui ");
        txtcantidadmi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadmiKeyTyped(evt);
            }
        });

        txtcantidadma.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcantidadma.setToolTipText("Ingresa la Informacion Aqui ");
        txtcantidadma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadmaActionPerformed(evt);
            }
        });
        txtcantidadma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadmaKeyTyped(evt);
            }
        });

        lblventa.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblventa.setText("Producto por venta ");

        lblcantidadmi.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcantidadmi.setText("Cantidad Minima Producto");

        lblcantidadma.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcantidadma.setText("Cantida Maxima Producto");

        lblcontiene.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcontiene.setText("Y Contendra");

        txtcontiene.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcontiene.setToolTipText("Ingresa la Informacion Aqui ");
        txtcontiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontieneActionPerformed(evt);
            }
        });
        txtcontiene.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontieneKeyTyped(evt);
            }
        });

        btnunidadv.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnunidadv.setText("...");
        btnunidadv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunidadvActionPerformed(evt);
            }
        });

        txtunidadv.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtunidadv.setToolTipText("Ingresa la Informacion Aqui ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblproducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblprecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcompra)
                                    .addComponent(lblcantidadi)
                                    .addComponent(lblproveedor))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(txtunidadc, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtproveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcantidadi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnunidadc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcontiene, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblcontiene)
                                        .addGap(253, 253, 253))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblventa)
                                        .addGap(83, 83, 83)
                                        .addComponent(txtunidadv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnunidadv, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcantidadmi)
                                        .addComponent(lblcategoria)
                                        .addComponent(lblsubcategoria)
                                        .addComponent(lblcantidadma))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtcantidadmi, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtcantidadma, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtsubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnsubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(17, 17, 17)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblbodega)
                        .addGap(29, 29, 29)
                        .addComponent(txtbodega, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnbodega, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbodega, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblbodega))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblsubcategoria))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnsubcategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtcategoria))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcantidadmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcantidadmi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtcantidadma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcantidadma))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblventa)
                                        .addComponent(btnunidadv))
                                    .addComponent(txtunidadv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(btnunidadc)
                            .addGap(8, 8, 8))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblproducto)
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblprecio))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtunidadc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcompra))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcantidadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblcantidadi))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnproveedor))
                                .addComponent(lblproveedor)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontiene)
                    .addComponent(txtcontiene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnactualizar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addComponent(btneliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnactualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btncancelar))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        if (txtproducto.getText().length() > 0) {
            conec.conectar();
            String proveedor = conec.consultac2get("select *  from proveedores where nombre_eproveedor='" + txtproveedor.getText() + "'", "ruc_proveedor");
            int subcategoria = conec.consultac1get("select *  from subcategoria where nombre_subcategoria='" + txtsubcategoria.getText() + "'", "cod_subcategoria");
            int bodega = conec.consultac1get("select *  from bodega where nombre_bodega='" + txtbodega.getText() + "'", "cod_bodega");
            int unidadv = conec.consultac1get("select *  from unidades where nombre_unidad='" + txtunidadv.getText() + "'", "cod_unidad");
            int unidadc = conec.consultac1get("select *  from unidades where nombre_unidad='" + txtunidadc.getText() + "'", "cod_unidad");
            String consulta = "UPDATE `alexanderflower`.`productos` SET `nombre_producto`='" + txtproducto.getText() + "',`unidad_productoc`='" + unidadc + "', `cantidadi_producto`=" + txtcantidadi.getText() + ", `cantidadmi_producto`=" + txtcantidadmi.getText() + ", `cantidadma_producto`=" + txtcantidadma.getText() + ", `proveedor_producto`='" + proveedor + "', `subcategoria_producto`=" + subcategoria + ", `bodega_producto`=" + bodega + ", `unidad_productov`=" + unidadv + ", `cantidadauni_producto`=" + txtcontiene.getText() + ", `precio_producto`=" + txtprecio.getText() + " WHERE `cod_producto`='" + codigo + "';";
            conec.consultaset(consulta);
            conec.desconectar();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed
    private void eliminar() {
        txtproducto.setEnabled(false);
        txtcantidadmi.setEnabled(false);
        txtcantidadma.setEnabled(false);
        txtprecio.setEnabled(false);
        txtproveedor.setEnabled(false);
        txtcategoria.setEnabled(false);
        txtsubcategoria.setEnabled(false);
        txtbodega.setEnabled(false);
        txtunidadc.setEnabled(false);
        txtunidadv.setEnabled(false);
        txtcontiene.setEnabled(false);
        btnproveedor.setEnabled(false);
        btnsubcategoria.setEnabled(false);
        btnbodega.setEnabled(false);
        btnunidadc.setEnabled(false);
        btnunidadv.setEnabled(false);
    }

    private void cargar() {

        txtcantidadi.setEnabled(false);
        codigo = buscarpro.codigo;
        txtproducto.setText(buscarpro.producto);
        txtcantidadi.setText(buscarpro.cantidadi);
        txtcantidadmi.setText(buscarpro.cantidadmi);
        txtcantidadma.setText(buscarpro.cantidadma);
        txtprecio.setText(buscarpro.precio);
        txtproveedor.setText(buscarpro.proveedor);
        txtcategoria.setText(buscarpro.subcategoria);
        txtsubcategoria.setText(buscarpro.subcategoria);
        txtbodega.setText(buscarpro.bodega);
        txtunidadc.setText(buscarpro.unidadc);
        txtunidadv.setText(buscarpro.unidadv);
        txtcontiene.setText(buscarpro.cantidaduni);
        if (panelinventario.vermep == 0) {
            lbltitulo.setText("Eliminar Información");
            btneliminar.setLocation(btnactualizar.getLocation().x, btnactualizar.getLocation().y);
            btnactualizar.setVisible(false);
            eliminar();

        } else if (panelinventario.vermep == 1) {
            lbltitulo.setText("Actualizar Información");
            btneliminar.setVisible(false);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        conec.conectar();
        String consulta = "UPDATE `alexanderflower`.`productos` SET `estado_producto`='0' WHERE `cod_producto`='" + codigo + "';";
        conec.consultaset(consulta);
        conec.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbodegaActionPerformed
        ca = 1;
        nuevabo nu = new nuevabo();
        ca = 0;
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtbodega.setText(nu.bodegaget());
    }//GEN-LAST:event_btnbodegaActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductoKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtproductoKeyTyped

    private void txtcantidadiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadiKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtcantidadiKeyTyped

    private void btnproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedorActionPerformed
        buscarp nu = new buscarp();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtproveedor.setText(buscarp.empresa);
    }//GEN-LAST:event_btnproveedorActionPerformed

    private void btnunidadcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunidadcActionPerformed
        ca = 1;
        nuevaun nu = new nuevaun();
        ca = 0;
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtunidadc.setText(nu.unidadget());
    }//GEN-LAST:event_btnunidadcActionPerformed

    private void txtsubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubcategoriaActionPerformed

    private void btnsubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubcategoriaActionPerformed
        ca = 1;
        nuevasca nu = new nuevasca();
        ca = 0;
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcategoria.setText(nu.categoriaget());
        txtsubcategoria.setText(nu.sucategoriaget());
    }//GEN-LAST:event_btnsubcategoriaActionPerformed

    private void txtcantidadmiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadmiKeyTyped
        validar.solonumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadmiKeyTyped

    private void txtcantidadmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadmaActionPerformed

    }//GEN-LAST:event_txtcantidadmaActionPerformed

    private void txtcantidadmaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadmaKeyTyped
        validar.solonumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadmaKeyTyped

    private void txtcontieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontieneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontieneActionPerformed

    private void txtcontieneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontieneKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtcontieneKeyTyped

    private void btnunidadvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunidadvActionPerformed
        ca = 1;
        nuevaun nu = new nuevaun();
        ca = 0;
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtunidadv.setText(nu.unidadget());
    }//GEN-LAST:event_btnunidadvActionPerformed
    private String codigo;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modielipro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modielipro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modielipro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modielipro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modielipro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbodega;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnproveedor;
    private javax.swing.JButton btnsubcategoria;
    private javax.swing.JButton btnunidadc;
    private javax.swing.JButton btnunidadv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblbodega;
    private javax.swing.JLabel lblcantidadi;
    private javax.swing.JLabel lblcantidadma;
    private javax.swing.JLabel lblcantidadmi;
    private javax.swing.JLabel lblcategoria;
    private javax.swing.JLabel lblcompra;
    private javax.swing.JLabel lblcontiene;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblproducto;
    private javax.swing.JLabel lblproveedor;
    private javax.swing.JLabel lblsubcategoria;
    private org.edisoncor.gui.label.LabelMetric lbltitulo;
    private javax.swing.JLabel lblventa;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField txtbodega;
    private javax.swing.JTextField txtcantidadi;
    private javax.swing.JTextField txtcantidadma;
    private javax.swing.JTextField txtcantidadmi;
    public static javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcontiene;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtproveedor;
    private javax.swing.JTextField txtsubcategoria;
    private javax.swing.JTextField txtunidadc;
    private javax.swing.JTextField txtunidadv;
    // End of variables declaration//GEN-END:variables
}
