/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import clases.controlformularios;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.imagenes;
import proyecto_integrador.panel;
import proyecto_integrador.validaciones;
import static ubicaciones.modielipro.cbpais;

/**
 *
 * @author usuario
 */
public class nuevasca extends javax.swing.JFrame {

    public static int bcategoria;
    private conexion conec = new conexion();
    private int i = 0, actual, index;
    private String categoria, codigo, subcategoria;
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form nuevasca
     */
    public nuevasca() {
        initComponents();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
     
    }

    public String sucategoriaget() {
        return categoria;
    }

    public String categoriaget() {
        return subcategoria;
    }

  

    private void limpiar() {
        tabladatos.setModel(modelo);
        txtbusqueda.setText("");
        txtsubcategoriam.setText("");
        txtsubcategoriae.setText("");
        txtsubcategorian.setText("");
        txtcategorian.setText("");
        txtcategoriam.setText("");
        txtcategoriae.setText("");
        btnseleccionar.setEnabled(false);
        rdradios.clearSelection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdradios = new javax.swing.ButtonGroup();
        panel3 = new org.edisoncor.gui.panel.Panel();
        lbltitulo1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel1 = new javax.swing.JLabel();
        tablaopciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblcategorian = new javax.swing.JLabel();
        txtsubcategorian = new javax.swing.JTextField();
        btnaceptarn = new javax.swing.JButton();
        lblbcategorian = new javax.swing.JLabel();
        txtcategorian = new javax.swing.JTextField();
        btnbcategorian = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblcategoriam = new javax.swing.JLabel();
        txtsubcategoriam = new javax.swing.JTextField();
        btnaceptarm = new javax.swing.JButton();
        lblbcategoriam = new javax.swing.JLabel();
        txtcategoriam = new javax.swing.JTextField();
        btnbcategoriam = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblcategoriae = new javax.swing.JLabel();
        txtsubcategoriae = new javax.swing.JTextField();
        btnaceptare = new javax.swing.JButton();
        lblbcategoriae = new javax.swing.JLabel();
        txtcategoriae = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        btnseleccionar = new javax.swing.JButton();
        lblbuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        txtbusqueda = new javax.swing.JTextField();
        rdsubcategoria = new javax.swing.JRadioButton();
        rdcategoria = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        lbltitulo1.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo1.setText("SUBCATÉGORIAS");
        lbltitulo1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lbltitulo1.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        tablaopciones.setBorder(new javax.swing.border.MatteBorder(null));
        tablaopciones.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tablaopciones.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tablaopciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tablaopcionesStateChanged(evt);
            }
        });

        lblcategorian.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcategorian.setText("Nombre SubCategoria");

        txtsubcategorian.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtsubcategorian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubcategorianActionPerformed(evt);
            }
        });
        txtsubcategorian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsubcategorianKeyTyped(evt);
            }
        });

        btnaceptarn.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptarn.setText("Aceptar");
        btnaceptarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarnActionPerformed(evt);
            }
        });

        lblbcategorian.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbcategorian.setText("Eliga Categoria");

        txtcategorian.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcategorian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcategorianKeyTyped(evt);
            }
        });

        btnbcategorian.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbcategorian.setText("...");
        btnbcategorian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbcategorianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnaceptarn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcategorian)
                            .addComponent(lblbcategorian))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsubcategorian, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcategorian, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbcategorian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbcategorian)
                    .addComponent(txtcategorian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbcategorian))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubcategorian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcategorian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaceptarn)
                .addGap(10, 10, 10))
        );

        tablaopciones.addTab("Nuevo", jPanel1);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        lblcategoriam.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcategoriam.setText("Nombre categoria");

        txtsubcategoriam.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtsubcategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubcategoriamActionPerformed(evt);
            }
        });

        btnaceptarm.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptarm.setText("Aceptar");
        btnaceptarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarmActionPerformed(evt);
            }
        });

        lblbcategoriam.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbcategoriam.setText("Eliga Categoria");

        txtcategoriam.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        btnbcategoriam.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbcategoriam.setText("...");
        btnbcategoriam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbcategoriamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnaceptarm))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblcategoriam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblbcategoriam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtcategoriam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbcategoriam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtsubcategoriam, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblbcategoriam)
                            .addComponent(txtcategoriam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbcategoriam))
                        .addGap(18, 18, 18)
                        .addComponent(txtsubcategoriam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcategoriam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaceptarm)
                .addGap(17, 17, 17))
        );

        tablaopciones.addTab("Modificar", jPanel2);

        lblcategoriae.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcategoriae.setText("Nombre categoria");

        txtsubcategoriae.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtsubcategoriae.setToolTipText("Ingresa la Informacion Aqui ");

        btnaceptare.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptare.setText("Aceptar");
        btnaceptare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptareActionPerformed(evt);
            }
        });

        lblbcategoriae.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbcategoriae.setText("Eliga Categoria");

        txtcategoriae.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcategoriae.setToolTipText("Ingresa la Informacion Aqui ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblbcategoriae)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnaceptare)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblcategoriae)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtcategoriae)
                                .addComponent(txtsubcategoriae, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addGap(18, 18, 18))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbcategoriae)
                    .addComponent(txtcategoriae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcategoriae, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubcategoriae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaceptare)
                .addContainerGap())
        );

        tablaopciones.addTab("Eliminar", jPanel3);

        panel1.setBorder(new javax.swing.border.MatteBorder(null));

        btnseleccionar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        lblbuscar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbuscar.setText("Buscar por:");

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        tabladatos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabladatosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        txtbusqueda.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtbusqueda.setToolTipText("Ingresa la Informacion Aqui ");
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtbusquedaHierarchyChanged(evt);
            }
        });
        txtbusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbusquedaInputMethodTextChanged(evt);
            }
        });

        rdradios.add(rdsubcategoria);
        rdsubcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdsubcategoria.setText("Subcategoria");

        rdradios.add(rdcategoria);
        rdcategoria.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdcategoria.setText("Categoria");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(lblbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(rdsubcategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdcategoria))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnseleccionar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbuscar)
                    .addComponent(rdsubcategoria)
                    .addComponent(rdcategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseleccionar)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tablaopciones))
                        .addGap(83, 83, 83))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubcategorianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubcategorianActionPerformed
        // 
    }//GEN-LAST:event_txtsubcategorianActionPerformed

    private void btnaceptarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarnActionPerformed
        if (txtsubcategorian.getText().length() > 0) {
            conec.conectar();
            String consulta = "select * from categorias where categorias.nombre_categoria like'%" + txtbusqueda.getText() + "%'";
            int indice = conec.consultac1get(consulta, "cod_categoria");
            consulta = "INSERT INTO `alexanderflower`.`subcategoria` (`nombre_subcategoria`, `cod_categoria`, `estado_subcategoria`) VALUES ('" + txtsubcategorian.getText() + "', " + indice + ", 1);";
            conec.consultaset(consulta);
            txtsubcategorian.setText("");
            txtsubcategorian.requestFocus();
            conec.desconectar();
        }
    }//GEN-LAST:event_btnaceptarnActionPerformed

    private void btnaceptarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarmActionPerformed
        if (txtsubcategoriam.getText().length() > 0) {
            conec.conectar();
            int cate = conec.consultac1get("select * from categorias where nombre_categoria='" + txtcategoriam.getText() + "'", "cod_categoria");
            String Consulta = "UPDATE `alexanderflower`.`subcategoria` SET `nombre_subcategoria`='" + txtsubcategoriam.getText() + "', `cod_categoria`=" + cate + " WHERE `cod_subcategoria`='" + codigo + "';";
            conec.consultaset(Consulta);
            conec.desconectar();
            tablaopciones.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnaceptarmActionPerformed

    private void tablaopcionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tablaopcionesStateChanged
        if (tablaopciones.getSelectedIndex() == 0) {

            if (nuevopro.ca == 0 && nuevasca.bcategoria == 0 && modielipro.ca == 0) {
                txtcategorian.setEnabled(false);
                i = 0;
                limpiar();
            } else {
                btnseleccionar.setEnabled(true);
            }

        }
        if (tablaopciones.getSelectedIndex() == 1) {
            i = 1;
            categoria = "";
            txtsubcategoriam.setEnabled(false);
            txtcategoriam.setEnabled(false);
            limpiar();
        }
        if (tablaopciones.getSelectedIndex() == 2) {
            i = 1;
            categoria = "";
            limpiar();
            txtsubcategoriae.setEnabled(false);
            txtcategoriae.setEnabled(false);
        }
    }//GEN-LAST:event_tablaopcionesStateChanged

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void tabladatosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabladatosAncestorAdded

    }//GEN-LAST:event_tabladatosAncestorAdded

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        index = tabladatos.getSelectedRow();
        categoria = tabladatos.getValueAt(index, 1).toString();
        codigo = tabladatos.getValueAt(index, 0).toString();
        subcategoria = tabladatos.getValueAt(index, 2).toString();
        if (tablaopciones.getSelectedIndex() == 1) {
            if (subcategoria != null) {
                txtsubcategoriam.setText(categoria);
                txtcategoriam.setText(subcategoria);
                txtsubcategoriam.setEnabled(true);

            }
        } else if (tablaopciones.getSelectedIndex() == 2) {
            if (subcategoria != null) {
                txtsubcategoriae.setText(categoria);
                txtcategoriae.setText(subcategoria);
            }
        }
    }//GEN-LAST:event_tabladatosMouseClicked

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        conec.conectar();
        final String[] columnas = {"Código", "SubCategoria", "Categoria"};
        String consulta = "";
        if (rdsubcategoria.isSelected()) {
            consulta = "select cod_subcategoria,nombre_subcategoria,nombre_categoria from categorias,subcategoria where categorias.cod_categoria=subcategoria.cod_categoria and estado_subcategoria=1 and subcategoria.nombre_subcategoria like '%" + txtbusqueda.getText() + "%'";
        }
        if (rdcategoria.isSelected()) {
            consulta = "select * from categorias where categorias.nombre_categoria like'%" + txtbusqueda.getText() + "%'";
            int indice = conec.consultac1get(consulta, "cod_categoria");
            consulta = "select cod_subcategoria,nombre_subcategoria,nombre_categoria from categorias,subcategoria where categorias.cod_categoria=subcategoria.cod_categoria and estado_subcategoria=1 and subcategoria.cod_categoria like '%" + indice + "%'";
        }
        tabladatos.setModel(conec.consultaget(consulta, columnas));
        conec.desconectar();
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtbusquedaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtbusquedaHierarchyChanged

    }//GEN-LAST:event_txtbusquedaHierarchyChanged

    private void txtbusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbusquedaInputMethodTextChanged

    }//GEN-LAST:event_txtbusquedaInputMethodTextChanged

    private void txtsubcategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubcategoriamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubcategoriamActionPerformed

    private void btnbcategorianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbcategorianActionPerformed
        categoriasb();
        txtcategorian.setText(nu.categoriaget());
    }//GEN-LAST:event_btnbcategorianActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened
   
    private void btnbcategoriamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbcategoriamActionPerformed
        categoriasb();
        txtcategoriam.setText(nu.categoriaget());
    }//GEN-LAST:event_btnbcategoriamActionPerformed

    private void btnaceptareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptareActionPerformed
        if (txtsubcategoriae.getText().length() > 0) {
            conec.conectar();
            String Consulta = "UPDATE `alexanderflower`.`subcategoria` SET `estado_subcategoria`=0 WHERE `cod_subcategoria`='" + codigo + "';";
            conec.consultaset(Consulta);
            conec.desconectar();
            tablaopciones.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnaceptareActionPerformed
    private validaciones validar = new validaciones();
    private void txtcategorianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcategorianKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtcategorianKeyTyped

    private void txtsubcategorianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsubcategorianKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtsubcategorianKeyTyped
    private void categoriasb() {
        bcategoria = 1;
        nu = new nuevaca();
        bcategoria = 0;
        panel.jd = new JDialog(nu, true);
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);

    }
    private nuevaca nu = new nuevaca();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevasca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevasca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevasca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevasca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevasca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptare;
    private javax.swing.JButton btnaceptarm;
    private javax.swing.JButton btnaceptarn;
    private javax.swing.JButton btnbcategoriam;
    private javax.swing.JButton btnbcategorian;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblbcategoriae;
    private javax.swing.JLabel lblbcategoriam;
    private javax.swing.JLabel lblbcategorian;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JLabel lblcategoriae;
    private javax.swing.JLabel lblcategoriam;
    private javax.swing.JLabel lblcategorian;
    private org.edisoncor.gui.label.LabelMetric lbltitulo1;
    private javax.swing.JPanel panel1;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JRadioButton rdcategoria;
    private javax.swing.ButtonGroup rdradios;
    private javax.swing.JRadioButton rdsubcategoria;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTabbedPane tablaopciones;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcategoriae;
    private javax.swing.JTextField txtcategoriam;
    private javax.swing.JTextField txtcategorian;
    private javax.swing.JTextField txtsubcategoriae;
    private javax.swing.JTextField txtsubcategoriam;
    private javax.swing.JTextField txtsubcategorian;
    // End of variables declaration//GEN-END:variables
}
