/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_integrador;

import clases.Reloj;
import clases.controlformularios;
import clases.oayuda;
import clientes.clientesprov;
import contabilidad.librodiario;
import cuentas_cobrar.cuentasxcobrar;
import cuentas_pagar.cuentasxpagar;
import cuentascorrientes.cuentasg;
import cuentascorrientes.listacuentas;
import facturacion.facturacion;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import parametros.panelparametros;
import productos.panelinventario;
import roles.roldepagos;
import usuarios.ingreso;

/**
 *
 * @author LAB4-08
 */
public class panel extends javax.swing.JFrame {

    private static conexion conec = new conexion();
    ingreso ing = new ingreso();
    private static final String consulta = "select * from empresa;";
    private static Graphics g;
    public static JDialog jd = new JDialog();
    public static String ini;
    String in;

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        lblusuario.setText(ingreso.userget());
        controlformularios cen = new controlformularios();

        this.setLocationRelativeTo(null);
        jd.setLocationRelativeTo(null);
    }
    private static String cierre = "";

    public static void obcierre() {

        conec.conectar();
        cierre = conec.consultac2get("select * from parametros", "hora_cierre");
        conec.desconectar();
    }

    public static void grabar() {
        obcierre();
        Calendar calendario = new GregorianCalendar();
        int hora = calendario.get(Calendar.HOUR_OF_DAY);
        int minutos = calendario.get(Calendar.MINUTE);
        int segundos = calendario.get(Calendar.SECOND);
        String ho = "", mi = "", se = "";
        if (segundos == 0) {
            se = "00";
        } else if (segundos == 1) {
            se = "01";
        } else if (segundos == 2) {
            se = "02";
        } else if (segundos == 3) {
            se = "03";
        } else if (segundos == 4) {
            se = "04";
        } else if (segundos == 5) {
            se = "05";
        } else if (segundos == 6) {
            se = "06";
        } else if (segundos == 7) {
            se = "07";
        } else if (segundos == 8) {
            se = "08";
        } else if (segundos == 9) {
            se = "09";
        } else {
            se = "" + segundos;
        }
        if (minutos == 0) {
            mi = "00";
        } else if (minutos == 1) {
            mi = "01";
        } else if (minutos == 2) {
            mi = "02";
        } else if (minutos == 3) {
            mi = "03";
        } else if (minutos == 4) {
            mi = "04";
        } else if (minutos == 5) {
            mi = "05";
        } else if (minutos == 6) {
            mi = "06";
        } else if (minutos == 7) {
            mi = "07";
        } else if (minutos == 8) {
            mi = "08";
        } else if (minutos == 9) {
            mi = "09";
        } else {
            mi = "" + minutos;
        }
        if (hora == 0) {
            ho = "00";
        } else if (hora == 1) {
            ho = "01";
        } else if (hora == 2) {
            ho = "02";
        } else if (hora == 3) {
            ho = "03";
        } else if (hora == 4) {
            ho = "04";
        } else if (hora == 5) {
            ho = "05";
        } else if (hora == 6) {
            ho = "06";
        } else if (hora == 7) {
            ho = "07";
        } else if (hora == 8) {
            ho = "08";
        } else if (hora == 9) {
            ho = "09";
        } else {
            ho = "" + hora;
        }
        String actual = "" + ho + ":" + mi + ":" + se;
        if (actual.equals(cierre)) {
            librodiario finali = new librodiario();
            finali.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel = new org.edisoncor.gui.panel.Panel();
        jButton1 = new javax.swing.JButton();
        btncuentaxcobrar = new javax.swing.JButton();
        btnclientes = new javax.swing.JButton();
        btnparametros = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btninventario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        btnayuda = new javax.swing.JButton();

        setTitle("MODULOS");
        setPreferredSize(new java.awt.Dimension(1250, 710));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        btnsalir.setText("x");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/OSEA.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        panel.setColorPrimario(new java.awt.Color(255, 204, 153));
        panel.setColorSecundario(new java.awt.Color(204, 204, 255));

        jButton1.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/Facturacion.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        btncuentaxcobrar.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        btncuentaxcobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/cuentas por cobrar.jpg"))); // NOI18N
        btncuentaxcobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuentaxcobrarActionPerformed(evt);
            }
        });

        btnclientes.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/clientes y proveedores.jpg"))); // NOI18N
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });

        btnparametros.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        btnparametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/parametros.jpg"))); // NOI18N
        btnparametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparametrosActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/cuentas por pagas.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/cuentas corrientes.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btninventario.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        btninventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/inventario.jpg"))); // NOI18N
        btninventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventarioActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Orator Std", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/CONTABILIDAD.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnparametros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncuentaxcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnclientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninventario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(543, 543, 543))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncuentaxcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnparametros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("USUARIO ACTIVO: ");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220)
                                .addComponent(jLabel1)))
                        .addGap(0, 171, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(btnsalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsalir)
                                .addComponent(jLabel2))
                            .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(btnayuda))
                .addGap(42, 42, 42)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("panel");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private controlformularios cen = new controlformularios();
    private static Reloj tiempos = new Reloj();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conec.conectar();
        tiempos.tiempo();
        cierre = conec.consultac2get("select * from parametros", "hora_cierre");
        conec.desconectar();
        dimension nuevo = new dimension();
        this.setBounds(0, 0, nuevo.dimension().width, nuevo.dimension().height);
        panel.setBounds(cen.pxget(this.getWidth(), panel.getWidth()), cen.pyget(this.getHeight(), panel.getHeight()), panel.getWidth(), panel.getHeight());
        imagenes p = new imagenes("/proyecto_integrador/imagenes/336324-sepik.jpg");
        this.add(p);
        this.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void btnparametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparametrosActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "parametros");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            panelparametros nu = new panelparametros();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }

    }//GEN-LAST:event_btnparametrosActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "clipro");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            clientesprov nuevo = new clientesprov();
            dialogo jd = new dialogo(nuevo, true);
            jd.setContentPane(nuevo.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }

    }//GEN-LAST:event_btnclientesActionPerformed

    private void btninventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarioActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "iventarios");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            panelinventario inventario = new panelinventario();
            dialogo jd = new dialogo(inventario, true);
            jd.setContentPane(inventario.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }

    }//GEN-LAST:event_btninventarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "facturacion");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            facturacion compra = new facturacion();
            dialogo jd = new dialogo(compra, true);
            jd.setContentPane(compra.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btncuentaxcobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuentaxcobrarActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "cuentasxcobrar");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            cuentasxcobrar cobrar = new cuentasxcobrar();
            dialogo jd = new dialogo(cobrar, true);
            jd.setContentPane(cobrar.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }

    }//GEN-LAST:event_btncuentaxcobrarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "cuentasxpagar");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            cuentasxpagar pagar = new cuentasxpagar();
            dialogo jd = new dialogo(pagar, true);
            jd.setContentPane(pagar.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "contabilidad");
        System.out.println("" + in + "   " + ini);
        conec.desconectar();
        if ("true".equals(in)) {
            roldepagos pagar = new roldepagos();
            dialogo jd = new dialogo(pagar, true);
            jd.setContentPane(pagar.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        conec.conectar();
        in = conec.consultac2get("select * from privilegios where nombre_usuario='" + conec.loginget() + "'", "contabilidad");

        if ("true".equals(in)) {
            if (conec.consultac1get("select count(*) from cuentascorr where estado_cuenta=1", "count(*)") > 0) {
                listacuentas lnu = new listacuentas();
                lnu.setVisible(true);
            } else {
                cuentasg pagar = new cuentasg();
                dialogo jd = new dialogo(pagar, true);
                jd.setContentPane(pagar.getContentPane());
                jd.pack();
                jd.setLocationRelativeTo(null);
                jd.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Acceso denegado");
        }
        conec.desconectar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed

    }//GEN-LAST:event_jLabel1KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnclientes;
    private javax.swing.JButton btncuentaxcobrar;
    private javax.swing.JButton btninventario;
    private javax.swing.JButton btnparametros;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblusuario;
    private org.edisoncor.gui.panel.Panel panel;
    // End of variables declaration//GEN-END:variables
}
