/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anticipos;

import clases.controlformularios;
import clases.oayuda;
import clientes.buscare;
import clientes.buscarp;
import clientes.clientesprov;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author USUARIO
 */
public class anticipo1 extends javax.swing.JFrame {

    /**
     * Creates new form anticipo1
     */
    public anticipo1() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel6 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        lbltitulo1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcfecha = new com.toedter.calendar.JDateChooser();
        txtempleado = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtconcepto = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnbuscar1 = new javax.swing.JButton();
        btnayuda1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel6.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel6.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel6MouseMoved(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        lbltitulo1.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo1.setText("ANTICIPOS");
        lbltitulo1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lbltitulo1.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel2.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("CI Empleado");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Valor del anticipo");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("Concepto");

        dcfecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcfechaFocusGained(evt);
            }
        });
        dcfecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcfechaMouseClicked(evt);
            }
        });
        dcfecha.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                dcfechaVetoableChange(evt);
            }
        });

        txtempleado.setEnabled(false);

        txtvalor.setText("0");
        txtvalor.setToolTipText("Ingrese el monto del anticipo ");
        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });

        txtconcepto.setToolTipText("Detalle el motivo del anticipo ");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setText("Elimnar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnbuscar1.setText("Buscar");
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        btnayuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayuda1MouseClicked(evt);
            }
        });
        btnayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayuda1ActionPerformed(evt);
            }
        });
        btnayuda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayuda1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                        .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24)
                .addComponent(btnayuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtempleado)
                    .addComponent(txtvalor)
                    .addComponent(txtconcepto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(btnbuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnbuscar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98))))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnayuda1))
                .addGap(65, 65, 65)
                .addComponent(lbltitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtempleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(28, 28, 28)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtconcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar)))
                .addGap(18, 18, 18)
                .addComponent(btnsalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private final Date fecha = new Date();
    private final conexion conec = new conexion();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    private void cargar() {
        
        dcfecha.setDate(fecha);
    }
    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        
        if (txtempleado.getText().length() > 0 && txtvalor.getText().length() > 0) {
            conec.conectar();
            int año = dcfecha.getCalendar().get(Calendar.YEAR);
            int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
            int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            conec.consultaset("INSERT INTO `alexanderflower`.`anticipos` (`fecha_anticipo`, `cod_empleado`, `valor_anticipo`, `concepto_anticipo`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + txtempleado.getText() + "', '" + txtvalor.getText() + "', '" + txtconcepto.getText() + "');");
            String codigoa = conec.consultac2get("select t.transmanu from transacciones t where transmanu is not null order by transmanu desc limit 1", "transmanu");
            if ("".equals(codigoa)) {
                codigoa = "0";
            }
            int codigom = Integer.parseInt(codigoa);
            codigom++;
            conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `debe`, `reciboco`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='BANCOS'", "cod_subcuenta2") + "', 'BANCOS', '" + txtvalor.getText() + "', '" + codigom + "');");
            conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `reciboco`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='ANTICIPOS QUINCENA'", "cod_subcuenta2") + "', 'ANTICIPOS QUINCENA', " + txtvalor.getText() + ", '" + codigom + "');");
            conec.desconectar();
            txtempleado.setText("");
            txtvalor.setText("");
            txtconcepto.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos lo campos");
        }
    }//GEN-LAST:event_btnnuevoActionPerformed
    controlformularios cen = new controlformularios();
    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        clientesprov.verme = 100;
        buscare proveedor = new buscare();
        dialogo jd = new dialogo(proveedor, true);
        jd.setContentPane(proveedor.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtempleado.setText(buscare.cedula);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        if (txtempleado.getText().length() > 0 && txtvalor.getText().length() > 0) {
            conec.conectar();
            int año = dcfecha.getCalendar().get(Calendar.YEAR);
            int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
            int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
            conec.consultaset("UPDATE `alexanderflower`.`anticipos` SET `fecha_anticipo`='" + año + "-" + mes + "-" + dia + "', `valor_anticipo`='" + txtvalor.getText() + "', `concepto_anticipo`='" + txtconcepto.getText() + "' WHERE `cod_anticipo`='" + cod + "';");
            conec.desconectar();
            txtempleado.setText("");
            txtvalor.setText("");
            txtconcepto.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Llene todos lo campos");
        }
    }//GEN-LAST:event_btnactualizarActionPerformed
    private String cod;
    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        conec.conectar();
        clientesprov.verme = 100;
        buscare proveedor = new buscare();
        dialogo jd = new dialogo(proveedor, true);
        jd.setContentPane(proveedor.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        String cedula = buscare.cedula;
        cod = conec.consultac2get("select a.cod_anticipo,a.fecha_anticipo,a.cod_empleado,a.valor_anticipo,a.concepto_anticipo from anticipos a where cod_empleado='" + cedula + "' order by a.fecha_anticipo desc limit 1", "a.cod_anticipo");
        
        txtempleado.setText(conec.consultac2get("select a.cod_anticipo,a.fecha_anticipo,a.cod_empleado,a.valor_anticipo,a.concepto_anticipo from anticipos a where cod_empleado='" + cedula + "' order by a.fecha_anticipo desc limit 1", "a.cod_empleado"));
        txtvalor.setText(conec.consultac2get("select a.cod_anticipo,a.fecha_anticipo,a.cod_empleado,a.valor_anticipo,a.concepto_anticipo from anticipos a where cod_empleado='" + cedula + "' order by a.fecha_anticipo desc limit 1", "a.valor_anticipo"));
        txtconcepto.setText(conec.consultac2get("select a.cod_anticipo,a.fecha_anticipo,a.cod_empleado,a.valor_anticipo,a.concepto_anticipo from anticipos a where cod_empleado='" + cedula + "' order by a.fecha_anticipo  desc limit 1", "concepto_anticipo"));
        conec.desconectar();
        if ("".equals(txtempleado.getText())) {
            JOptionPane.showMessageDialog(this, "No Existe registros");
        }
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (txtempleado.getText().length() > 0) {
            conec.conectar();
            conec.consultaset("DELETE FROM `alexanderflower`.`anticipos` WHERE `cod_anticipo`='" + cod + "';");
            conec.desconectar();
            txtempleado.setText("");
            txtvalor.setText("");
            txtconcepto.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al borrar");
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(true);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void dcfechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcfechaFocusGained

    }//GEN-LAST:event_dcfechaFocusGained

    private void dcfechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcfechaMouseClicked
        System.out.println("sas");
    }//GEN-LAST:event_dcfechaMouseClicked

    private void dcfechaVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_dcfechaVetoableChange

    }//GEN-LAST:event_dcfechaVetoableChange

    private void panel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel6MouseMoved
        if (dcfecha.getDate().before(cen.fechasmas(fecha, 30)) || dcfecha.getDate().before(fecha)) {
            
        } else {
            dcfecha.setDate(fecha);
            JOptionPane.showMessageDialog(this, "Fecha Erronea");
        }
        if (dcfecha.getDate().after(cen.fechasmas(fecha, -30))) {
            
        } else {
            dcfecha.setDate(fecha);
            JOptionPane.showMessageDialog(this, "Fecha Erronea");
        }
    }//GEN-LAST:event_panel6MouseMoved

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        conec.conectar();
        double sueldo = Double.parseDouble(conec.consultac2get("select * from empleados where cedula_empleado='" + txtempleado.getText() + "'", "sueldo_empleado"));
        if (sueldo < Double.parseDouble(txtvalor.getText())) {
            JOptionPane.showMessageDialog(this, "El anticipo debe ser menor \n al el sueldo del empleado");
            txtvalor.setText("0");
        }
        conec.desconectar();
    }//GEN-LAST:event_txtvalorActionPerformed

    private void btnayuda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayuda1MouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayuda1MouseClicked

    private void btnayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayuda1ActionPerformed

    }//GEN-LAST:event_btnayuda1ActionPerformed

    private void btnayuda1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayuda1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayuda1KeyPressed
    oayuda ay = new oayuda();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anticipo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anticipo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anticipo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anticipo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anticipo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnayuda1;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private org.edisoncor.gui.label.LabelMetric lbltitulo1;
    private org.edisoncor.gui.panel.Panel panel6;
    private javax.swing.JTextField txtconcepto;
    private javax.swing.JTextField txtempleado;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
