/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plandecuentas;

import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import javax.swing.tree.TreePath;
import productos.nuevabo;
import proyecto_integrador.conexion;
import proyecto_integrador.panel;

/**
 *
 * @author Cristian
 */
public class plancuentas extends javax.swing.JFrame {

    conexion db = new conexion();

    /**
     * Creates new form plancuentas
     */
    public plancuentas() {
        initComponents();
        mostrar();
    
    }

    public void abrir(JTree tree) {
        int row = 0;
        while (row < tree.getRowCount()) {
            tree.expandRow(row);
            row++;
        }
    }

   public void cerrar(JTree tree) {
    int row = tree.getRowCount() - 1;
    while (row >= 0) {
      tree.collapseRow(row);
      row--;
      }
    }
 

    private void mostrar() {
        db.conectar();
        DefaultMutableTreeNode niv1 = new DefaultMutableTreeNode("Plan de Cuentas");
        DefaultMutableTreeNode niv2;
        DefaultMutableTreeNode niv3;
        DefaultMutableTreeNode niv4;
        DefaultMutableTreeNode niv5;
        DefaultMutableTreeNode niv6;

        Object[][] data_niv1 = db.select("cuentas", " cod_cuenta, nombre_cuenta ", "estado_cuenta=1");
        if (data_niv1.length > 0) {
            for (int i = 0; i < data_niv1.length; i++) {

                niv2 = new DefaultMutableTreeNode(data_niv1[i][1]);
                niv1.add(niv2);

                Object[][] data_niv2 = db.select("subcuentas", "cod_subcuenta,nombre_subcuenta", " cod_cuenta='" + data_niv1[i][0].toString() + "' and estado_subcuenta=1");

                if (data_niv2.length > 0) {
                    for (int j = 0; j < data_niv2.length; j++) {
                        niv3 = new DefaultMutableTreeNode(data_niv2[j][1]);
                        niv2.add(niv3);

                        Object[][] data_niv3 = db.select("subcuenta1", "cod_subcuenta1,nombre_subcuenta1", " cod_subcuenta='" + data_niv2[j][0].toString() + "' and estado_subcuenta1=1");

                        if (data_niv3.length > 0) {
                            for (int k = 0; k < data_niv3.length; k++) {
                                niv4 = new DefaultMutableTreeNode(data_niv3[k][1]);
                                niv3.add(niv4);
                                Object[][] data_niv4 = db.select("subcuenta2", "cod_subcuenta2,nombre_subcuenta2", " cod_subcuenta1='" + data_niv3[k][0].toString() + "' and estado_subcuenta2=1");

                                if (data_niv4.length > 0) {
                                    for (int l = 0; l < data_niv4.length; l++) {
                                        niv5 = new DefaultMutableTreeNode(data_niv4[l][1]);
                                        niv4.add(niv5);
                                        Object[][] data_niv5 = db.select("subcuenta3", "cod_subcuenta3,nombre_subcuenta3", " cod_subcuenta2='" + data_niv4[l][0].toString() + "' and estado_subcuenta3=1");

                                        if (data_niv5.length > 0) {
                                            for (int m = 0; m < data_niv5.length; m++) {
                                                niv6 = new DefaultMutableTreeNode(data_niv5[m][1]);
                                                niv5.add(niv6);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        DefaultTreeModel modelo = new DefaultTreeModel(niv1);
        this.arbol.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        btnniv1 = new javax.swing.JButton();
        lblniv1 = new javax.swing.JLabel();
        lblniv2 = new javax.swing.JLabel();
        lblniv3 = new javax.swing.JLabel();
        lblniv4 = new javax.swing.JLabel();
        lblniv5 = new javax.swing.JLabel();
        cbniv1 = new javax.swing.JComboBox();
        cbniv2 = new javax.swing.JComboBox();
        cbniv3 = new javax.swing.JComboBox();
        cbniv4 = new javax.swing.JComboBox();
        cbniv5 = new javax.swing.JComboBox();
        btnniv2 = new javax.swing.JButton();
        btnniv3 = new javax.swing.JButton();
        btnniv4 = new javax.swing.JButton();
        btnniv5 = new javax.swing.JButton();
        btnseleccionar = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(400);

        arbol.setBackground(new java.awt.Color(204, 204, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        jSplitPane1.setLeftComponent(jScrollPane1);

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        labelMetric7.setForeground(new java.awt.Color(51, 51, 255));
        labelMetric7.setText("PLAN DE CUENTAS");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        btnniv1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnniv1.setText("Buscar <> Nuevo");
        btnniv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnniv1ActionPerformed(evt);
            }
        });

        lblniv1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblniv1.setText("Cuentas Niv.1");

        lblniv2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblniv2.setText("Cuentas Niv.2");

        lblniv3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblniv3.setText("Cuentas Niv.3");

        lblniv4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblniv4.setText("Cuentas Niv.4");

        lblniv5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblniv5.setText("Cuentas Niv.5");

        cbniv1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbniv1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbniv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbniv1ActionPerformed(evt);
            }
        });

        cbniv2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbniv2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbniv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbniv2ActionPerformed(evt);
            }
        });

        cbniv3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbniv3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbniv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbniv3ActionPerformed(evt);
            }
        });

        cbniv4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbniv4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbniv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbniv4ActionPerformed(evt);
            }
        });

        cbniv5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbniv5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnniv2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnniv2.setText("Buscar <> Nuevo");
        btnniv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnniv2ActionPerformed(evt);
            }
        });

        btnniv3.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnniv3.setText("Buscar <> Nuevo");
        btnniv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnniv3ActionPerformed(evt);
            }
        });

        btnniv4.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnniv4.setText("Buscar <> Nuevo");
        btnniv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnniv4ActionPerformed(evt);
            }
        });

        btnniv5.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnniv5.setText("Buscar <> Nuevo");
        btnniv5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnniv5ActionPerformed(evt);
            }
        });

        btnseleccionar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnseleccionar.setText("Seleccionar");

        btnimprimir.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnimprimir.setText("Imprimir Plan");

        btnsalir.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(btnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(btnimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(lblniv3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbniv4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnniv5))
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(lblniv4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbniv3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnniv4))
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(lblniv5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbniv5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnniv3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel3Layout.createSequentialGroup()
                                            .addComponent(lblniv1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbniv1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                            .addComponent(lblniv2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbniv2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(33, 33, 33)
                                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnniv2)
                                        .addComponent(btnniv1))))))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblniv1)
                    .addComponent(cbniv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnniv1))
                .addGap(27, 27, 27)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblniv2)
                    .addComponent(cbniv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnniv2))
                .addGap(27, 27, 27)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblniv3)
                    .addComponent(cbniv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnniv5))
                .addGap(27, 27, 27)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblniv4)
                    .addComponent(cbniv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnniv4))
                .addGap(24, 24, 24)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblniv5)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbniv5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnniv3)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnimprimir)
                    .addComponent(btnseleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(panel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseClicked
    }//GEN-LAST:event_arbolMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        db.conectar();
        cbniv1.setModel(db.consultacget("Select * from cuentas where estado_cuenta=1", "nombre_cuenta"));
        db.desconectar();
    }//GEN-LAST:event_formWindowOpened

    private void cbniv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbniv1ActionPerformed
        try {
            cbniv2.removeAllItems();
            cbniv3.removeAllItems();
            cbniv4.removeAllItems();
            cbniv5.removeAllItems();
            db.conectar();
            String codigo = db.consultac2get("select * from cuentas where nombre_cuenta='" + cbniv1.getSelectedItem().toString() + "'", "cod_cuenta");
            cbniv2.setModel(db.consultacget("Select * from subcuentas where estado_subcuenta=1 and cod_cuenta='" + codigo + "'", "nombre_subcuenta"));
            db.desconectar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_cbniv1ActionPerformed

    private void cbniv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbniv4ActionPerformed
        try {
            cbniv3.removeAllItems();
            cbniv5.removeAllItems();
            db.conectar();
            String codigo = db.consultac2get("select * from subcuenta1 where nombre_subcuenta1='" + cbniv4.getSelectedItem().toString() + "'", "cod_subcuenta1");
            System.out.println("" + codigo);
            cbniv3.setModel(db.consultacget("Select * from subcuenta2 where estado_subcuenta2=1 and cod_subcuenta1='" + codigo + "'", "nombre_subcuenta2"));
            db.desconectar();
        } catch (java.lang.NullPointerException ex) {
        }

    }//GEN-LAST:event_cbniv4ActionPerformed

    private void cbniv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbniv2ActionPerformed
        try {
            cbniv3.removeAllItems();
            cbniv4.removeAllItems();
            cbniv5.removeAllItems();
            db.conectar();
            String codigo = db.consultac2get("select * from subcuentas where nombre_subcuenta='" + cbniv2.getSelectedItem().toString() + "'", "cod_subcuenta");
            cbniv4.setModel(db.consultacget("Select * from subcuenta1 where estado_subcuenta1=1 and cod_subcuenta='" + codigo + "'", "nombre_subcuenta1"));
            db.desconectar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_cbniv2ActionPerformed

    private void cbniv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbniv3ActionPerformed
        try {
            cbniv5.removeAllItems();
            db.conectar();
            String codigo = db.consultac2get("select * from subcuenta2 where nombre_subcuenta2='" + cbniv3.getSelectedItem().toString() + "'", "cod_subcuenta2");
            System.out.println("" + codigo);
            cbniv5.setModel(db.consultacget("Select * from subcuenta3 where estado_subcuenta3=1 and cod_subcuenta2='" + codigo + "'", "nombre_subcuenta3"));
            db.desconectar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_cbniv3ActionPerformed

    private void btnniv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnniv1ActionPerformed
        try {
            cuentas nu = new cuentas();
            panel.jd = new JDialog(nu, true);
            panel.jd.setContentPane(nu.getContentPane());
            panel.jd.pack();
            panel.jd.setVisible(true);
            cbniv1.setSelectedItem(cuentas.cuenta);
            mostrar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_btnniv1ActionPerformed

    private void btnniv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnniv2ActionPerformed
        try {
            subcuentas nu = new subcuentas();
            panel.jd = new JDialog(nu, true);
            panel.jd.setContentPane(nu.getContentPane());
            panel.jd.pack();
            panel.jd.setVisible(true);
            cbniv2.setSelectedItem(subcuentas.cuenta1);
            mostrar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_btnniv2ActionPerformed

    private void btnniv5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnniv5ActionPerformed
        try {
            subcuentas1 nu = new subcuentas1();
            panel.jd = new JDialog(nu, true);
            panel.jd.setContentPane(nu.getContentPane());
            panel.jd.pack();
            panel.jd.setVisible(true);
            cbniv4.setSelectedItem(subcuentas1.cuenta1);
            mostrar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_btnniv5ActionPerformed

    private void btnniv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnniv4ActionPerformed
        try {
            subcuentas2 nu = new subcuentas2();
            panel.jd = new JDialog(nu, true);
            panel.jd.setContentPane(nu.getContentPane());
            panel.jd.pack();
            panel.jd.setVisible(true);
            cbniv3.setSelectedItem(subcuentas2.cuenta1);
            mostrar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_btnniv4ActionPerformed

    private void btnniv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnniv3ActionPerformed
        try {
            subcuentas3 nu = new subcuentas3();
            panel.jd = new JDialog(nu, true);
            panel.jd.setContentPane(nu.getContentPane());
            panel.jd.pack();
            panel.jd.setVisible(true);
            cbniv5.setSelectedItem(subcuentas3.cuenta1);
            mostrar();
        } catch (java.lang.NullPointerException ex) {
        }
    }//GEN-LAST:event_btnniv3ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cerrar(arbol);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    abrir(arbol);
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plancuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plancuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plancuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plancuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plancuentas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arbol;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnniv1;
    private javax.swing.JButton btnniv2;
    private javax.swing.JButton btnniv3;
    private javax.swing.JButton btnniv4;
    private javax.swing.JButton btnniv5;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JComboBox cbniv1;
    private javax.swing.JComboBox cbniv2;
    private javax.swing.JComboBox cbniv3;
    private javax.swing.JComboBox cbniv4;
    private javax.swing.JComboBox cbniv5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private javax.swing.JLabel lblniv1;
    private javax.swing.JLabel lblniv2;
    private javax.swing.JLabel lblniv3;
    private javax.swing.JLabel lblniv4;
    private javax.swing.JLabel lblniv5;
    private org.edisoncor.gui.panel.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
