/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package usuarios;

import clases.controlformularios;
import javax.swing.table.DefaultTableModel;
import proyecto_integrador.conexion;
import proyecto_integrador.panel;

/**
 *
 * @author USUARIO
 */
public class tipousuario extends javax.swing.JFrame {
   private conexion conec = new conexion();
    private int i = 0, actual, index;
    private String tipousuario, codigo;
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form tipousuario
     */
    public tipousuario() {
        initComponents();
        controlformularios cen=new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
     this.setSize(444, 443);
        actual = this.getSize().height;
    }
private void limpiar() {
        tabladatos.setModel(modelo);
        txtbusqueda.setText("");
        txtaccesom.setText("");
        txtaccesoe.setText("");
        btnseleccionar.setEnabled(false);
    }
    String tipoget() {
        return tipousuario;
    }

    private void dimensiones() {
        if (i == 0) {

            this.setSize(this.getWidth(), (this.getHeight() / 2) + 30);
            panel1.setVisible(false);

        } else if (i == 1) {
            this.setSize(this.getWidth(), actual);
            panel1.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        jLabel1 = new javax.swing.JLabel();
        tablaopciones = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblacesson = new javax.swing.JLabel();
        txtacceson = new javax.swing.JTextField();
        btnaceptarn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblaccesom = new javax.swing.JLabel();
        txtaccesom = new javax.swing.JTextField();
        btnaceptarm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblaccesoe = new javax.swing.JLabel();
        txtaccesoe = new javax.swing.JTextField();
        btnaceptare = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        btnseleccionar = new javax.swing.JButton();
        lblbuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        txtbusqueda = new javax.swing.JTextField();

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        labelMetric7.setForeground(new java.awt.Color(51, 51, 255));
        labelMetric7.setText("Tipos Accesos");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        tablaopciones.setBorder(new javax.swing.border.MatteBorder(null));
        tablaopciones.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tablaopciones.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tablaopciones.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tablaopcionesStateChanged(evt);
            }
        });

        lblacesson.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblacesson.setText("Nombre Categoria");

        txtacceson.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtacceson.setToolTipText("Ingresa la Informacion Aqui ");
        txtacceson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccesonActionPerformed(evt);
            }
        });

        btnaceptarn.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptarn.setText("Aceptar");
        btnaceptarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaceptarn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblacesson)
                        .addGap(18, 18, 18)
                        .addComponent(txtacceson, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblacesson, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtacceson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnaceptarn)
                .addGap(10, 10, 10))
        );

        tablaopciones.addTab("Nuevo", jPanel1);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        lblaccesom.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblaccesom.setText("Nombre categoria");

        txtaccesom.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        btnaceptarm.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptarm.setText("Aceptar");
        btnaceptarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaceptarm)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblaccesom)
                        .addGap(18, 18, 18)
                        .addComponent(txtaccesom, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccesom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaccesom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnaceptarm)
                .addContainerGap())
        );

        tablaopciones.addTab("Modificar", jPanel2);

        lblaccesoe.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblaccesoe.setText("Nombre categoria");

        txtaccesoe.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        btnaceptare.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnaceptare.setText("Aceptar");
        btnaceptare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnaceptare)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblaccesoe)
                        .addGap(18, 18, 18)
                        .addComponent(txtaccesoe, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccesoe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtaccesoe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnaceptare)
                .addContainerGap())
        );

        tablaopciones.addTab("Eliminar", jPanel3);

        panel1.setBorder(new javax.swing.border.MatteBorder(null));

        btnseleccionar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        lblbuscar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbuscar.setText("Buscar por Nombre Acceso");

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        tabladatos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabladatosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        txtbusqueda.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtbusqueda.setToolTipText("Ingresa la Informacion Aqui ");
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtbusquedaHierarchyChanged(evt);
            }
        });
        txtbusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbusquedaInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblbuscar))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnseleccionar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblbuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseleccionar)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tablaopciones, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablaopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaccesonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccesonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccesonActionPerformed

    private void btnaceptarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarnActionPerformed
        if (txtacceson.getText().length() > 0) {
            conec.conectar();
            String Consulta = "INSERT INTO `alexanderflower`.`tipousuario` (`nombre_tipousuario`, `estado_tipousuario`) VALUES ('"+txtacceson.getText()+"', '1');";
            conec.consultaset(Consulta);
            txtacceson.setText("");
            txtacceson.requestFocus();
            conec.desconectar();
        }
    }//GEN-LAST:event_btnaceptarnActionPerformed

    private void btnaceptarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarmActionPerformed
        if (txtaccesom.getText().length() > 0) {
            conec.conectar();
            String Consulta = "UPDATE `alexanderflower`.`tipousuario` SET `nombre_tipousuario`='"+txtaccesom.getText()+"' WHERE `codigo_tipousuario`='"+codigo+"';";
            conec.consultaset(Consulta);
            txtaccesom.setText("");
            txtaccesom.requestFocus();
            conec.desconectar();
            tablaopciones.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnaceptarmActionPerformed

    private void btnaceptareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptareActionPerformed
        if (txtaccesoe.getText().length() > 0) {
            conec.conectar();
            String Consulta = "UPDATE `alexanderflower`.`tipousuario` SET `estado_tipousuario`='0' WHERE `codigo_tipousuario`='"+codigo+"';";
            conec.consultaset(Consulta);
            conec.desconectar();
            tablaopciones.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnaceptareActionPerformed

    private void tablaopcionesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tablaopcionesStateChanged
        if (tablaopciones.getSelectedIndex() == 0) {
            if (nuevou.estado == 0 ) {
                i = 0;
                dimensiones();
                limpiar();
                panel.jd.setSize(this.getWidth(), (actual / 2) + 20);
            }
            else  {
                btnseleccionar.setEnabled(true);
            }

        }
        if (tablaopciones.getSelectedIndex() == 1) {
            i = 1;
            dimensiones();
            tipousuario = "";
            txtaccesom.setEnabled(false);
            limpiar();
            panel.jd.setSize(this.getWidth(), actual);
            panel.jd.repaint();
        }
        if (tablaopciones.getSelectedIndex() == 2) {
            i = 1;
            dimensiones();
            tipousuario = "";
            limpiar();
            panel.jd.setSize(this.getWidth(), actual);
            txtaccesoe.setEnabled(false);
        }
    }//GEN-LAST:event_tablaopcionesStateChanged

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed

        this.setVisible(false);
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void tabladatosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabladatosAncestorAdded

    }//GEN-LAST:event_tabladatosAncestorAdded

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked
        index = tabladatos.getSelectedRow();
        tipousuario = tabladatos.getValueAt(index, 1).toString();
        codigo = tabladatos.getValueAt(index, 0).toString();
        if (tablaopciones.getSelectedIndex() == 1) {
            if (tipousuario != null) {
                txtaccesom.setText(tipousuario);
                txtaccesom.setEnabled(true);
            }
        } else if (tablaopciones.getSelectedIndex() == 2) {
            if (tipousuario != null) {
                txtaccesoe.setText(tipousuario);
                txtaccesoe.setEnabled(false);
            }
        }
    }//GEN-LAST:event_tabladatosMouseClicked

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        conec.conectar();
        final String[] columnas = {"Código", "Categoria"};
        String consulta = "select codigo_tipousuario,nombre_tipousuario from tipousuario where nombre_tipousuario like '%" + txtbusqueda.getText() + "%' and estado_tipousuario=1;";
        tabladatos.setModel(conec.consultaget(consulta, columnas));
        conec.desconectar();
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtbusquedaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtbusquedaHierarchyChanged

    }//GEN-LAST:event_txtbusquedaHierarchyChanged

    private void txtbusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbusquedaInputMethodTextChanged

    }//GEN-LAST:event_txtbusquedaInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipousuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipousuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptare;
    private javax.swing.JButton btnaceptarm;
    private javax.swing.JButton btnaceptarn;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private javax.swing.JLabel lblaccesoe;
    private javax.swing.JLabel lblaccesom;
    private javax.swing.JLabel lblacesson;
    private javax.swing.JLabel lblbuscar;
    private javax.swing.JPanel panel1;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTabbedPane tablaopciones;
    private javax.swing.JTextField txtaccesoe;
    private javax.swing.JTextField txtaccesom;
    private javax.swing.JTextField txtacceson;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
