/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import clases.controlformularios;
import clases.impresiones;
import javax.swing.JDialog;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author WINDOWS
 */
public class facturacion extends javax.swing.JFrame {

    private conexion conec = new conexion();

    /**
     * Creates new form facturacion
     */
    public facturacion() {
        initComponents();cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    private void cargar() {
        conec.conectar();
        String columnas[] = {"Punto de venta", "Cod. Factura", "Ruc", "Fecha Emision", "Total"};
        tabladatos.setModel(conec.consultaget("SELECT fc.cod_facturaco,fc.codigo_fact,fc.ruc_proveedor,fc.fecha_emision,fc.total_facturaco FROM facturasco fc WHERE fecha_emision>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)", columnas));
        tabladatos1.setModel(conec.consultaget("SELECT fc.cod_facturave,fc.codigo_fact,fc.numero_cliente ,fc.fecha_emision,fc.total_facturave FROM facturasve fc WHERE fecha_emision>=DATE_SUB(CURDATE(),INTERVAL 30 DAY)", columnas));
        conec.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaopciones = new javax.swing.JTabbedPane();
        panel4 = new org.edisoncor.gui.panel.Panel();
        btnmodificar = new javax.swing.JButton();
        btnanular = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        lbltabla = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        btncrear = new javax.swing.JButton();
        btnayudas1 = new javax.swing.JButton();
        panel5 = new org.edisoncor.gui.panel.Panel();
        btnanular1 = new javax.swing.JButton();
        btnmodificar1 = new javax.swing.JButton();
        btnsalir1 = new javax.swing.JButton();
        lbltabla1 = new javax.swing.JLabel();
        btncrear1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabladatos1 = new javax.swing.JTable();
        btnayudas2 = new javax.swing.JButton();
        panel6 = new org.edisoncor.gui.panel.Panel();
        btnreporte = new javax.swing.JButton();
        btnreporte1 = new javax.swing.JButton();
        btnreporte2 = new javax.swing.JButton();

        tablaopciones.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        panel4.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel4.setColorSecundario(new java.awt.Color(255, 153, 0));

        btnmodificar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnanular.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnanular.setText("ANULAR");
        btnanular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanularActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        lbltabla.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbltabla.setText("TABLA DE DOCUMENTOS EMITIDOS");

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        btncrear.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncrear.setText("CREAR");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnayudas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbltabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnayudas1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btncrear)
                                .addGap(22, 22, 22)
                                .addComponent(btnmodificar)
                                .addGap(18, 18, 18)
                                .addComponent(btnanular)
                                .addGap(37, 37, 37)
                                .addComponent(btnsalir)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbltabla))
                    .addComponent(btnayudas1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        tablaopciones.addTab("FACTURA COMPRA", panel4);

        panel5.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel5.setColorSecundario(new java.awt.Color(255, 153, 0));

        btnanular1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnanular1.setText("ANULAR");

        btnmodificar1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnmodificar1.setText("MODIFICAR");
        btnmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificar1ActionPerformed(evt);
            }
        });

        btnsalir1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnsalir1.setText("SALIR");
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });

        lbltabla1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbltabla1.setText("TABLA DE DOCUMENTOS EMITIDOS");

        btncrear1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncrear1.setText("CREAR");
        btncrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrear1ActionPerformed(evt);
            }
        });

        tabladatos1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabladatos1);

        btnayudas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lbltabla1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnayudas2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel5Layout.createSequentialGroup()
                        .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel5Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btncrear1)
                                .addGap(22, 22, 22)
                                .addComponent(btnmodificar1)
                                .addGap(18, 18, 18)
                                .addComponent(btnanular1)
                                .addGap(37, 37, 37)
                                .addComponent(btnsalir1)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltabla1)
                    .addComponent(btnayudas2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanular1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tablaopciones.addTab("FACTURA VENTA", panel5);

        panel6.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel6.setColorSecundario(new java.awt.Color(255, 153, 0));

        btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/nue_vo.png"))); // NOI18N
        btnreporte.setText("Facturas Compras");
        btnreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteActionPerformed(evt);
            }
        });

        btnreporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/nue_vo.png"))); // NOI18N
        btnreporte1.setText("Facturas Ventas");
        btnreporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte1ActionPerformed(evt);
            }
        });

        btnreporte2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/nue_vo.png"))); // NOI18N
        btnreporte2.setText("Imprimir Facturas");
        btnreporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporte2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnreporte)
                .addGap(36, 36, 36)
                .addComponent(btnreporte2)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel6Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(btnreporte1)
                    .addContainerGap(510, Short.MAX_VALUE)))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreporte, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel6Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(btnreporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );

        tablaopciones.addTab("REPORTES", panel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        facturacompra compra = new facturacompra();
        dialogo jd = new dialogo(compra, true);
        jd.setContentPane(compra.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btncrearActionPerformed

    private void btncrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrear1ActionPerformed
        facturaventa venta = new facturaventa();
        dialogo jd = new dialogo(venta, true);
        jd.setContentPane(venta.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btncrear1ActionPerformed

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalir1ActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnanularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnanularActionPerformed

    private void btnmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificar1ActionPerformed

    private void btnreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteActionPerformed
        imp.imspresionset("rfcompras.jasper");
    }//GEN-LAST:event_btnreporteActionPerformed

    private void btnreporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte1ActionPerformed
        imp.imspresionset("rfventas.jasper");
    }//GEN-LAST:event_btnreporte1ActionPerformed

    private void btnreporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporte2ActionPerformed
         imp.imspresionset("facturaco.jasper");
    }//GEN-LAST:event_btnreporte2ActionPerformed
impresiones imp=new impresiones();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new facturacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanular;
    private javax.swing.JButton btnanular1;
    private javax.swing.JButton btnayudas1;
    private javax.swing.JButton btnayudas2;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btncrear1;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificar1;
    private javax.swing.JButton btnreporte;
    private javax.swing.JButton btnreporte1;
    private javax.swing.JButton btnreporte2;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsalir1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbltabla;
    private javax.swing.JLabel lbltabla1;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.Panel panel5;
    private org.edisoncor.gui.panel.Panel panel6;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTable tabladatos1;
    private javax.swing.JTabbedPane tablaopciones;
    // End of variables declaration//GEN-END:variables
}
