/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cuentascorrientes;

import clases.controlformularios;
import clases.impresiones;
import clases.letrasn;
import clientes.buscarc;
import clientes.buscarp;
import clientes.clientesprov;
import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.panel;

/**
 *
 * @author USUARIO
 */
public class cuentasg extends javax.swing.JFrame {

    /**
     * Creates new form cuentasg
     */
    public cuentasg() {
        initComponents();
        acuentasc();
        desactivoc();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
        this.setTitle("Cuenta corriente Nro: " + listacuentas.ncuenta + " " + listacuentas.ndes);
        saldoch();
        cargardere();
        chequesc();
        dcdesde.setDate(fecha);
        dchasta.setDate(fecha);
    }

    private void saldoch() {
        conec.conectar();
        txtsaldo.setText(conec.consultac2get("select * from cuentascorr where num_cuentacorr='" + listacuentas.ndes + "' ", "saldo_cuentacorr"));
        conec.desconectar();
    }

    private void cargardere() {
        conec.conectar();
        lblcontadordr.setText(conec.consultac2get("select count(*) from deporeti dr where dr.num_cuentacorr='" + listacuentas.ndes + "'", "count(*)"));
        String columnas[] = {"Nro. Cta Cte", "Nro. Trans", "Emision", "Tipo", "Referencia", "Monto $"};
        tabladr.setModel(conec.consultaget("select dr.num_cuentacorr,dr.cod_deporeti,dr.emision,dr.tipo_deporeti,dr.referencia_deporeti,dr.monto_depo from deporeti dr where dr.estado_deporeti=1 and dr.num_cuentacorr='" + listacuentas.ndes + "'", columnas));
        conec.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdradios = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        tablaopciones = new javax.swing.JTabbedPane();
        panel6 = new org.edisoncor.gui.panel.Panel();
        panel1 = new javax.swing.JPanel();
        lblemision = new javax.swing.JLabel();
        dcemision = new com.toedter.calendar.JDateChooser();
        lblncheque = new javax.swing.JLabel();
        txtncheque = new javax.swing.JTextField();
        lblmonto = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        lblpaguese = new javax.swing.JLabel();
        lblpaguese1 = new javax.swing.JLabel();
        txtpaguese = new javax.swing.JTextField();
        btnbuscarcp = new javax.swing.JButton();
        cbtipo = new javax.swing.JComboBox();
        lblcantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        lblreferencia = new javax.swing.JLabel();
        txtreferencia = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        lblsaldo = new javax.swing.JLabel();
        txtsaldo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablacheques = new javax.swing.JTable();
        lblchequespor = new javax.swing.JLabel();
        btnmodificarch = new javax.swing.JButton();
        btnnuevoch = new javax.swing.JButton();
        btneliminarch = new javax.swing.JButton();
        btnsalirch = new javax.swing.JButton();
        cbclasificar = new javax.swing.JComboBox();
        lbldesde = new javax.swing.JLabel();
        lblhasta = new javax.swing.JLabel();
        dcdesde = new com.toedter.calendar.JDateChooser();
        dchasta = new com.toedter.calendar.JDateChooser();
        rdcliente = new javax.swing.JRadioButton();
        rdproveedor = new javax.swing.JRadioButton();
        btnver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblcontadorch = new javax.swing.JLabel();
        panel7 = new org.edisoncor.gui.panel.Panel();
        lblregistros = new javax.swing.JLabel();
        lblcontadordr = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabladr = new javax.swing.JTable();
        btnmodificarmdr = new javax.swing.JButton();
        btneliminardr = new javax.swing.JButton();
        btnsalirdr = new javax.swing.JButton();
        btnnuevodr = new javax.swing.JButton();
        lbltransaccionesr = new javax.swing.JLabel();
        panel8 = new org.edisoncor.gui.panel.Panel();
        lblmostrarcc = new javax.swing.JLabel();
        cbtipocc = new javax.swing.JComboBox();
        lblnumerocc = new javax.swing.JLabel();
        lblcontadorcc = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablacc = new javax.swing.JTable();
        btnaceptarcc = new javax.swing.JButton();
        btncancelarcc = new javax.swing.JButton();
        btnpagar = new javax.swing.JButton();
        panel10 = new org.edisoncor.gui.panel.Panel();
        lblapertura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacuentas = new javax.swing.JTable();
        btncrear = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnimprimircc = new javax.swing.JButton();

        jButton1.setText("jButton1");

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tablaopciones.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N

        panel6.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel6.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel6MouseMoved(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setEnabled(false);

        lblemision.setText("Emision");

        lblncheque.setText("Cheque Nro.");

        txtncheque.setText("0");

        lblmonto.setText("Monto Us $");

        txtmonto.setText("0");
        txtmonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtmontoMouseClicked(evt);
            }
        });

        lblpaguese.setText("Paguese a la ");

        lblpaguese1.setText("orden de :");

        txtpaguese.setToolTipText("Ingrese la información requerida ");

        btnbuscarcp.setText("Buscar");
        btnbuscarcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcpActionPerformed(evt);
            }
        });

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clientes", "Proveedores" }));
        cbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoActionPerformed(evt);
            }
        });

        lblcantidad.setText("La Cantidad");

        txtcantidad.setToolTipText("Ingrese la información requerida ");

        lblreferencia.setText("Referencia");

        txtreferencia.setToolTipText("Ingrese la información requerida ");

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblemision)
                                    .addComponent(lblpaguese))
                                .addGap(54, 54, 54)
                                .addComponent(dcemision, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblpaguese1)
                                    .addComponent(lblcantidad)
                                    .addComponent(lblreferencia))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtpaguese)
                                            .addComponent(txtreferencia, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(btnbuscarcp)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnaceptar, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(txtcantidad)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblncheque)
                            .addComponent(lblmonto))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmonto)
                            .addComponent(txtncheque, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblncheque)
                        .addComponent(txtncheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcemision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemision))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmonto)
                            .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblpaguese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpaguese1))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpaguese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscarcp)
                        .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcantidad)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblreferencia)
                        .addComponent(txtreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblsaldo.setText("Saldo de la Cta.Cte US $ ");

        txtsaldo.setEnabled(false);
        txtsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsaldoActionPerformed(evt);
            }
        });

        tablacheques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablacheques);

        lblchequespor.setText("Cheques por: ");

        btnmodificarch.setText("Modificar");
        btnmodificarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarchActionPerformed(evt);
            }
        });

        btnnuevoch.setText("Nuevo");
        btnnuevoch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevochActionPerformed(evt);
            }
        });

        btneliminarch.setText("Eliminar");
        btneliminarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarchActionPerformed(evt);
            }
        });

        btnsalirch.setText("Salir");
        btnsalirch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirchActionPerformed(evt);
            }
        });

        cbclasificar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Fechas", "Clasificar" }));
        cbclasificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbclasificarActionPerformed(evt);
            }
        });

        lbldesde.setText("Desde");

        lblhasta.setText("Hasta");

        dcdesde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dcdesdeMouseClicked(evt);
            }
        });
        dcdesde.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dcdesdeMouseMoved(evt);
            }
        });
        dcdesde.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dcdesdeComponentShown(evt);
            }
        });
        dcdesde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dcdesdeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dcdesdeFocusLost(evt);
            }
        });
        dcdesde.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                dcdesdeHierarchyChanged(evt);
            }
        });
        dcdesde.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                dcdesdeAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dcdesdeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dcdesde.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                dcdesdeVetoableChange(evt);
            }
        });

        rdradios.add(rdcliente);
        rdcliente.setText("Clientes");

        rdradios.add(rdproveedor);
        rdproveedor.setText("Proveedores");

        btnver.setText("Ver");
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });

        jLabel1.setText("Nro Transacciones");

        lblcontadorch.setText("0");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel6Layout.createSequentialGroup()
                                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel6Layout.createSequentialGroup()
                                        .addComponent(lblchequespor)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbclasificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel6Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblcontadorch)))
                                .addGap(18, 18, 18)
                                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel6Layout.createSequentialGroup()
                                        .addComponent(lbldesde)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dcdesde, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblhasta)
                                        .addGap(0, 14, Short.MAX_VALUE)
                                        .addComponent(dchasta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel6Layout.createSequentialGroup()
                                        .addComponent(rdcliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdproveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnver)))
                                .addGap(65, 65, 65))
                            .addGroup(panel6Layout.createSequentialGroup()
                                .addComponent(lblsaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnuevoch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmodificarch)
                            .addComponent(btneliminarch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsalirch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 159, Short.MAX_VALUE))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblsaldo)
                            .addComponent(txtsaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblhasta)
                                .addComponent(dchasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dcdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblchequespor)
                                .addComponent(cbclasificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbldesde)))
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdcliente)
                                    .addComponent(rdproveedor)
                                    .addComponent(btnver))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblcontadorch))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnnuevoch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificarch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminarch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalirch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tablaopciones.addTab("Chequera", panel6);

        panel7.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel7.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel7MouseMoved(evt);
            }
        });

        lblregistros.setText("Total de Registros:");

        lblcontadordr.setText("0");

        tabladr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabladr);

        btnmodificarmdr.setText("Modificar");
        btnmodificarmdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarmdrActionPerformed(evt);
            }
        });

        btneliminardr.setText("Eliminar");
        btneliminardr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminardrActionPerformed(evt);
            }
        });

        btnsalirdr.setText("Salir");
        btnsalirdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirdrActionPerformed(evt);
            }
        });

        btnnuevodr.setText("Nuevo");
        btnnuevodr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevodrActionPerformed(evt);
            }
        });

        lbltransaccionesr.setText("Transacciones de Registros de Depositos y Retiros");

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltransaccionesr)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel7Layout.createSequentialGroup()
                        .addComponent(lblregistros)
                        .addGap(18, 18, 18)
                        .addComponent(lblcontadordr)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevodr)
                .addGap(36, 36, 36)
                .addComponent(btnmodificarmdr)
                .addGap(39, 39, 39)
                .addComponent(btneliminardr)
                .addGap(30, 30, 30)
                .addComponent(btnsalirdr, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblregistros)
                    .addComponent(lblcontadordr))
                .addGap(18, 18, 18)
                .addComponent(lbltransaccionesr)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btneliminardr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodificarmdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsalirdr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnuevodr, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tablaopciones.addTab("Depositos y Retiros", panel7);

        panel8.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel8.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel8MouseMoved(evt);
            }
        });

        lblmostrarcc.setText("Mostrar ");

        cbtipocc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));
        cbtipocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoccActionPerformed(evt);
            }
        });

        lblnumerocc.setText("Total de registros procesados");

        lblcontadorcc.setText("0");

        tablacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaccMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablacc);

        btnaceptarcc.setText("Aceptar");
        btnaceptarcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarccActionPerformed(evt);
            }
        });

        btncancelarcc.setText("Cancelar");
        btncancelarcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarccActionPerformed(evt);
            }
        });

        btnpagar.setText("Pagar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addComponent(lblmostrarcc)
                        .addGap(18, 18, 18)
                        .addComponent(cbtipocc, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addComponent(lblnumerocc)
                        .addGap(18, 18, 18)
                        .addComponent(lblcontadorcc))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpagar)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaceptarcc)
                .addGap(62, 62, 62)
                .addComponent(btncancelarcc)
                .addGap(85, 85, 85))
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmostrarcc)
                    .addComponent(cbtipocc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumerocc)
                    .addComponent(lblcontadorcc))
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnpagar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btncancelarcc, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnaceptarcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        tablaopciones.addTab("Cheques Cobrados", panel8);

        panel10.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel10.setColorSecundario(new java.awt.Color(255, 153, 0));
        panel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panel10MouseMoved(evt);
            }
        });

        lblapertura.setText("Apertura de Cuentas Corrientes");

        tablacuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablacuentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacuentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacuentas);

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        btnmodificar.setText("Modificar");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnimprimircc.setText("Imprimir");
        btnimprimircc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblapertura))
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel10Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btncrear)
                                .addGap(14, 14, 14)
                                .addComponent(btnmodificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btneliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnimprimircc))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnsalir)
                .addGap(39, 39, 39))
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblapertura)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel10Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimprimircc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tablaopciones.addTab("Crear Cuentas", panel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablaopciones)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private conexion conec = new conexion();
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed
    controlformularios cen = new controlformularios();
    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        cuentacorr nu = new cuentacorr();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btncrearActionPerformed

    private void panel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel10MouseMoved
        acuentasc();
    }//GEN-LAST:event_panel10MouseMoved
    public static int estadocrr = 0;
    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        if (!"".equals(ncuenta)) {
            estadocrr = 1;
            mecuentascorr nu = new mecuentascorr();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        }
    }//GEN-LAST:event_btnmodificarActionPerformed
    public static String ncuenta = "", banco = "";
    private void tablacuentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacuentasMouseClicked
        int index = tablacuentas.getSelectedRow();
        ncuenta = tablacuentas.getValueAt(index, 0).toString();
        banco = tablacuentas.getValueAt(index, 1).toString();
    }//GEN-LAST:event_tablacuentasMouseClicked

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (!"".equals(ncuenta)) {
            estadocrr = 2;
            mecuentascorr nu = new mecuentascorr();
            dialogo jd = new dialogo(nu, true);
            jd.setContentPane(nu.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void cbclasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbclasificarActionPerformed
        tablachequesa();
    }//GEN-LAST:event_cbclasificarActionPerformed
    private Date fecha = new Date();

    private void chequesc() {
        conec.conectar();
        String columnas[] = {"Nro. Cta Cte", "Nro. Cheque", "Emision", "Paguese a", "Referencia", "Monto $", "Situación"};
        tablacc.setModel(conec.consultaget("select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_cliente,apellidos_cliente)as clt,ch.referencia_cheque,ch.monto_cheque,ch.pago_cheque from  cheques ch,clientes c,proveedores p where ch.paguese_cheque=c.cedula_cliente and ch.num_cuenta='" + listacuentas.ndes + "'  union select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_proveedor,apellidos_proveedor)as clt,ch.referencia_cheque,ch.monto_cheque,ch.pago_cheque from  cheques ch,proveedores p where ch.paguese_cheque=p.ruc_proveedor and ch.num_cuenta='" + listacuentas.ndes + "'", columnas));
        conec.desconectar();
    }

    private void tablachequesa() {
        String columnas[] = {"Nro. Cta Cte", "Nro. Cheque", "Emision", "Paguese a", "Referencia", "Monto $"};
        conec.conectar();
        if (cbclasificar.getSelectedIndex() == 0) {
            tablacheques.setModel(conec.consultaget("select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_cliente,apellidos_cliente)as clt,ch.referencia_cheque,ch.monto_cheque from  cheques ch,clientes c,proveedores p where ch.paguese_cheque=c.cedula_cliente and ch.num_cuenta='" + listacuentas.ndes + "'  union select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_proveedor,apellidos_proveedor)as clt,ch.referencia_cheque,ch.monto_cheque from  cheques ch,proveedores p where ch.paguese_cheque=p.ruc_proveedor and ch.num_cuenta='" + listacuentas.ndes + "'", columnas));
            rdcliente.setVisible(false);
            rdproveedor.setVisible(false);
            dcdesde.setVisible(false);
            dchasta.setVisible(false);
            lbldesde.setVisible(false);
            lblhasta.setVisible(false);
            btnver.setVisible(false);
        } else if (cbclasificar.getSelectedIndex() == 1) {

            rdcliente.setVisible(false);
            rdproveedor.setVisible(false);
            dcdesde.setVisible(true);
            dchasta.setVisible(true);
            lbldesde.setVisible(true);
            lblhasta.setVisible(true);
            btnver.setVisible(true);
        } else if (cbclasificar.getSelectedIndex() == 2) {
            rdcliente.setVisible(true);
            rdproveedor.setVisible(true);
            dcdesde.setVisible(false);
            dchasta.setVisible(false);
            lbldesde.setVisible(false);
            lblhasta.setVisible(false);
            btnver.setVisible(false);
        }
        conec.desconectar();
    }
    private void btnnuevochActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevochActionPerformed
        activoc();
        dcemision.setDate(fecha);
    }//GEN-LAST:event_btnnuevochActionPerformed
    private int estadoch = 0;
    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        if (Double.parseDouble(txtmonto.getText()) < Double.parseDouble(txtsaldo.getText())) {
            conec.conectar();
            int año = dcemision.getCalendar().get(Calendar.YEAR);
            int mes = dcemision.getCalendar().get(Calendar.MONTH) + 1;
            int dia = dcemision.getCalendar().get(Calendar.DAY_OF_MONTH);
            if (estadoch == 0) {
                if (!"".equals(txtncheque.getText()) && !"".equals(txtpaguese.getText()) && !"0".equals(txtmonto.getText())) {
                    conec.consultaset("INSERT INTO `alexanderflower`.`cheques` (`num_cuenta`, `num_cheque`, `monto_cheque`, `fecha_cheque`, `paguese_cheque`, `tipo_cheque`, `referencia_cheque`, `estado_cheque`) VALUES ('" + listacuentas.ndes + "', '" + txtncheque.getText() + "', '" + txtmonto.getText() + "', '" + año + "-" + mes + "-" + dia + "', '" + buscarc.cedula + "', '1', '" + txtreferencia.getText() + "', '1');");
                    limpiarch();
                    saldoch();
                    desactivoc();
                    chequesc();
                }
            } else if (estadoch == 1) {
                if (!"".equals(txtncheque.getText()) && !"".equals(txtpaguese.getText()) && !"0".equals(txtmonto.getText())) {
                    conec.consultaset("INSERT INTO `alexanderflower`.`cheques` (`num_cuenta`, `num_cheque`, `monto_cheque`, `fecha_cheque`, `paguese_cheque`, `tipo_cheque`, `referencia_cheque`, `estado_cheque`) VALUES ('" + listacuentas.ndes + "', '" + txtncheque.getText() + "', '" + txtmonto.getText() + "', '" + año + "-" + mes + "-" + dia + "', '" + buscarp.ruc + "', '2', '" + txtreferencia.getText() + "', '1');");
                    limpiarch();
                    saldoch();
                    desactivoc();
                    chequesc();
                }
            }
            conec.desconectar();

        } else {
            JOptionPane.showMessageDialog(this, "Saldo Insuficiente");
        }
    }//GEN-LAST:event_btnaceptarActionPerformed
    private void limpiarch() {
        txtncheque.setText("");
        txtmonto.setText("");
        txtpaguese.setText("");
        txtcantidad.setText("");
        txtreferencia.setText("");
    }

    private void btnbuscarcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcpActionPerformed
        if (cbtipo.getSelectedIndex() == 0) {
            clientesprov.verme = 100;
            buscarc cliente = new buscarc();
            dialogo jd = new dialogo(cliente, true);
            jd.setContentPane(cliente.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            txtpaguese.setText(buscarc.nombres + " " + buscarc.apellidos);

        } else if (cbtipo.getSelectedIndex() == 1) {
            clientesprov.verme = 100;
            buscarp cliente = new buscarp();
            dialogo jd = new dialogo(cliente, true);
            jd.setContentPane(cliente.getContentPane());
            jd.pack();
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            txtpaguese.setText(buscarp.nombres + " " + buscarp.apellidos);
        }
    }//GEN-LAST:event_btnbuscarcpActionPerformed

    private void txtsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsaldoActionPerformed

    }//GEN-LAST:event_txtsaldoActionPerformed

    private void btnsalirchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirchActionPerformed
        this.setVisible(false);
        listacuentas.ncuenta = "";
        listacuentas.ndes = "";
    }//GEN-LAST:event_btnsalirchActionPerformed

    private void cbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoActionPerformed
        if (cbtipo.getSelectedIndex() == 0) {
            estadoch = 0;
        } else if (cbtipo.getSelectedIndex() == 1) {
            estadoch = 1;
        }
    }//GEN-LAST:event_cbtipoActionPerformed

    private void dcdesdeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dcdesdeAncestorAdded

    }//GEN-LAST:event_dcdesdeAncestorAdded

    private void dcdesdeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcdesdeFocusGained

    }//GEN-LAST:event_dcdesdeFocusGained

    private void dcdesdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcdesdeMouseClicked

    }//GEN-LAST:event_dcdesdeMouseClicked

    private void dcdesdeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dcdesdeMouseMoved

    }//GEN-LAST:event_dcdesdeMouseMoved

    private void dcdesdeHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_dcdesdeHierarchyChanged

    }//GEN-LAST:event_dcdesdeHierarchyChanged

    private void panel6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel6MouseMoved
        conec.conectar();
        lblcontadorch.setText(conec.consultac2get("select count(*) from cheques ch where ch.num_cuenta='" + listacuentas.ndes + "'", "count(*)"));
        conec.desconectar();
        tablachequesa();
//vgdg
    }//GEN-LAST:event_panel6MouseMoved

    private void dcdesdeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dcdesdeComponentShown

    }//GEN-LAST:event_dcdesdeComponentShown

    private void dcdesdeVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_dcdesdeVetoableChange

    }//GEN-LAST:event_dcdesdeVetoableChange

    private void dcdesdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dcdesdeFocusLost

    }//GEN-LAST:event_dcdesdeFocusLost

    private void dcdesdeAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dcdesdeAncestorMoved

    }//GEN-LAST:event_dcdesdeAncestorMoved

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        conec.conectar();
        String columnas[] = {"Nro. Cta Cte", "Nro. Cheque", "Emision", "Paguese a", "Referencia", "Monto $"};
        int año = dcdesde.getCalendar().get(Calendar.YEAR);
        int mes = dcdesde.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcdesde.getCalendar().get(Calendar.DAY_OF_MONTH);
        int año1 = dchasta.getCalendar().get(Calendar.YEAR);
        int mes1 = dchasta.getCalendar().get(Calendar.MONTH) + 1;
        int dia1 = dchasta.getCalendar().get(Calendar.DAY_OF_MONTH);
        if (dcdesde.getDate().before(dchasta.getDate())) {
            tablacheques.setModel(conec.consultaget("select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_cliente,apellidos_cliente)as clt,ch.referencia_cheque,ch.monto_cheque from  cheques ch,clientes c,proveedores p where ch.paguese_cheque=c.cedula_cliente and (ch.fecha_cheque>'" + año + "-" + mes + "-" + dia + "' and ch.fecha_cheque<'" + año1 + "-" + mes1 + "-" + dia1 + "') and ch.num_cuenta='" + listacuentas.ndes + "' union select ch.num_cuenta,ch.num_cheque,ch.fecha_cheque,concat_ws(' ',nombres_proveedor,apellidos_proveedor)as clt,ch.referencia_cheque,ch.monto_cheque from  cheques ch,proveedores p where ch.paguese_cheque=p.ruc_proveedor and (ch.fecha_cheque>'" + año + "-" + mes + "-" + dia + "' and ch.fecha_cheque<'" + año1 + "-" + mes1 + "-" + dia1 + "') and ch.num_cuenta='" + listacuentas.ndes + "'", columnas));
        } else {
            JOptionPane.showMessageDialog(this, "La Fecha desde no debo ser \n mayor a la de Hasta");
        }
        if (dchasta.getDate().before(dcdesde.getDate())) {
            JOptionPane.showMessageDialog(this, "La Fecha Hasta no debo ser \n menor a la de Desde");
        } else {

        }
        conec.desconectar();
    }//GEN-LAST:event_btnverActionPerformed

    private void txtmontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmontoMouseClicked
        letrasn NumLetra = new letrasn();
        String numero = txtmonto.getText();
        txtcantidad.setText(NumLetra.Convertir(numero, true));
    }//GEN-LAST:event_txtmontoMouseClicked

    private void btnnuevodrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevodrActionPerformed
        deporeti depo = new deporeti();
        controlformularios cen = new controlformularios();
        dialogo jd = new dialogo(depo, true);
        jd.setContentPane(depo.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btnnuevodrActionPerformed

    private void panel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel7MouseMoved
        cargardere();
    }//GEN-LAST:event_panel7MouseMoved

    private void panel8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel8MouseMoved

    }//GEN-LAST:event_panel8MouseMoved
    private int index = 0;
    private void tablaccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaccMouseClicked
        index = tablacc.getSelectedRow();

    }//GEN-LAST:event_tablaccMouseClicked

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed
        if (!"Cobrado H".equals(tablacc.getValueAt(index, 6).toString())) {
            tablacc.setValueAt("Cobrado", index, 6);
        }
    }//GEN-LAST:event_btnpagarActionPerformed

    private void btnaceptarccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarccActionPerformed
        int año = dcdesde.getCalendar().get(Calendar.YEAR);
        int mes = dcdesde.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcdesde.getCalendar().get(Calendar.DAY_OF_MONTH);
        for (int i = 0; i < tablacc.getRowCount(); i++) {
            conec.conectar();
            if ("Cobrado".equals(tablacc.getValueAt(i, 6).toString())) {
                conec.consultaset("UPDATE `alexanderflower`.`cheques` SET `pago_cheque`='Cobrado H' WHERE `num_cheque`='" + tablacc.getValueAt(i, 1).toString() + "' and`num_cuenta`='" + listacuentas.ndes + "';");

                double saldoa = Double.parseDouble(conec.consultac2get("select * from cuentascorr where num_cuentacorr='" + listacuentas.ndes + "'", "saldo_cuentacorr"));
                saldoa = saldoa - Double.parseDouble(tablacc.getValueAt(i, 5).toString());
                conec.consultaset("UPDATE `alexanderflower`.`cuentascorr` SET `saldo_cuentacorr`=" + saldoa + " WHERE `num_cuentacorr`='" + listacuentas.ndes + "';");
                String codigoa = conec.consultac2get("select t.transmanu from transacciones t where transmanu is not null order by transmanu desc limit 1", "transmanu");
                if ("".equals(codigoa)) {
                    codigoa = "0";
                }
                int codigom = Integer.parseInt(codigoa);
                codigom++;
                conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `debe`, `reciboco`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='BANCOS'", "cod_subcuenta2") + "', 'BANCOS', '" + tablacc.getValueAt(i, 5) + "', '" + codigom + "');");
                conec.consultaset("INSERT INTO `alexanderflower`.`transacciones` (`fecha_trans`, `cod_cuenta`, `des_cuenta`, `haber`, `reciboco`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select * from subcuenta2 where nombre_subcuenta2='ANTICIPOS QUINCENA'", "cod_subcuenta2") + "', 'ANTICIPOS QUINCENA', " + tablacc.getValueAt(i, 5) + ", '" + codigom + "');");

                saldoch();
            }
            conec.desconectar();
        }
        chequesc();
        JOptionPane.showMessageDialog(this, "Se Ha realizado con exito");

    }//GEN-LAST:event_btnaceptarccActionPerformed

    private void btncancelarccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarccActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarccActionPerformed
    private impresiones imprimir = new impresiones();
    private void btnimprimirccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirccActionPerformed
        imprimir.imspresionset("rebancos.jasper");

    }//GEN-LAST:event_btnimprimirccActionPerformed

    private void btnmodificarmdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarmdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarmdrActionPerformed

    private void btnmodificarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodificarchActionPerformed

    private void btneliminarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarchActionPerformed

    private void btneliminardrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminardrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminardrActionPerformed

    private void btnsalirdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalirdrActionPerformed

    private void cbtipoccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoccActionPerformed
    private void desactivoc() {
        dcemision.setEnabled(false);
        txtncheque.setEnabled(false);
        txtpaguese.setEnabled(false);
        txtcantidad.setEnabled(false);
        txtreferencia.setEnabled(false);
        txtmonto.setEnabled(false);
        btnbuscarcp.setEnabled(false);
        btnaceptar.setEnabled(false);
        cbtipo.setEnabled(false);
    }

    private void activoc() {
        dcemision.setEnabled(true);
        txtncheque.setEnabled(true);
        txtreferencia.setEnabled(true);
        txtmonto.setEnabled(true);
        btnbuscarcp.setEnabled(true);
        btnaceptar.setEnabled(true);
        cbtipo.setEnabled(true);
    }

    private void acuentasc() {
        String columnas[] = {"Nro. Cta Cte", "Banco", "Para uso de", "Saldo $"};
        conec.conectar();
        tablacuentas.setModel(conec.consultaget("select cr.num_cuentacorr,b.nombre_banco,cr.des_cuentacorr,cr.saldo_cuentacorr from cuentascorr cr,bancos b where b.cod_banco=cr.cod_banco and cr.estado_cuenta=1", columnas));
        conec.desconectar();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuentasg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuentasg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuentasg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuentasg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuentasg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnaceptarcc;
    private javax.swing.JButton btnbuscarcp;
    private javax.swing.JButton btncancelarcc;
    private javax.swing.JButton btncrear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btneliminarch;
    private javax.swing.JButton btneliminardr;
    private javax.swing.JButton btnimprimircc;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnmodificarch;
    private javax.swing.JButton btnmodificarmdr;
    private javax.swing.JButton btnnuevoch;
    private javax.swing.JButton btnnuevodr;
    private javax.swing.JButton btnpagar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsalirch;
    private javax.swing.JButton btnsalirdr;
    private javax.swing.JButton btnver;
    private javax.swing.JComboBox cbclasificar;
    private javax.swing.JComboBox cbtipo;
    private javax.swing.JComboBox cbtipocc;
    private com.toedter.calendar.JDateChooser dcdesde;
    private com.toedter.calendar.JDateChooser dcemision;
    private com.toedter.calendar.JDateChooser dchasta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblapertura;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblchequespor;
    private javax.swing.JLabel lblcontadorcc;
    private javax.swing.JLabel lblcontadorch;
    private javax.swing.JLabel lblcontadordr;
    private javax.swing.JLabel lbldesde;
    private javax.swing.JLabel lblemision;
    private javax.swing.JLabel lblhasta;
    private javax.swing.JLabel lblmonto;
    private javax.swing.JLabel lblmostrarcc;
    private javax.swing.JLabel lblncheque;
    private javax.swing.JLabel lblnumerocc;
    private javax.swing.JLabel lblpaguese;
    private javax.swing.JLabel lblpaguese1;
    private javax.swing.JLabel lblreferencia;
    private javax.swing.JLabel lblregistros;
    private javax.swing.JLabel lblsaldo;
    private javax.swing.JLabel lbltransaccionesr;
    private javax.swing.JPanel panel1;
    private org.edisoncor.gui.panel.Panel panel10;
    private org.edisoncor.gui.panel.Panel panel6;
    private org.edisoncor.gui.panel.Panel panel7;
    private org.edisoncor.gui.panel.Panel panel8;
    private javax.swing.JRadioButton rdcliente;
    private javax.swing.JRadioButton rdproveedor;
    private javax.swing.ButtonGroup rdradios;
    private javax.swing.JTable tablacc;
    private javax.swing.JTable tablacheques;
    private javax.swing.JTable tablacuentas;
    private javax.swing.JTable tabladr;
    public static javax.swing.JTabbedPane tablaopciones;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtmonto;
    private javax.swing.JTextField txtncheque;
    private javax.swing.JTextField txtpaguese;
    private javax.swing.JTextField txtreferencia;
    private javax.swing.JTextField txtsaldo;
    // End of variables declaration//GEN-END:variables
}
