/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import clases.controlformularios;
import clases.oayuda;
import facturacion.facturacompra;
import facturacion.facturaventa;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto_integrador.*;
import proyecto_integrador.conexion;
import proyecto_integrador.dimension;
import proyecto_integrador.imagenes;
import proyecto_integrador.validaciones;

/**
 *
 * @author Cristian
 */
public class buscarc extends javax.swing.JFrame {

    private int index;
    private conexion conec = new conexion();
    public static String cedula = "", ruc = "", nombres = "", apellidos = "", telefono = "", direccion = "", ciudad = "", movil = "", email = "";

    /**
     * Creates new form buscarc
     */
    public buscarc() {
        initComponents();
        cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgradios = new javax.swing.ButtonGroup();
        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        jLabel1 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        rdapellidos = new javax.swing.JRadioButton();
        lblingreso = new javax.swing.JLabel();
        lblbusqueda = new javax.swing.JLabel();
        rdnombres = new javax.swing.JRadioButton();
        rdcedula = new javax.swing.JRadioButton();
        rdruc = new javax.swing.JRadioButton();
        rddireccion = new javax.swing.JRadioButton();
        btnnuevo = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnseleccionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        btnayuda1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        labelMetric7.setForeground(new java.awt.Color(51, 51, 255));
        labelMetric7.setText("BUSCAR CLIENTE");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        txtbusqueda.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtbusqueda.setToolTipText("Ingresa la Informacion Aqui ");
        txtbusqueda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtbusquedaMouseMoved(evt);
            }
        });
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtbusquedaHierarchyChanged(evt);
            }
        });
        txtbusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbusquedaInputMethodTextChanged(evt);
            }
        });
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });

        bgradios.add(rdapellidos);
        rdapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdapellidos.setForeground(new java.awt.Color(51, 51, 51));
        rdapellidos.setText("Apellidos");
        rdapellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdapellidosActionPerformed(evt);
            }
        });

        lblingreso.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblingreso.setForeground(new java.awt.Color(51, 51, 51));
        lblingreso.setText("BUSCAR POR:");

        lblbusqueda.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblbusqueda.setForeground(new java.awt.Color(51, 51, 51));
        lblbusqueda.setText("INGRESELA BUSQUEDA:");

        bgradios.add(rdnombres);
        rdnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdnombres.setForeground(new java.awt.Color(51, 51, 51));
        rdnombres.setText("Nombres");
        rdnombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnombresActionPerformed(evt);
            }
        });

        bgradios.add(rdcedula);
        rdcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdcedula.setForeground(new java.awt.Color(51, 51, 51));
        rdcedula.setText("Cédula");
        rdcedula.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rdcedulaMouseMoved(evt);
            }
        });
        rdcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdcedulaActionPerformed(evt);
            }
        });

        bgradios.add(rdruc);
        rdruc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rdruc.setForeground(new java.awt.Color(51, 51, 51));
        rdruc.setText("Ruc");
        rdruc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrucActionPerformed(evt);
            }
        });

        bgradios.add(rddireccion);
        rddireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        rddireccion.setForeground(new java.awt.Color(51, 51, 51));
        rddireccion.setText("Dirección");
        rddireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rddireccionActionPerformed(evt);
            }
        });

        btnnuevo.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnseleccionar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        tabladatos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        btnayuda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayuda1MouseClicked(evt);
            }
        });
        btnayuda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayuda1ActionPerformed(evt);
            }
        });
        btnayuda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayuda1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(btnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(lblingreso)
                                    .addGap(26, 26, 26)
                                    .addComponent(rdcedula))
                                .addComponent(lblbusqueda))
                            .addGap(18, 18, 18)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtbusqueda)
                                .addGroup(panel3Layout.createSequentialGroup()
                                    .addComponent(rdruc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rddireccion)))))))
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(rdnombres)
                                .addGap(18, 18, 18)
                                .addComponent(rdapellidos))
                            .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnayuda1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(btnayuda1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblingreso)
                    .addComponent(rdcedula)
                    .addComponent(rdruc)
                    .addComponent(rdnombres)
                    .addComponent(rdapellidos)
                    .addComponent(rddireccion))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbusqueda))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnseleccionar)
                    .addComponent(btnnuevo)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void limpieza() {
        DefaultTableModel nuevos = new DefaultTableModel();
        txtbusqueda.setText("");
        txtbusqueda.requestFocus();
        tabladatos.setModel(nuevos);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened
    private void cargar() {
        imagenes p = new imagenes("/proyecto_integrador/imagenes/fondo 1.jpg");
        this.add(p);
        this.repaint();

    }
    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
        try {
            index = tabladatos.getSelectedRow();
            cedula = tabladatos.getValueAt(index, 0).toString();
            ruc = tabladatos.getValueAt(index, 1).toString();
            nombres = tabladatos.getValueAt(index, 2).toString();
            apellidos = tabladatos.getValueAt(index, 3).toString();
            telefono = tabladatos.getValueAt(index, 4).toString();
            direccion = tabladatos.getValueAt(index, 5).toString();
            ciudad = tabladatos.getValueAt(index, 6).toString();
            movil = tabladatos.getValueAt(index, 7).toString();
            email = tabladatos.getValueAt(index, 8).toString();
            clientesprov panel12 = new clientesprov();
            if (panel12.vermeget() == 0 || panel12.vermeget() == 1) {
                modielic nuevoc = new modielic();
                dialogo jd = new dialogo(nuevoc, true);
                jd.setContentPane(nuevoc.getContentPane());
                jd.pack();
                jd.setLocationRelativeTo(null);
                jd.setVisible(true);
            }
            this.setVisible(false);
        } catch (java.lang.ArrayIndexOutOfBoundsException a) {
            JOptionPane.showMessageDialog(this, "Eliga un registro");
        }

    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        nuevoc nu = new nuevoc();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void rddireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rddireccionActionPerformed
        limpieza();
    }//GEN-LAST:event_rddireccionActionPerformed

    private void rdrucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrucActionPerformed
        limpieza();
    }//GEN-LAST:event_rdrucActionPerformed

    private void rdcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdcedulaActionPerformed
        limpieza();
    }//GEN-LAST:event_rdcedulaActionPerformed

    private void rdcedulaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdcedulaMouseMoved

        rdcedula.setToolTipText("buscar por cedula");
    }//GEN-LAST:event_rdcedulaMouseMoved

    private void rdnombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnombresActionPerformed
        limpieza();
    }//GEN-LAST:event_rdnombresActionPerformed

    private void rdapellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdapellidosActionPerformed
        limpieza();
    }//GEN-LAST:event_rdapellidosActionPerformed

    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed
        conec.conectar();
        final String[] columnas = {"Cédula", "Ruc", "Nombres", "Apellidos", "Teléfono", "Dirección", "Ciudad", "Móvil", "Email"};
        String consulta = "";
        if (rdcedula.isSelected()) {
            consulta = "SELECT cedula_cliente,ruc_cliente,nombres_cliente,apellidos_cliente,telefono_cliente,direccion_cliente,nombre_ciudad,movil_cliente,email_cliente FROM clientes,ciudades where ciudades.cod_ciudad=clientes.ciudad_cliente and cedula_cliente like'%" + txtbusqueda.getText() + "%' and estado_cliente=1;";
        } else if (rdruc.isSelected()) {
            consulta = "SELECT cedula_cliente,ruc_cliente,nombres_cliente,apellidos_cliente,telefono_cliente,direccion_cliente,nombre_ciudad,movil_cliente,email_cliente FROM clientes,ciudades where ciudades.cod_ciudad=clientes.ciudad_cliente and ruc_cliente like'%" + txtbusqueda.getText() + "%' and estado_cliente=1;";
        } else if (rdnombres.isSelected()) {
            consulta = "SELECT cedula_cliente,ruc_cliente,nombres_cliente,apellidos_cliente,telefono_cliente,direccion_cliente,nombre_ciudad,movil_cliente,email_cliente FROM clientes,ciudades where ciudades.cod_ciudad=clientes.ciudad_cliente and nombres_cliente like'%" + txtbusqueda.getText() + "%' and estado_cliente=1;";
        } else if (rdapellidos.isSelected()) {
            consulta = "SELECT cedula_cliente,ruc_cliente,nombres_cliente,apellidos_cliente,telefono_cliente,direccion_cliente,nombre_ciudad,movil_cliente,email_cliente FROM clientes,ciudades where ciudades.cod_ciudad=clientes.ciudad_cliente and apellidos_cliente like'%" + txtbusqueda.getText() + "%' and estado_cliente=1;";
        } else if (rddireccion.isSelected()) {
            consulta = "SELECT cedula_cliente,ruc_cliente,nombres_cliente,apellidos_cliente,telefono_cliente,direccion_cliente,nombre_ciudad,movil_cliente,email_cliente FROM clientes,ciudades where ciudades.cod_ciudad=clientes.ciudad_cliente and direccion_cliente like'%" + txtbusqueda.getText() + "%' and estado_cliente=1;";
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una opción");
        }
        tabladatos.setModel(conec.consultaget(consulta, columnas));
        conec.desconectar();
    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void txtbusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbusquedaInputMethodTextChanged

    }//GEN-LAST:event_txtbusquedaInputMethodTextChanged

    private void txtbusquedaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtbusquedaHierarchyChanged

    }//GEN-LAST:event_txtbusquedaHierarchyChanged

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtbusquedaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbusquedaMouseMoved

        txtbusqueda.setToolTipText("Ingrese la Información a Buscar  ");
    }//GEN-LAST:event_txtbusquedaMouseMoved

    private void btnayuda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayuda1MouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayuda1MouseClicked

    private void btnayuda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayuda1ActionPerformed

    }//GEN-LAST:event_btnayuda1ActionPerformed

    private void btnayuda1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayuda1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayuda1KeyPressed
    private clientesprov nuevo = new clientesprov();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgradios;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnayuda1;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private javax.swing.JLabel lblbusqueda;
    private javax.swing.JLabel lblingreso;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JRadioButton rdapellidos;
    private javax.swing.JRadioButton rdcedula;
    private javax.swing.JRadioButton rddireccion;
    private javax.swing.JRadioButton rdnombres;
    private javax.swing.JRadioButton rdruc;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
