/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import clases.controlformularios;
import clases.oayuda;
import static clientes.nuevoc.txtciudad;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.imagenes;
import proyecto_integrador.panel;
import proyecto_integrador.validaciones;
import ubicaciones.buscarciu;

/**
 *
 * @author usuario
 */
public class modielic extends javax.swing.JFrame {

    private validaciones validar = new validaciones();
    private conexion conectar = new conexion();

    /**
     * Creates new form modielic
     */
    public modielic() {
        initComponents();
        cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
        this.setLocationRelativeTo(null);
    }

    private void ruc() {
        if (txtruc.getText().length() == 13) {
            boolean veri = validar.validaruc(txtruc.getText());
            if (veri == true) {
            } else {
                JOptionPane.showMessageDialog(this, "Ruc invalido");
                txtruc.setText("");
                txtruc.requestFocus();
            }
        }
        if (txtruc.getText().length() >= 13) {
            txtruc.setText(validar.rucget());
        }
    }

    private void desactiva() {
        txtruc.setEnabled(false);
        txtnombres.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefono.setEnabled(false);
        txtmovil.setEnabled(false);
        txtciudad.setEnabled(false);
        btnbuscarc.setEnabled(false);
    }

    private void activa() {
        txtruc.setEnabled(true);
        txtnombres.setEnabled(true);
        txtapellidos.setEnabled(true);
        txtdireccion.setEnabled(true);
        txtemail.setEnabled(true);
        txttelefono.setEnabled(true);
        txtmovil.setEnabled(true);
        txtciudad.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        lbltitulo = new org.edisoncor.gui.label.LabelMetric();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btneliminar = new javax.swing.JButton();
        lblciuad = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        txtcedula = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lblruc = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtmovil = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        txtnombres = new javax.swing.JTextField();
        txtruc = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        txtciudad = new javax.swing.JTextField();
        btnbuscarc = new javax.swing.JButton();
        txtdireccion = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        btnayuda = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        lbltitulo.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo.setText(".....................");
        lbltitulo.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lbltitulo.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel2.setText("Telf. movil");

        btneliminar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lblciuad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblciuad.setText("Ciudad");

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcedula.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtcedula.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtcedulaMouseMoved(evt);
            }
        });
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtcedulaHierarchyChanged(evt);
            }
        });
        txtcedula.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtcedulaInputMethodTextChanged(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        lblcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcedula.setText("Numero de Cédula");

        txttelefono.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txttelefono.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txttelefono.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txttelefonoMouseMoved(evt);
            }
        });
        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        lblruc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblruc.setText("Número de RUC");

        lblnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblnombres.setText("Nombres");

        txtemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtemail.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtemail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtemailMouseMoved(evt);
            }
        });
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        txtapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtapellidos.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtapellidos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtapellidosMouseMoved(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        txtmovil.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtmovil.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtmovil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtmovilMouseMoved(evt);
            }
        });
        txtmovil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmovilFocusLost(evt);
            }
        });
        txtmovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmovilKeyTyped(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        txtnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtnombres.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtnombres.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtnombresMouseMoved(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        txtruc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtruc.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtruc.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtrucMouseMoved(evt);
            }
        });
        txtruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrucFocusLost(evt);
            }
        });
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrucKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrucKeyTyped(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblemail.setText("Email");

        txtciudad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtciudad.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtciudad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtciudadMouseMoved(evt);
            }
        });

        btnbuscarc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbuscarc.setText("...");
        btnbuscarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcActionPerformed(evt);
            }
        });

        txtdireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtdireccion.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtdireccion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtdireccionMouseMoved(evt);
            }
        });

        lblapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblapellidos.setText("Apellidos");

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setText("Teléfono");

        lbldireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion.setText("Dirección");

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcedula)
                    .addComponent(lbldireccion)
                    .addComponent(lblapellidos)
                    .addComponent(lblemail)
                    .addComponent(lblnombres))
                .addGap(44, 44, 44)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblciuad)
                        .addGap(109, 109, 109)
                        .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtapellidos)
                                        .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(lblruc)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(panel3Layout.createSequentialGroup()
                            .addComponent(btneliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnactualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btncancelar))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(btnayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcedula)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnombres)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblruc)
                        .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellidos)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail)
                    .addComponent(lblciuad)
                    .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btncancelar)
                    .addComponent(btneliminar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
        if (txttelefono.getText().length() > 0) {
            if (txttelefono.getText().length() > 6 && txttelefono.getText().length() < 8) {

            } else {
                txttelefono.setText("");
                txttelefono.requestFocus();
                JOptionPane.showMessageDialog(this, "Teléfono Invalido");
            }
        }
    }//GEN-LAST:event_txttelefonoFocusLost

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcedulaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtcedulaHierarchyChanged

    }//GEN-LAST:event_txtcedulaHierarchyChanged

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost

    }//GEN-LAST:event_txtcedulaFocusLost

    private void txtcedulaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcedulaInputMethodTextChanged

    }//GEN-LAST:event_txtcedulaInputMethodTextChanged

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyPressed

    }//GEN-LAST:event_txtcedulaKeyPressed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtrucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrucFocusLost
        ruc();
    }//GEN-LAST:event_txtrucFocusLost

    private void txtrucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyPressed

        ruc();
    }//GEN-LAST:event_txtrucKeyPressed

    private void txtrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtrucKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtmovilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmovilFocusLost
        if (txtmovil.getText().length() > 0) {
            if (txtmovil.getText().length() > 9 && txtmovil.getText().length() < 11) {

            } else {
                txtmovil.setText("");
                txtmovil.requestFocus();
                JOptionPane.showMessageDialog(this, "Móvil Invalido");
            }
        }
    }//GEN-LAST:event_txtmovilFocusLost

    private void txtmovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmovilKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtmovilKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void btnbuscarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcActionPerformed

        buscarciu nuevo = new buscarciu();
        clientesprov.eatadobset(1);
        dialogo jd = new dialogo(nuevo, true);
        jd.setContentPane(nuevo.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btnbuscarcActionPerformed

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        if (txtemail.getText().length() > 0) {
            boolean veri = validar.validaemail(txtemail.getText());
            if (veri == true) {

            } else {
                JOptionPane.showMessageDialog(this, "Direccion de Correo Invalido");
                txtemail.setText("");
                txtemail.requestFocus();
            }
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        conectar.conectar();
        String consulta = "select * from ciudades where ciudades.nombre_ciudad='" + txtciudad.getText() + "'";
        int indice = conectar.consultac1get(consulta, "cod_ciudad");
        String consuta = "UPDATE `alexanderflower`.`clientes` SET `nombres_cliente`='" + txtnombres.getText() + "', `apellidos_cliente`='" + txtapellidos.getText() + "', `direccion_cliente`='" + txtdireccion.getText() + "', `telefono_cliente`='" + txttelefono.getText() + "', `ciudad_cliente`='" + indice + "', `movil_cliente`='" + txtmovil.getText() + "', `ruc_cliente`='" + txtruc.getText() + "' WHERE `cedula_cliente`='" + txtcedula.getText() + "';";
        conectar.consultaset(consuta);
        conectar.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed
    private void cargar() {
        imagenes p = new imagenes("/proyecto_integrador/imagenes/fondo_gris.jpg");
        this.add(p);
        this.repaint();

        txtcedula.setText(buscarc.cedula);
        txtnombres.setText(buscarc.nombres);
        txtapellidos.setText(buscarc.apellidos);
        txtdireccion.setText(buscarc.direccion);
        txtemail.setText(buscarc.email);
        txtruc.setText(buscarc.ruc);
        txttelefono.setText(buscarc.telefono);
        txtmovil.setText(buscarc.movil);
        txtciudad.setText(buscarc.ciudad);
        clientesprov nuevo = new clientesprov();
        if (nuevo.vermeget() == 1) {
            lbltitulo.setText("Modificar Información");
            btneliminar.setVisible(false);
            activa();

        }
        if (nuevo.vermeget() == 0) {

            btnactualizar.setVisible(false);
            btneliminar.setBounds(btnactualizar.location().x, btnactualizar.location().y, btneliminar.getWidth(), btneliminar.getHeight());
            lbltitulo.setText("Eliminar Información");
            desactiva();
        }
        System.out.println("" + nuevo.vermeget());
        txtcedula.setEnabled(false);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        conectar.conectar();
        String consuta = "UPDATE `alexanderflower`.`clientes` SET `estado_cliente`='0' WHERE `cedula_cliente`='" + txtcedula.getText() + "';";
        conectar.consultaset(consuta);
        conectar.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtcedulaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcedulaMouseMoved

        txtcedula.setToolTipText("Ingrese La Cedula  ");// TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaMouseMoved

    private void txtnombresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombresMouseMoved

        txtnombres.setToolTipText("Ingrese El Nombre");// TODO add your handling code here:
    }//GEN-LAST:event_txtnombresMouseMoved

    private void txtapellidosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidosMouseMoved

        txtapellidos.setToolTipText("Ingrese El Apellido  ");
// TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosMouseMoved

    private void txtdireccionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMouseMoved

        txtdireccion.setToolTipText("Ingrese La Direccion ");// TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionMouseMoved

    private void txtemailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseMoved

        txtemail.setToolTipText("Ingrese El Correo Electronico ");// TODO add your handling code here:
    }//GEN-LAST:event_txtemailMouseMoved

    private void txtrucMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrucMouseMoved

        txtruc.setToolTipText("Ingrese El Ruc  ");// TODO add your handling code here:
    }//GEN-LAST:event_txtrucMouseMoved

    private void txttelefonoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoMouseMoved

        txttelefono.setToolTipText("Ingrese El Telefono  ");// TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoMouseMoved

    private void txtmovilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmovilMouseMoved

        txtmovil.setToolTipText("Ingrese el Numero de Celular ");        // TODO add your handling code here:
    }//GEN-LAST:event_txtmovilMouseMoved

    private void txtciudadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtciudadMouseMoved

        txtciudad.setToolTipText("Ingrese La Ciudad  ");// TODO add your handling code here:
    }//GEN-LAST:event_txtciudadMouseMoved

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modielic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modielic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modielic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modielic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modielic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnbuscarc;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblciuad;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblruc;
    private org.edisoncor.gui.label.LabelMetric lbltitulo;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcedula;
    public static javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmovil;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
