/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import clases.controlformularios;
import clases.oayuda;
import static clientes.modielic.txtciudad;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.imagenes;
import proyecto_integrador.panel;
import proyecto_integrador.validaciones;
import ubicaciones.buscarciu;

/**
 *
 * @author usuario
 */
public class modielie extends javax.swing.JFrame {

    private conexion conectar = new conexion();
    private validaciones validar = new validaciones();

    private void cedula() {
        if (txtcedula.getText().length() == 10) {
            boolean veri = validar.validarce(txtcedula.getText());
            if (veri == true) {
                activa();

            } else {
                JOptionPane.showMessageDialog(this, "Cédula invalida");
                txtcedula.setText("");
                txtcedula.requestFocus();
                desactiva();
            }
        }
        if (txtcedula.getText().length() >= 10) {
            txtcedula.setText("");
            txtcedula.setText(validar.cedulaget());
        }
    }

    private void desactiva() {
        txtnombres.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefono.setEnabled(false);
        txtmovil.setEnabled(false);
        txtciudad.setEnabled(false);
        btnbuscarc.setEnabled(false);
        txthorai.setEnabled(false);
        txthoraf.setEnabled(false);
        btnactualizar.setEnabled(false);
    }

    private void activa() {
        txtnombres.setEnabled(true);
        txtapellidos.setEnabled(true);
        txtdireccion.setEnabled(true);
        txtemail.setEnabled(true);
        txttelefono.setEnabled(true);
        txtmovil.setEnabled(true);
        btnbuscarc.setEnabled(true);
        txthorai.setEnabled(true);
        txthoraf.setEnabled(true);
        btnactualizar.setEnabled(true);
    }

    private void limpieza() {
        txtcedula.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txtdireccion.setText("");
        txtciudad.setText("");
        txttelefono.setText("");
        txtmovil.setText("");
        txtemail.setText("");
        txthorai.setText("00:00:00");
        txthoraf.setText("00:00:00");
    }

    /**
     * Creates new form modielie
     */
    public modielie() {
        initComponents();
        cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        lbltitulo = new org.edisoncor.gui.label.LabelMetric();
        jLabel3 = new javax.swing.JLabel();
        txtapellidos = new javax.swing.JTextField();
        lblnombres = new javax.swing.JLabel();
        lblciuad = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        txtmovil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        txtciudad = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        btneliminar = new javax.swing.JButton();
        lblcedula = new javax.swing.JLabel();
        btnbuscarc = new javax.swing.JButton();
        btncargo = new javax.swing.JButton();
        txtsalario = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        lblsalario = new javax.swing.JLabel();
        txtdepartamento = new javax.swing.JTextField();
        lbldepartamento = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        btndepartamento = new javax.swing.JButton();
        lbinicio = new javax.swing.JLabel();
        txthorai = new javax.swing.JFormattedTextField();
        lblfin = new javax.swing.JLabel();
        txthoraf = new javax.swing.JFormattedTextField();
        btnayuda = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        lbltitulo.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo.setText(".....................");
        lbltitulo.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lbltitulo.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        txtapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtapellidos.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtapellidos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtapellidosMouseMoved(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        lblnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblnombres.setText("Nombres");

        lblciuad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblciuad.setText("Ciudad");

        txtemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtemail.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtemail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtemailMouseMoved(evt);
            }
        });
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        lblapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblapellidos.setText("Apellidos");

        txtcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcedula.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtcedula.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtcedulaMouseMoved(evt);
            }
        });
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtcedulaHierarchyChanged(evt);
            }
        });
        txtcedula.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtcedulaInputMethodTextChanged(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setText("Teléfono");

        btnactualizar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        txtdireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtdireccion.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtdireccion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtdireccionMouseMoved(evt);
            }
        });

        txttelefono.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txttelefono.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txttelefono.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txttelefonoMouseMoved(evt);
            }
        });
        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        lbldireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion.setText("Dirección");

        lblemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblemail.setText("Email");

        txtmovil.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtmovil.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtmovil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtmovilMouseMoved(evt);
            }
        });
        txtmovil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmovilFocusLost(evt);
            }
        });
        txtmovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmovilKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel2.setText("Telf. movil");

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtciudad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtciudad.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtciudad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtciudadMouseMoved(evt);
            }
        });

        txtnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtnombres.setToolTipText("Ingresa Aqui la Informacion Requerida ");
        txtnombres.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtnombresMouseMoved(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        lblcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcedula.setText("Numero de Cédula");

        btnbuscarc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbuscarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcActionPerformed(evt);
            }
        });

        btncargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargoActionPerformed(evt);
            }
        });

        txtsalario.setText("0");
        txtsalario.setToolTipText("Ingrese el sueldo a percibir por el cargo  que ocupa  ");
        txtsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalarioActionPerformed(evt);
            }
        });

        txtcargo.setToolTipText("Seleccione el cargo que va ocupar   ");

        lblsalario.setText("Salario");

        txtdepartamento.setToolTipText("Seleccione el departamento a ser asignado ");

        lbldepartamento.setText("Departamento");

        lblcargo.setText("Cargo");

        btndepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepartamentoActionPerformed(evt);
            }
        });

        lbinicio.setText("Hora de Inicio Laboral");

        txthorai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm:ss"))));
        txthorai.setText("00:00:00");

        lblfin.setText("Hora de fin Laboral");

        txthoraf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm:ss"))));
        txthoraf.setText("00:00:00");

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldepartamento)
                            .addComponent(lblsalario))
                        .addGap(89, 89, 89)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(txthorai)
                                .addGap(137, 137, 137)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txthoraf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btncargo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblnombres)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldireccion)
                                    .addComponent(lblapellidos)
                                    .addComponent(lblemail)))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblcedula)))
                        .addGap(43, 43, 43)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(txtdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btndepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblcargo)
                                .addGap(256, 256, 256))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtapellidos)
                                            .addComponent(txtnombres)
                                            .addComponent(txtcedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2)))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblciuad)))
                                        .addGap(48, 48, 48)
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(lbinicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfin)
                        .addGap(242, 242, 242))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(btneliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnactualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncancelar))
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addComponent(btnayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcedula)
                            .addComponent(jLabel1)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblnombres)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellidos)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblciuad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblcargo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbldepartamento)
                        .addComponent(txtdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsalario)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbinicio)
                    .addComponent(txthorai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfin)
                    .addComponent(txthoraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        if (txtemail.getText().length() > 0) {
            boolean veri = validar.validaemail(txtemail.getText());
            if (veri == true) {

            } else {
                JOptionPane.showMessageDialog(this, "Direccion de Correo Invalido");
                txtemail.setText("");
                txtemail.requestFocus();
            }
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
        if (txttelefono.getText().length() > 0) {
            if (txttelefono.getText().length() > 6 && txttelefono.getText().length() < 8) {

            } else {
                txttelefono.setText("");
                txttelefono.requestFocus();
                JOptionPane.showMessageDialog(this, "Teléfono Invalido");
            }
        }
    }//GEN-LAST:event_txttelefonoFocusLost

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcedulaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtcedulaHierarchyChanged

    }//GEN-LAST:event_txtcedulaHierarchyChanged

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost

        cedula();
    }//GEN-LAST:event_txtcedulaFocusLost

    private void txtcedulaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcedulaInputMethodTextChanged

    }//GEN-LAST:event_txtcedulaInputMethodTextChanged

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyPressed
        cedula();
    }//GEN-LAST:event_txtcedulaKeyPressed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        conectar.conectar();
        String consulta = "select * from ciudades where ciudades.nombre_ciudad='" + txtciudad.getText() + "'";
        int indice = conectar.consultac1get(consulta, "cod_ciudad");
        int dep = conectar.consultac1get("select * from departamentos where nombre_dep='" + txtdepartamento.getText() + "'", "cod_dep");
        int cargo = conectar.consultac1get("select * from cargos where nombre_cargo='" + txtcargo.getText() + "'", "cod_cargo");
        String consuta = "UPDATE `alexanderflower`.`empleados` SET `nombres_empleado`='" + txtnombres.getText() + "', `apellidos_empleado`='" + txtapellidos.getText() + "', `direccion_empleado`='" + txtdireccion.getText() + "', `telefono_empleado`='" + txttelefono.getText() + "', `movil_empleado`='" + txtmovil.getText() + "', `email_empleado`='" + txtemail.getText() + "', `sueldo_empleado`='" + txtsalario.getText() + "', `cod_departamento`='" + dep + "', `cod_cargo`='" + cargo + "', `horali`='" + txthorai.getText() + "', `horalf`='" + txthoraf.getText() + "' WHERE `cedula_empleado`='" + txtcedula.getText() + "';";
        conectar.consultaset(consuta);
        conectar.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtmovilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmovilFocusLost
        if (txtmovil.getText().length() > 0) {
            if (txtmovil.getText().length() > 9 && txtmovil.getText().length() < 11) {

            } else {
                txtmovil.setText("");
                txtmovil.requestFocus();
                JOptionPane.showMessageDialog(this, "Móvil Invalido");
            }
        }
    }//GEN-LAST:event_txtmovilFocusLost

    private void txtmovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmovilKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtmovilKeyTyped

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void btnbuscarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcActionPerformed
        buscarciu nuevo = new buscarciu();
        clientesprov.eatadobset(5);
        dialogo jd = new dialogo(nuevo, true);
        jd.setContentPane(nuevo.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btnbuscarcActionPerformed
    private void cargar() {
        conectar.conectar();
        imagenes p = new imagenes("/proyecto_integrador/imagenes/fondo_gris.jpg");
        this.add(p);
        this.repaint();

        txtcedula.setText(buscare.cedula);
        txtnombres.setText(buscare.nombres);
        txtapellidos.setText(buscare.apellidos);
        txtdireccion.setText(buscare.direccion);
        txtemail.setText(buscare.email);
        txttelefono.setText(buscare.telefono);
        txtmovil.setText(buscare.movil);
        txtciudad.setText(buscare.ciudad);
        txtsalario.setText(conectar.consultac2get("select * from empleados where cedula_empleado='" + buscare.cedula + "'", "sueldo_empleado"));
        txtcargo.setText(conectar.consultac2get("select nombre_cargo from empleados,cargos where empleados.cod_cargo=cargos.cod_cargo and cedula_empleado='" + buscare.cedula + "'", "nombre_cargo"));
        txtdepartamento.setText(conectar.consultac2get("select nombre_dep from empleados,departamentos where empleados.cod_departamento=departamentos.cod_dep and cedula_empleado='" + buscare.cedula + "'", "nombre_dep"));
        txthorai.setText(conectar.consultac2get("select * from empleados,cargos where empleados.cod_cargo=cargos.cod_cargo and cedula_empleado='" + buscare.cedula + "'", "horali"));
        txthoraf.setText(conectar.consultac2get("select * from empleados,departamentos where empleados.cod_departamento=departamentos.cod_dep and cedula_empleado='" + buscare.cedula + "'", "horalf"));

        clientesprov nuevo = new clientesprov();
        if (nuevo.vermeget() == 5) {
            lbltitulo.setText("Modificar Información");
            btneliminar.setVisible(false);
            activa();

        }
        if (nuevo.vermeget() == 4) {

            btnactualizar.setVisible(false);
            btneliminar.setBounds(btnactualizar.location().x, btnactualizar.location().y, btneliminar.getWidth(), btneliminar.getHeight());
            lbltitulo.setText("Eliminar Información");
            desactiva();
        }
        System.out.println("" + nuevo.vermeget());
        txtcedula.setEnabled(false);
        conectar.desconectar();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        conectar.conectar();
        String consuta = "UPDATE `alexanderflower`.`empleados` SET `estado_empleado`='0' WHERE `cedula_empleado`='" + txtcedula.getText() + "';";
        conectar.consultaset(consuta);
        conectar.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtcedulaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcedulaMouseMoved

        txtcedula.setToolTipText("Ingrese La Cedula  ");

    }//GEN-LAST:event_txtcedulaMouseMoved

    private void txtnombresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombresMouseMoved
        // TODO add your handling code here:

        txtnombres.setToolTipText("Ingrese El Nombre");
    }//GEN-LAST:event_txtnombresMouseMoved

    private void txtapellidosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidosMouseMoved
        // TODO add your handling code here:
        txtapellidos.setToolTipText("Ingrese El Apellido  ");
    }//GEN-LAST:event_txtapellidosMouseMoved

    private void txtdireccionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMouseMoved

        txtdireccion.setToolTipText("Ingrese La Direccion ");// TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionMouseMoved

    private void txtemailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseMoved
        // TODO add your handling code here:
        txtemail.setToolTipText("Ingrese El Correo Electronico ");
    }//GEN-LAST:event_txtemailMouseMoved

    private void txttelefonoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoMouseMoved
        // TODO add your handling code here:
        txttelefono.setToolTipText("Ingrese El Telefono  ");
    }//GEN-LAST:event_txttelefonoMouseMoved

    private void txtmovilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmovilMouseMoved
        // TODO add your handling code here:
        txtmovil.setToolTipText("Ingrese el Numero de Celular ");
    }//GEN-LAST:event_txtmovilMouseMoved

    private void txtciudadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtciudadMouseMoved
        // TODO add your handling code here:
        txtciudad.setToolTipText("Ingrese La Ciudad ");
    }//GEN-LAST:event_txtciudadMouseMoved

    private void btndepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepartamentoActionPerformed
        departamentos nu = new departamentos();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtdepartamento.setText(departamentos.departamento);
    }//GEN-LAST:event_btndepartamentoActionPerformed

    private void btncargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargoActionPerformed
        cargos nu = new cargos();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcargo.setText(cargos.cargo);
    }//GEN-LAST:event_btncargoActionPerformed

    private void txtsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalarioActionPerformed
        conectar.conectar();
        String suel = conectar.consultac2get("select * from parametros", "sueldobasico");
        if (Double.parseDouble(suel) < Double.parseDouble(txtsalario.getText())) {
            JOptionPane.showMessageDialog(this, "El sueldo es menor al sueldo basico");
        }
        conectar.desconectar();
    }//GEN-LAST:event_txtsalarioActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modielie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modielie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modielie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modielie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modielie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnbuscarc;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargo;
    private javax.swing.JButton btndepartamento;
    private javax.swing.JButton btneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbinicio;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblciuad;
    private javax.swing.JLabel lbldepartamento;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfin;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblsalario;
    private org.edisoncor.gui.label.LabelMetric lbltitulo;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcedula;
    public static javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtdepartamento;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JFormattedTextField txthoraf;
    private javax.swing.JFormattedTextField txthorai;
    private javax.swing.JTextField txtmovil;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
