/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientes;

import clases.controlformularios;
import clases.oayuda;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;
import proyecto_integrador.dialogo;
import proyecto_integrador.imagenes;
import proyecto_integrador.panel;
import proyecto_integrador.validaciones;
import ubicaciones.buscarciu;

/**
 *
 * @author usuario
 */
public class nuevoe extends javax.swing.JFrame {

    private conexion conectar = new conexion();
    private validaciones validar = new validaciones();

    /**
     * Creates new form nuevoe
     */
    public nuevoe() {
        initComponents();
        cargar();
        controlformularios cen = new controlformularios();
        this.setBounds(cen.xget(this.getWidth()), cen.yget(this.getHeight()), this.getWidth(), this.getHeight());
    }

    private void cedula() {
        if (txtcedula.getText().length() == 10) {
            boolean veri = validar.validarce(txtcedula.getText());
            if (veri == true) {
                activa();

            } else {
                JOptionPane.showMessageDialog(this, "Cédula invalida");
                txtcedula.setText("");
                txtcedula.requestFocus();
                desactiva();
            }
        }
        if (txtcedula.getText().length() >= 10) {
            txtcedula.setText("");
            txtcedula.setText(validar.cedulaget());
        }
    }

    private void desactiva() {
        txtnombres.setEnabled(false);
        txtapellidos.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtemail.setEnabled(false);
        txttelefono.setEnabled(false);
        txtmovil.setEnabled(false);
        txtciudad.setEnabled(false);
        btnbuscarc.setEnabled(false);
        btnnuevo.setEnabled(false);
        txtcargo.setEnabled(false);
        txtdepartamento.setEnabled(false);
        txtsalario.setEnabled(false);
        txthorai.setEnabled(false);
        txthoraf.setEnabled(false);
        btncargo.setEnabled(false);
        btndepartamento.setEnabled(false);
    }

    private void activa() {
        txtnombres.setEnabled(true);
        txtapellidos.setEnabled(true);
        txtdireccion.setEnabled(true);
        txtemail.setEnabled(true);
        txttelefono.setEnabled(true);
        txtmovil.setEnabled(true);
        btnbuscarc.setEnabled(true);
        btnnuevo.setEnabled(true);
        txtsalario.setEnabled(true);
        txthorai.setEnabled(true);
        txthoraf.setEnabled(true);
        btncargo.setEnabled(true);
        btndepartamento.setEnabled(true);
    }

    private void limpieza() {
        txtcedula.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txtdireccion.setText("");
        txtciudad.setText("");
        txttelefono.setText("");
        txtmovil.setText("");
        txtemail.setText("");
        txtcargo.setText("");
        txtdepartamento.setText("");
        txtsalario.setText("");
        txthorai.setText("00:00:00");
        txthoraf.setText("00:00:00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new org.edisoncor.gui.panel.Panel();
        labelMetric7 = new org.edisoncor.gui.label.LabelMetric();
        jLabel3 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lblapellidos = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        btnbuscarc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblciuad = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btncancelar = new javax.swing.JButton();
        txtcedula = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        btnnuevo = new javax.swing.JButton();
        txtmovil = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        lblemail = new javax.swing.JLabel();
        lbldepartamento = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        lblsalario = new javax.swing.JLabel();
        txtdepartamento = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        btndepartamento = new javax.swing.JButton();
        btncargo = new javax.swing.JButton();
        lbinicio = new javax.swing.JLabel();
        txthorai = new javax.swing.JFormattedTextField();
        lblfin = new javax.swing.JLabel();
        txthoraf = new javax.swing.JFormattedTextField();
        btnayuda = new javax.swing.JButton();
        lblx = new javax.swing.JLabel();
        lblx1 = new javax.swing.JLabel();
        lblx2 = new javax.swing.JLabel();
        lblx3 = new javax.swing.JLabel();
        lblx4 = new javax.swing.JLabel();
        lblx5 = new javax.swing.JLabel();
        lblx6 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel3.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel3.setColorSecundario(new java.awt.Color(255, 153, 0));

        labelMetric7.setForeground(new java.awt.Color(51, 51, 255));
        labelMetric7.setText("NUEVO EMPLEADO ");
        labelMetric7.setColorDeSombra(new java.awt.Color(255, 255, 255));
        labelMetric7.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        txtdireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtdireccion.setToolTipText("Ingresa la Informacion Aqui ");
        txtdireccion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtdireccionMouseMoved(evt);
            }
        });

        lblapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblapellidos.setText("Apellidos");

        lbldireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion.setText("Dirección");

        btnbuscarc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnbuscarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setText("Teléfono");

        lblciuad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblciuad.setText("Ciudad");

        lblnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblnombres.setText("Nombres");

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel2.setText("Telf. movil");

        btncancelar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtcedula.setToolTipText("Ingresa la Informacion Aqui ");
        txtcedula.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtcedulaMouseMoved(evt);
            }
        });
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });
        txtcedula.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtcedulaHierarchyChanged(evt);
            }
        });
        txtcedula.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtcedulaInputMethodTextChanged(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcedulaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });

        lblcedula.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcedula.setText("Numero de Cédula");

        txttelefono.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txttelefono.setToolTipText("Ingresa la Informacion Aqui ");
        txttelefono.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txttelefonoMouseMoved(evt);
            }
        });
        txttelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttelefonoFocusLost(evt);
            }
        });
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        btnnuevo.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        txtmovil.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtmovil.setToolTipText("Ingresa la Informacion Aqui ");
        txtmovil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtmovilMouseMoved(evt);
            }
        });
        txtmovil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtmovilFocusLost(evt);
            }
        });
        txtmovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmovilKeyTyped(evt);
            }
        });

        txtnombres.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtnombres.setToolTipText("Ingresa la Informacion Aqui ");
        txtnombres.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtnombresMouseMoved(evt);
            }
        });
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        txtemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtemail.setToolTipText("Ingresa la Informacion Aqui ");
        txtemail.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtemailMouseMoved(evt);
            }
        });
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtemailFocusLost(evt);
            }
        });

        txtciudad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtciudad.setToolTipText("Ingresa la Informacion Aqui ");
        txtciudad.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtciudadMouseMoved(evt);
            }
        });

        txtapellidos.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtapellidos.setToolTipText("Ingresa la Informacion Aqui ");
        txtapellidos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtapellidosMouseMoved(evt);
            }
        });
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        lblemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblemail.setText("Email");

        lbldepartamento.setText("Departamento");

        lblcargo.setText("Cargo");

        lblsalario.setText("Salario");

        txtdepartamento.setToolTipText("Seleccione el departamento a ser asignado ");

        txtcargo.setToolTipText("Seleccione el cargo que va ocupar   ");

        txtsalario.setText("0");
        txtsalario.setToolTipText("Ingrese el salario del empleado ");
        txtsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalarioActionPerformed(evt);
            }
        });

        btndepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepartamentoActionPerformed(evt);
            }
        });

        btncargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargoActionPerformed(evt);
            }
        });

        lbinicio.setText("Hora de Inicio Laboral");

        txthorai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm:ss"))));
        txthorai.setText("00:00:00");

        lblfin.setText("Hora de fin Laboral");

        txthoraf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm:ss"))));
        txthoraf.setText("00:00:00");

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        lblx.setForeground(new java.awt.Color(255, 0, 0));
        lblx.setText("*");

        lblx1.setForeground(new java.awt.Color(255, 0, 0));
        lblx1.setText("*");

        lblx2.setForeground(new java.awt.Color(255, 0, 0));
        lblx2.setText("*");

        lblx3.setForeground(new java.awt.Color(255, 0, 0));
        lblx3.setText("*");

        lblx4.setForeground(new java.awt.Color(255, 0, 0));
        lblx4.setText("*");

        lblx5.setForeground(new java.awt.Color(255, 0, 0));
        lblx5.setText("*");

        lblx6.setForeground(new java.awt.Color(255, 0, 0));
        lblx6.setText("*");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblemail)
                            .addComponent(lbldepartamento)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcedula)
                                    .addComponent(lblnombres)
                                    .addComponent(lblapellidos)
                                    .addComponent(lbldireccion)
                                    .addComponent(lblsalario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblx5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblx3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblx2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblx1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btncancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtapellidos)
                                            .addComponent(txtnombres)
                                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2)))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblciuad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblx4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel3Layout.createSequentialGroup()
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addComponent(txtdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btndepartamento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txthorai, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtsalario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                                .addGap(9, 9, 9)))
                                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addComponent(lblfin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txthoraf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel3Layout.createSequentialGroup()
                                                .addComponent(lblcargo)
                                                .addGap(37, 37, 37)
                                                .addComponent(lblx6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncargo)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbinicio))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(btnayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMetric7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcedula)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblx))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblnombres)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblx1))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblapellidos)
                            .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblciuad)
                            .addComponent(btnbuscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblx2)
                            .addComponent(lblx4)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblx3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btncargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbldepartamento)
                        .addComponent(lblcargo)
                        .addComponent(txtdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblx6))
                    .addComponent(btndepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsalario)
                    .addComponent(txtsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblx5))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbinicio)
                    .addComponent(txthorai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfin)
                    .addComponent(txthoraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnnuevo))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusLost
        if (txtemail.getText().length() > 0) {
            boolean veri = validar.validaemail(txtemail.getText());
            if (veri == true) {

            } else {
                JOptionPane.showMessageDialog(this, "Direccion de Correo Invalido");
                txtemail.setText("");
                txtemail.requestFocus();
            }
        }
    }//GEN-LAST:event_txtemailFocusLost

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed

        conectar.conectar();
        String consulta = "select * from ciudades where ciudades.nombre_ciudad='" + txtciudad.getText() + "'";
        int indice = conectar.consultac1get(consulta, "cod_ciudad");
        int dep = conectar.consultac1get("select * from departamentos where nombre_dep='" + txtdepartamento.getText() + "'", "cod_dep");
        int cargo = conectar.consultac1get("select * from cargos where nombre_cargo='" + txtcargo.getText() + "'", "cod_cargo");
        String consuta = "INSERT INTO `alexanderflower`.`empleados` (`cedula_empleado`, `nombres_empleado`, `apellidos_empleado`, `direccion_empleado`, `telefono_empleado`, `ciudad_empleado`, `movil_empleado`, `estado_empleado`, `email_empleado`, `sueldo_empleado`, `cod_departamento`, `cod_cargo`, `horali`, `horalf`) VALUES ('" + txtcedula.getText() + "', '" + txtnombres.getText() + "', '" + txtapellidos.getText() + "', '" + txtdireccion.getText() + "', '" + txttelefono.getText() + "', " + indice + ", '" + txtmovil.getText() + "', '1', '" + txtemail.getText() + "', '" + txtsalario.getText() + "', '" + dep + "', '" + cargo + "', '" + txthorai.getText() + "', '" + txthoraf.getText() + "');";
        conectar.consultaset(consuta);
        conectar.desconectar();
        limpieza();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txttelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttelefonoFocusLost
        if (txttelefono.getText().length() > 0) {
            if (txttelefono.getText().length() > 6 && txttelefono.getText().length() < 8) {

            } else {
                txttelefono.setText("");
                txttelefono.requestFocus();
                JOptionPane.showMessageDialog(this, "Teléfono Invalido");
            }
        }
    }//GEN-LAST:event_txttelefonoFocusLost

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcedulaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtcedulaHierarchyChanged

    }//GEN-LAST:event_txtcedulaHierarchyChanged

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost

        cedula();
    }//GEN-LAST:event_txtcedulaFocusLost

    private void txtcedulaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtcedulaInputMethodTextChanged

    }//GEN-LAST:event_txtcedulaInputMethodTextChanged

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtcedulaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyPressed
        cedula();
    }//GEN-LAST:event_txtcedulaKeyPressed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtmovilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtmovilFocusLost
        if (txtmovil.getText().length() > 0) {
            if (txtmovil.getText().length() > 9 && txtmovil.getText().length() < 11) {

            } else {
                txtmovil.setText("");
                txtmovil.requestFocus();
                JOptionPane.showMessageDialog(this, "Móvil Invalido");
            }
        }
    }//GEN-LAST:event_txtmovilFocusLost

    private void txtmovilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmovilKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txtmovilKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        validar.sololetras(evt);
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void btnbuscarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcActionPerformed
        buscarciu nuevo = new buscarciu();
        clientesprov.eatadobset(4);
        dialogo jd = new dialogo(nuevo, true);
        jd.setContentPane(nuevo.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
    }//GEN-LAST:event_btnbuscarcActionPerformed
    private void cargar() {
        imagenes p = new imagenes("/proyecto_integrador/imagenes/fondo_gris.jpg");
        this.add(p);
        this.repaint();
        desactiva();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void txtcedulaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcedulaMouseMoved
        txtcedula.setToolTipText("Ingrese La Cedula  ");  // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaMouseMoved

    private void txtnombresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombresMouseMoved
        txtnombres.setToolTipText("Ingrese El Nombre");   // TODO add your handling code here:
    }//GEN-LAST:event_txtnombresMouseMoved

    private void txtapellidosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidosMouseMoved
        txtapellidos.setToolTipText("Ingrese El Apellido  ");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidosMouseMoved

    private void txtdireccionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdireccionMouseMoved
        txtdireccion.setToolTipText("Ingrese La Direccion ");   // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionMouseMoved

    private void txtemailMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseMoved

        txtemail.setToolTipText("Ingrese El Correo Electronico ");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailMouseMoved

    private void txttelefonoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttelefonoMouseMoved
        txttelefono.setToolTipText("Ingrese El Telefono  ");    // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoMouseMoved

    private void txtmovilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmovilMouseMoved

        txtmovil.setToolTipText("Ingrese el Numero de Celular ");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmovilMouseMoved

    private void txtciudadMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtciudadMouseMoved
        txtciudad.setToolTipText("Ingrese La Ciudad  ");            // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadMouseMoved

    private void btndepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepartamentoActionPerformed
        departamentos nu = new departamentos();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtdepartamento.setText(departamentos.departamento);
    }//GEN-LAST:event_btndepartamentoActionPerformed

    private void btncargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargoActionPerformed
        cargos nu = new cargos();
        dialogo jd = new dialogo(nu, true);
        jd.setContentPane(nu.getContentPane());
        jd.pack();
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        txtcargo.setText(cargos.cargo);
    }//GEN-LAST:event_btncargoActionPerformed

    private void txtsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalarioActionPerformed
        conectar.conectar();
        String suel = conectar.consultac2get("select * from parametros", "sueldobasico");
        if (Double.parseDouble(suel) < Double.parseDouble(txtsalario.getText())) {
            JOptionPane.showMessageDialog(this, "El sueldo es menor al sueldo basico");
        }
        conectar.desconectar();
    }//GEN-LAST:event_txtsalarioActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btnbuscarc;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncargo;
    private javax.swing.JButton btndepartamento;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private org.edisoncor.gui.label.LabelMetric labelMetric7;
    private javax.swing.JLabel lbinicio;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblciuad;
    private javax.swing.JLabel lbldepartamento;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblfin;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblsalario;
    private javax.swing.JLabel lblx;
    private javax.swing.JLabel lblx1;
    private javax.swing.JLabel lblx2;
    private javax.swing.JLabel lblx3;
    private javax.swing.JLabel lblx4;
    private javax.swing.JLabel lblx5;
    private javax.swing.JLabel lblx6;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcedula;
    public static javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtdepartamento;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JFormattedTextField txthoraf;
    private javax.swing.JFormattedTextField txthorai;
    private javax.swing.JTextField txtmovil;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
