/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parametros;

import clases.oayuda;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import proyecto_integrador.conexion;
import proyecto_integrador.inicio;
import proyecto_integrador.validaciones;

/**
 *
 * @author lab4-01
 */
public class informacionempresas extends javax.swing.JFrame {

    private Date fechaac = new Date();
    private final conexion conec = new conexion();
    private final validaciones validar = new validaciones();
    private int codigo;

    /**
     * Creates new form informacionempresas
     */
    public informacionempresas() {
        initComponents();
       arran();
    }

    private void arran() {
        dcfecha.setDate(fechaac);
        conec.conectar();
        String consulta = "select count(*) from empresa;";
        int dato = conec.consultac1get(consulta, "count(*)");
        String consulta1 = "select * from paises where estado_pais=1";
        cbpais.setModel(conec.consultacget(consulta1, "nombre_pais"));
        if (dato == 0) {
            btnactualizar.setVisible(false);
            panelparametros.arranquei = 1;
            btne.setVisible(false);

        } else if (dato != 0) {

            try {
                btnactualizar.setLocation(btnguardar.getLocation().x, btnguardar.getLocation().y);
                btnguardar.setVisible(false);
                consulta = "select * from empresa;";
                codigo = conec.consultac1get(consulta, "cod_empresa");
                txtempresa.setText("" + conec.consultac2get(consulta, "nombre_empresa"));
                txtdireccion.setText("" + conec.consultac2get(consulta, "direccion_empresa"));
                txttelefono.setText("" + conec.consultac2get(consulta, "telefono_empresa"));
                txtemail.setText("" + conec.consultac2get(consulta, "email_empresa"));
                txtencargado.setText("" + conec.consultac2get(consulta, "encargado_empresa"));
                txtruc.setText("" + conec.consultac2get(consulta, "ruc_empresa"));
                txtnumerof.setText("" + conec.consultac2get(consulta, "codigoms_empresa"));
                txtautorizacion.setText("" + conec.consultac2get(consulta, "autorizacionsri_empresa"));
                txtiniciof.setText("" + conec.consultac2get(consulta, "facturacioni_empresa"));
                txtfinalf.setText("" + conec.consultac2get(consulta, "facturacionf_empresa"));
                String fecha = conec.consultac2get(consulta, "fechacaducidadf_empresa");
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                Date nuevaFecha = formatoFecha.parse(fecha);
                dcfecha.setDate(nuevaFecha);
                cbprovincia.setModel(conec.consultacget("select nombre_provincia from provincias p, ciudades c where p.cod_provincia=c.cod_provincia and c.cod_ciudad=" + conec.consultac1get(consulta, "ciudad_empresa") + "", "nombre_provincia"));
                conec.conectar();
                cbciudad.setModel(conec.consultacget("select nombre_ciudad from ciudades where cod_ciudad=" + conec.consultac1get(consulta, "ciudad_empresa") + "", "nombre_ciudad"));
            } catch (ParseException ex) {
              
            }

        }
        conec.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        lblnumerof = new javax.swing.JLabel();
        lblfinf = new javax.swing.JLabel();
        lblcaducidadf = new javax.swing.JLabel();
        lblautorizacion = new javax.swing.JLabel();
        lbliniciof = new javax.swing.JLabel();
        lblruc = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        txtnumerof = new javax.swing.JTextField();
        txtautorizacion = new javax.swing.JTextField();
        txtiniciof = new javax.swing.JTextField();
        txtfinalf = new javax.swing.JTextField();
        lblencargado = new javax.swing.JLabel();
        txtencargado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btne = new javax.swing.JButton();
        dcfecha = new com.toedter.calendar.JDateChooser();
        lbltelefono = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        cbciudad = new javax.swing.JComboBox();
        txtempresa = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        lblciudad = new javax.swing.JLabel();
        lblpais = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblprovincia = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        lbldireccion = new javax.swing.JLabel();
        cbprovincia = new javax.swing.JComboBox();
        lbllocalidad = new javax.swing.JLabel();
        cbpais = new javax.swing.JComboBox();
        lblnombre = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 204, 102));

        lblnumerof.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblnumerof.setText("Numero de Facturacion");

        lblfinf.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblfinf.setText("Finalizacion de Facturado");

        lblcaducidadf.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblcaducidadf.setText("Fecha caducidad de Facturado");

        lblautorizacion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblautorizacion.setText("Autorizacion del SRI");

        lbliniciof.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbliniciof.setText("Inicio de Facturado");

        lblruc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblruc.setText("Ruc Empresa");

        txtruc.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        txtnumerof.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        txtautorizacion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        txtiniciof.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        txtfinalf.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        lblencargado.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblencargado.setText("Representante Legal");

        txtencargado.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("INFORMACION OPCIONAL");

        btne.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btne.setText("Actualizar Opcional");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        lbltelefono.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbltelefono.setText("Telefono Empresa");

        lblemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblemail.setText("Email Empresa");

        cbciudad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N

        txtempresa.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtempresa.setToolTipText("Ingresa la Informacion Aqui ");

        txtdireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtdireccion.setToolTipText("Ingresa la Informacion Aqui ");
        txtdireccion.setMinimumSize(new java.awt.Dimension(6, 20));

        lblciudad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblciudad.setText("Ciudad");

        lblpais.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblpais.setText("País");

        lbltitulo.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(51, 51, 255));
        lbltitulo.setText("INFORMACIÓN DE LA EMPRESA");

        lblprovincia.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblprovincia.setText("Provincia");

        txtemail.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txtemail.setToolTipText("Ingresa la Informacion Aqui ");
        txtemail.setMinimumSize(new java.awt.Dimension(6, 20));

        txttelefono.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        txttelefono.setToolTipText("Ingresa la Informacion Aqui ");
        txttelefono.setMinimumSize(new java.awt.Dimension(6, 20));
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        lbldireccion.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbldireccion.setText("Direccion Empresa");

        cbprovincia.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbprovinciaActionPerformed(evt);
            }
        });

        lbllocalidad.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lbllocalidad.setText("Localizacion Empresa");

        cbpais.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        cbpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbpaisActionPerformed(evt);
            }
        });
        cbpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbpaisKeyPressed(evt);
            }
        });

        lblnombre.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        lblnombre.setText("Nombre Empresa");

        btnguardar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnactualizar.setFont(new java.awt.Font("Adobe Caslon Pro", 0, 14)); // NOI18N
        btnactualizar.setText("Actualizar Empresa");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(btnguardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnactualizar))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createSequentialGroup()
                                            .addGap(130, 130, 130)
                                            .addComponent(jLabel1))
                                        .addComponent(lbllocalidad)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(lblnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblprovincia)
                                                    .addComponent(lblciudad)
                                                    .addComponent(lbltelefono)
                                                    .addComponent(lbldireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblemail, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblpais))
                                                .addGap(132, 132, 132)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbprovincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtdireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txttelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblruc)
                            .addComponent(lblcaducidadf)
                            .addComponent(lblfinf)
                            .addComponent(lbliniciof)
                            .addComponent(lblautorizacion)
                            .addComponent(lblnumerof)
                            .addComponent(lblencargado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtruc)
                            .addComponent(txtnumerof)
                            .addComponent(txtautorizacion)
                            .addComponent(txtiniciof)
                            .addComponent(txtfinalf)
                            .addComponent(txtencargado, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(dcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbllocalidad)
                .addGap(1, 1, 1)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbpais, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblprovincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblciudad)
                    .addComponent(cbciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbldireccion)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btnguardar))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblencargado)
                    .addComponent(txtencargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtruc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblruc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnumerof)
                    .addComponent(txtnumerof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblautorizacion)
                    .addComponent(txtautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiniciof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbliniciof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfinalf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfinf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcaducidadf)
                    .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
        int año = dcfecha.getCalendar().get(Calendar.YEAR);
        int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        conec.conectar();
        String consulta = "UPDATE `alexanderflower`.`empresa` SET `codigoms_empresa`='" + txtnumerof.getText() + "', `autorizacionsri_empresa`='" + txtautorizacion.getText() + "', `facturacioni_empresa`='" + txtiniciof.getText() + "', `facturacionf_empresa`='" + txtfinalf.getText() + "', `fechacaducidadf_empresa`='" + año + "-" + mes + "-" + dia + "', `encargado_empresa`='" + txtencargado.getText() + "', `ruc_empresa`='" + txtruc.getText() + "' WHERE `cod_empresa`='" + codigo + "';";
        conec.consultaset(consulta);
        conec.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btneActionPerformed

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        validar.solonumeros(evt);
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void cbprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbprovinciaActionPerformed
        conec.conectar();
        String consulta = "select * from provincias where provincias.nombre_provincia='" + cbprovincia.getSelectedItem() + "'";
        int indice = conec.consultac1get(consulta, "cod_provincia");
        consulta = "select * from ciudades where ciudades.cod_provincia=" + indice + " and estado_ciudad=1";
        cbciudad.setModel(conec.consultacget(consulta, "nombre_ciudad"));
        conec.desconectar();
    }//GEN-LAST:event_cbprovinciaActionPerformed

    private void cbpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbpaisActionPerformed
        conec.conectar();
        String consulta = "select * from paises where paises.nombre_pais='" + cbpais.getSelectedItem() + "'";
        int indice = conec.consultac1get(consulta, "cod_pais");
        consulta = "select * from provincias where provincias.cod_pais=" + indice + " and estado_provincia=1";
        cbprovincia.setModel(conec.consultacget(consulta, "nombre_provincia"));
        conec.desconectar();
    }//GEN-LAST:event_cbpaisActionPerformed

    private void cbpaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbpaisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbpaisKeyPressed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (!"".equals(txtempresa.getText()) || !"".equals(txtdireccion.getText()) || !"".equals(txttelefono.getText()) || !"".equals(txtemail.getText())) {
            conec.conectar();
            String consulta = "select * from ciudades where ciudades.nombre_ciudad='" + cbciudad.getSelectedItem() + "'";
            int indice = conec.consultac1get(consulta, "cod_ciudad");
            consulta = "INSERT INTO `alexanderflower`.`empresa` (`nombre_empresa`, `direccion_empresa`, `telefono_empresa`, `ciudad_empresa`, `email_empresa`) VALUES ('" + txtempresa.getText() + "', '" + txtdireccion.getText() + "', '" + txttelefono.getText() + "', '" + indice + "', '" + txtemail.getText() + "');";
            conec.consultaset(consulta);
            conec.desconectar();
            inicio nuevo = new inicio();
            nuevo.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        conec.conectar();
        String consulta = "select * from ciudades where ciudades.nombre_ciudad='" + cbciudad.getSelectedItem() + "'";
        int indice = conec.consultac1get(consulta, "cod_ciudad");
        consulta = "UPDATE `alexanderflower`.`empresa` SET `nombre_empresa`='" + txtempresa.getText() + "', `direccion_empresa`='" + txtdireccion.getText() + "', `telefono_empresa`='" + txttelefono.getText() + "', `ciudad_empresa`='" + indice + "', `email_empresa`='" + txtemail.getText() + "' WHERE `cod_empresa`='" + codigo + "';";
        conec.consultaset(consulta);
        conec.desconectar();
        this.setVisible(false);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informacionempresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informacionempresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informacionempresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informacionempresas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informacionempresas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox cbciudad;
    private javax.swing.JComboBox cbpais;
    private javax.swing.JComboBox cbprovincia;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblautorizacion;
    private javax.swing.JLabel lblcaducidadf;
    private javax.swing.JLabel lblciudad;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblencargado;
    private javax.swing.JLabel lblfinf;
    private javax.swing.JLabel lbliniciof;
    private javax.swing.JLabel lbllocalidad;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumerof;
    private javax.swing.JLabel lblpais;
    private javax.swing.JLabel lblprovincia;
    private javax.swing.JLabel lblruc;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField txtautorizacion;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtencargado;
    private javax.swing.JTextField txtfinalf;
    private javax.swing.JTextField txtiniciof;
    private javax.swing.JTextField txtnumerof;
    private javax.swing.JTextField txtruc;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
