/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;

import clases.controlformularios;
import clases.oayuda;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import proyecto_integrador.conexion;

/**
 *
 * @author Cristian
 */
public class balancec extends javax.swing.JFrame {

    conexion conec = new conexion();
    Date fecham = new Date();
    controlformularios cn = new controlformularios();

    /**
     * Creates new form balancec
     */
    public balancec() {
        initComponents();
        cargar();
    }

    private void cargar() {
        dcfecha.setDate(cn.fechasmas(fecham, -30));
        dcfecha1.setDate(fecham);
        conec.conectar();
        cbcuentas.setModel(conec.consultacget("select distinct des_cuenta from transacciones order by des_cuenta asc", "des_cuenta"));
        cbcuentas.addItem("Todos");
        cbcuentas.setSelectedIndex(cbcuentas.getItemCount() - 1);
        conec.desconectar();
    }

    private void cargart() {
        conec.conectar();
        String columnas[] = {"Cod. Cuenta", "Nom. Cuenta", "Debe", "Haber", "Debe", "Haber"};
        int año = dcfecha.getCalendar().get(Calendar.YEAR);
        int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
        int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        int año1 = dcfecha1.getCalendar().get(Calendar.YEAR);
        int mes1 = dcfecha1.getCalendar().get(Calendar.MONTH) + 1;
        int dia1 = dcfecha1.getCalendar().get(Calendar.DAY_OF_MONTH);
        if (cbcuentas.getSelectedIndex() == cbcuentas.getItemCount() - 1) {

            tabladatos.setModel(conec.consultaget("select cod_cuenta,des_cuenta,sum(t.debe),sum(t.haber) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "') group by t.des_cuenta", columnas));
            txtdebe.setText(conec.consultac2get("select sum(t.debe) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "')", "sum(t.debe)"));
            txthaber.setText(conec.consultac2get("select sum(t.haber) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "')", "sum(t.haber)"));

        } else {
            tabladatos.setModel(conec.consultaget("select cod_cuenta,des_cuenta,sum(t.debe),sum(t.haber) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "') and t.des_cuenta='" + cbcuentas.getSelectedItem().toString() + "' group by t.cod_cuenta", columnas));
            txtdebe.setText(conec.consultac2get("select sum(t.debe) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "') and t.des_cuenta='" + cbcuentas.getSelectedItem().toString() + "' group by t.cod_cuenta", "sum(t.debe)"));
            txthaber.setText(conec.consultac2get("select sum(t.haber) from transacciones t where (t.fecha_trans>='" + año + "-" + mes + "-" + dia + "' and t.fecha_trans<='" + año1 + "-" + mes1 + "-" + dia1 + "') and t.des_cuenta='" + cbcuentas.getSelectedItem().toString() + "' group by t.cod_cuenta", "sum(t.haber)"));

        }
        conec.desconectar();
        calculos();
    }

    private void calculos() {
        for (int i = 0; i < tabladatos.getRowCount(); i++) {
            if (Double.parseDouble(tabladatos.getValueAt(i, 2).toString()) > Double.parseDouble(tabladatos.getValueAt(i, 3).toString())) {
                tabladatos.setValueAt("0", i, 5);
                tabladatos.setValueAt(Double.parseDouble(tabladatos.getValueAt(i, 2).toString()) - Double.parseDouble(tabladatos.getValueAt(i, 3).toString()), i, 4);
            } else if (Double.parseDouble(tabladatos.getValueAt(i, 2).toString()) < Double.parseDouble(tabladatos.getValueAt(i, 3).toString())) {
                tabladatos.setValueAt("0", i, 4);
                tabladatos.setValueAt(Double.parseDouble(tabladatos.getValueAt(i, 3).toString()) - Double.parseDouble(tabladatos.getValueAt(i, 2).toString()), i, 5);
            } else if (Double.parseDouble(tabladatos.getValueAt(i, 2).toString()) == Double.parseDouble(tabladatos.getValueAt(i, 3).toString())) {
                tabladatos.setValueAt("0", i, 5);
                tabladatos.setValueAt("0", i, 4);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel6 = new org.edisoncor.gui.panel.Panel();
        btncancelar = new javax.swing.JButton();
        lblfecha = new javax.swing.JLabel();
        dcfecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        txthaber = new javax.swing.JTextField();
        lbltotal = new javax.swing.JLabel();
        txtdebe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblempresa = new org.edisoncor.gui.label.LabelMetric();
        dcfecha1 = new com.toedter.calendar.JDateChooser();
        lblfecha1 = new javax.swing.JLabel();
        cbcuentas = new javax.swing.JComboBox();
        lblcuentab = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnayuda = new javax.swing.JButton();

        panel6.setColorPrimario(new java.awt.Color(204, 255, 204));
        panel6.setColorSecundario(new java.awt.Color(255, 153, 0));

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        lblfecha.setText("FILTRAR DESDE ");

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabladatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladatos);

        txthaber.setEditable(false);

        lbltotal.setText("TOTALES");

        txtdebe.setEditable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clientes/portada.jpg"))); // NOI18N

        lblempresa.setForeground(new java.awt.Color(51, 51, 255));
        lblempresa.setText("BALANCE CONTABLE");
        lblempresa.setToolTipText("");
        lblempresa.setColorDeSombra(new java.awt.Color(255, 255, 255));
        lblempresa.setFont(new java.awt.Font("DS-Digital", 1, 48)); // NOI18N

        lblfecha1.setText("HASTA");

        cbcuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcuentasActionPerformed(evt);
            }
        });

        lblcuentab.setText("CUENTAS ");

        jTextField1.setBackground(new java.awt.Color(0, 255, 102));
        jTextField1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("SUMAS");
        jTextField1.setEnabled(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(0, 255, 102));
        jTextField2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("SALDOS");
        jTextField2.setEnabled(false);

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(93, 93, 93))
            .addGroup(panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel6Layout.createSequentialGroup()
                                .addComponent(lblfecha)
                                .addGap(18, 18, 18)
                                .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblfecha1)
                                .addGap(18, 18, 18)
                                .addComponent(dcfecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addComponent(lblcuentab, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbcuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panel6Layout.createSequentialGroup()
                                    .addComponent(lbltotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txthaber, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btncancelar)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createSequentialGroup()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnayuda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dcfecha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblfecha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcuentab, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbcuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotal)
                    .addComponent(txtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void tabladatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladatosMouseClicked

    }//GEN-LAST:event_tabladatosMouseClicked

    private void cbcuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcuentasActionPerformed
        cargart();
    }//GEN-LAST:event_cbcuentasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(balancec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(balancec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(balancec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(balancec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new balancec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btncancelar;
    private javax.swing.JComboBox cbcuentas;
    private com.toedter.calendar.JDateChooser dcfecha;
    private com.toedter.calendar.JDateChooser dcfecha1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblcuentab;
    private org.edisoncor.gui.label.LabelMetric lblempresa;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfecha1;
    private javax.swing.JLabel lbltotal;
    private org.edisoncor.gui.panel.Panel panel6;
    private javax.swing.JTable tabladatos;
    private javax.swing.JTextField txtdebe;
    private javax.swing.JTextField txthaber;
    // End of variables declaration//GEN-END:variables
}
