/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contabilidad;

import clases.oayuda;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyecto_integrador.conexion;

/**
 *
 * @author WINDOWS
 */
public class cierreperiodos extends javax.swing.JFrame {
    
    private conexion conec = new conexion();

    /**
     * Creates new form cierreperiodos
     */
    public cierreperiodos() {
        initComponents();
        cierresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbllistar = new javax.swing.JLabel();
        cbasientos = new javax.swing.JCheckBox();
        cbbalance = new javax.swing.JCheckBox();
        chganacias = new javax.swing.JCheckBox();
        lblcierres = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        lblcerrarfecha = new javax.swing.JLabel();
        dcfecha = new com.toedter.calendar.JDateChooser();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnayuda = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        lbllistar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lbllistar.setText("Listar");

        cbasientos.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cbasientos.setText("Asientos de cierre");

        cbbalance.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        cbbalance.setText("Balance general");

        chganacias.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        chganacias.setText("Ganancias y perdidad");

        lblcierres.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblcierres.setText("Cierres Previos");

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        lblcerrarfecha.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblcerrarfecha.setText("Cerrar a Fecha");

        dcfecha.setEnabled(false);

        btnaceptar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btnaceptar.setText("Realizar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_integrador/imagenes/ayudas.jpg"))); // NOI18N
        btnayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnayudaMouseClicked(evt);
            }
        });
        btnayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnayudaActionPerformed(evt);
            }
        });
        btnayuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnayudaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbasientos)
                                .addGap(144, 144, 144)
                                .addComponent(lblcierres)
                                .addGap(373, 373, 373))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chganacias)
                                    .addComponent(cbbalance)
                                    .addComponent(lblcerrarfecha)
                                    .addComponent(lbllistar))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnaceptar)
                        .addGap(4, 4, 4)
                        .addComponent(btncancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcerrarfecha)
                            .addComponent(dcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnayuda)))
                .addGap(22, 22, 22)
                .addComponent(lbllistar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcierres)
                    .addComponent(cbasientos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(cbbalance)
                        .addGap(18, 18, 18)
                        .addComponent(chganacias))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Date fechap = new Date();
    
    private void cierresh() {
        dcfecha.setDate(fechap);
        conec.conectar();
        String columnas[] = {"Codigo", "Fecha", "Ganancias", "Perdidas"};
        tabladatos.setModel(conec.consultaget("select * from cieres", columnas));
        conec.desconectar();
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened
    private Date fechaac = new Date();
    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        
        conec.conectar();
        if (conec.consultac1get("select count(*) from cieres", "count(*)") == 0) {
            int seleccion = JOptionPane.showOptionDialog(this, "¿Confimar el cierre de periodo", "Cierre de periodos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");
            if (seleccion == 0) {
                
                int año = dcfecha.getCalendar().get(Calendar.YEAR);
                int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
                int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
                
                conec.consultaset("INSERT INTO `alexanderflower`.`cieres` (`fecha_cierre`, `ganancias`, `perdidas`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select sum(t.haber) from transacciones t where t.fecha_trans<=curdate() ", "sum(t.haber)") + "', '" + conec.consultac2get("select sum(t.debe) from transacciones t where t.fecha_trans<=curdate() ", "sum(t.debe)") + "');");
                
            }
        } else {
            try {
                String fecha = conec.consultac2get("select * from cieres order by codigo_cierre desc  limit 1", "fecha_cierre");
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                Date nuevaFecha = formatoFecha.parse(fecha);
                if (fechaac.before(nuevaFecha)) {
                    int seleccion = JOptionPane.showOptionDialog(this, "¿Confimar el cierre de periodo", "Cierre de periodos", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, "Si");
                    if (seleccion == 0) {
                        
                        int año = dcfecha.getCalendar().get(Calendar.YEAR);
                        int mes = dcfecha.getCalendar().get(Calendar.MONTH) + 1;
                        int dia = dcfecha.getCalendar().get(Calendar.DAY_OF_MONTH);
                        
                        conec.consultaset("INSERT INTO `alexanderflower`.`cieres` (`fecha_cierre`, `ganancias`, `perdidas`) VALUES ('" + año + "-" + mes + "-" + dia + "', '" + conec.consultac2get("select sum(t.haber) from transacciones t where t.fecha_trans>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) ", "sum(t.haber)") + "', '" + conec.consultac2get("select sum(t.debe) from transacciones t where t.fecha_trans>=DATE_SUB(CURDATE(),INTERVAL 30 DAY) ", "sum(t.debe)") + "');");
                        
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Solo se realiza el cierre pasando \n mas de 30 dias");
                }
                
            } catch (ParseException ex) {
                Logger.getLogger(cierreperiodos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        conec.desconectar();
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnayudaMouseClicked
        try {
            oayuda ay = new oayuda();
            ay.opena("Manual.pdf");
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnayudaMouseClicked

    private void btnayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnayudaActionPerformed

    }//GEN-LAST:event_btnayudaActionPerformed

    private void btnayudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnayudaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                oayuda ay = new oayuda();
                ay.opena("Manual.pdf");
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_btnayudaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cierreperiodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cierreperiodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cierreperiodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cierreperiodos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cierreperiodos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btnayuda;
    private javax.swing.JButton btncancelar;
    private javax.swing.JCheckBox cbasientos;
    private javax.swing.JCheckBox cbbalance;
    private javax.swing.JCheckBox chganacias;
    private com.toedter.calendar.JDateChooser dcfecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcerrarfecha;
    private javax.swing.JLabel lblcierres;
    private javax.swing.JLabel lbllistar;
    private javax.swing.JTable tabladatos;
    // End of variables declaration//GEN-END:variables
}
